[[deployment]]
= Deployment information

[[deployment.deployables]]
== Building deployable units

[[deployment.deployables.jar]]
=== Building a deployable JAR

[source, bash]
----
$ ./mvnw clean package
----

The Spring Boot plugin contained in the build instruction will create a runnable artifact that can just be run with `java -jar target/*.jar`.

[[deployment.deployables.docker]]
=== Building a Docker container

To build a Docker container, you have to have Docker running on your machine.
If that's set, run the following command:

[source, bash]
----
$ ./mvnw clean spring-boot:build-image
----

That building a layered Docker image based on Paketo buildpacks.
More details on that https://spring.io/blog/2020/01/27/creating-docker-images-with-spring-boot-2-3-0-m1[here].

[[deployment.spring-profiles]]
== Spring profiles

The application uses Spring application profiles that allow configuration to carry different values and different features activated based on the profiles selected on startup.
The profiles are activated by setting the `spring.profile.active` property or environment variable respectively.

* `prod` -- Activated in production environments.
* `cloud` -- Activated on PaaS platforms like CloudFoundry.
* `staging` -- Profile activated on the development staging instance.
* `local` (not checked into the repository) -- if the file is created locally, it enables the Maven execution to automatically configure the `develop` profile for easy local execution.
The profile itself can be used to tweak settings (work against a locally installed database or the like).
* `develop` -- The profile to activate on the local developer machine (activated transparently in case an `application-local.properties` is placed under `src/main/resources`).
* `tracing` -- Enables tracing information about database interaction written to the log files.

Application functionality activated in the application based on profiles activated:

* `!prod` -- Test data is inserted on application startup.
* `develop` -- Switches the application to be run against an H2 in-memory database and a dummy mail server.
* `staging` -- Drops all tables of the database on application startup.

The profile configuration for the different deployment environments looks as follows:

* _Development_ - `staging`, triggers database (wipe and test data) reset on startup.
* _Test_ - TODO: investigate
* _Production_ - `prod`

[[deployment.security]]
== Security considerations

=== Third-party certificates

The <<third-party, API for third parties>> is <<third-party.authentication, secured>> by X509 certificates.
To allow this, the certificates provided by those applications need to be held in a trust store and configured with the application.
Deployments need to specify the following properties:

* `server.ssl.key-store` -- the path to the key store to be used.
* `server.ssl.key-store-password` -- the password to access the key store.
* `server.ssl.key-store-type` -- set to `JKS`
* `server.ssl.trust-store` -- the path to the trust store to be used containing the trusted certificates.
* `server.ssl.trust-store-password` -- the password to access the trust store.
* `server.ssl.trust-store-type` -- set to `JKS`
* `server.ssl.client-auth` -- set to `want` to enable client certificate authentication
