/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.52.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * CampaignFormElement
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-15T22:47:05.366577+01:00[Europe/Berlin]")
public class CampaignFormElement {
  @JsonProperty("type")
  private String type = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("caption")
  private String caption = null;

  @JsonProperty("styles")
  private List<String> styles = null;

  @JsonProperty("dependingOn")
  private String dependingOn = null;

  @JsonProperty("dependingOnValues")
  private List<String> dependingOnValues = null;

  @JsonProperty("important")
  private Boolean important = null;

  public CampaignFormElement type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public CampaignFormElement id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CampaignFormElement caption(String caption) {
    this.caption = caption;
    return this;
  }

   /**
   * Get caption
   * @return caption
  **/
  @Schema(description = "")
  public String getCaption() {
    return caption;
  }

  public void setCaption(String caption) {
    this.caption = caption;
  }

  public CampaignFormElement styles(List<String> styles) {
    this.styles = styles;
    return this;
  }

  public CampaignFormElement addStylesItem(String stylesItem) {
    if (this.styles == null) {
      this.styles = new ArrayList<>();
    }
    this.styles.add(stylesItem);
    return this;
  }

   /**
   * Get styles
   * @return styles
  **/
  @Schema(description = "")
  public List<String> getStyles() {
    return styles;
  }

  public void setStyles(List<String> styles) {
    this.styles = styles;
  }

  public CampaignFormElement dependingOn(String dependingOn) {
    this.dependingOn = dependingOn;
    return this;
  }

   /**
   * Get dependingOn
   * @return dependingOn
  **/
  @Schema(description = "")
  public String getDependingOn() {
    return dependingOn;
  }

  public void setDependingOn(String dependingOn) {
    this.dependingOn = dependingOn;
  }

  public CampaignFormElement dependingOnValues(List<String> dependingOnValues) {
    this.dependingOnValues = dependingOnValues;
    return this;
  }

  public CampaignFormElement addDependingOnValuesItem(String dependingOnValuesItem) {
    if (this.dependingOnValues == null) {
      this.dependingOnValues = new ArrayList<>();
    }
    this.dependingOnValues.add(dependingOnValuesItem);
    return this;
  }

   /**
   * Get dependingOnValues
   * @return dependingOnValues
  **/
  @Schema(description = "")
  public List<String> getDependingOnValues() {
    return dependingOnValues;
  }

  public void setDependingOnValues(List<String> dependingOnValues) {
    this.dependingOnValues = dependingOnValues;
  }

  public CampaignFormElement important(Boolean important) {
    this.important = important;
    return this;
  }

   /**
   * Get important
   * @return important
  **/
  @Schema(description = "")
  public Boolean isImportant() {
    return important;
  }

  public void setImportant(Boolean important) {
    this.important = important;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignFormElement campaignFormElement = (CampaignFormElement) o;
    return Objects.equals(this.type, campaignFormElement.type) &&
        Objects.equals(this.id, campaignFormElement.id) &&
        Objects.equals(this.caption, campaignFormElement.caption) &&
        Objects.equals(this.styles, campaignFormElement.styles) &&
        Objects.equals(this.dependingOn, campaignFormElement.dependingOn) &&
        Objects.equals(this.dependingOnValues, campaignFormElement.dependingOnValues) &&
        Objects.equals(this.important, campaignFormElement.important);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, id, caption, styles, dependingOn, dependingOnValues, important);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignFormElement {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    caption: ").append(toIndentedString(caption)).append("\n");
    sb.append("    styles: ").append(toIndentedString(styles)).append("\n");
    sb.append("    dependingOn: ").append(toIndentedString(dependingOn)).append("\n");
    sb.append("    dependingOnValues: ").append(toIndentedString(dependingOnValues)).append("\n");
    sb.append("    important: ").append(toIndentedString(important)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
