/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.52.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import de.quarano.sormas.client.model.CaseClassification;
import de.quarano.sormas.client.model.CaseOrigin;
import de.quarano.sormas.client.model.CaseOutcome;
import de.quarano.sormas.client.model.ClinicalCourseDto;
import de.quarano.sormas.client.model.CommunityReferenceDto;
import de.quarano.sormas.client.model.ContactTracingContactType;
import de.quarano.sormas.client.model.CovidTestReason;
import de.quarano.sormas.client.model.DengueFeverType;
import de.quarano.sormas.client.model.Disease;
import de.quarano.sormas.client.model.DistrictReferenceDto;
import de.quarano.sormas.client.model.EndOfIsolationReason;
import de.quarano.sormas.client.model.EpiDataDto;
import de.quarano.sormas.client.model.FacilityReferenceDto;
import de.quarano.sormas.client.model.FacilityType;
import de.quarano.sormas.client.model.FollowUpStatus;
import de.quarano.sormas.client.model.HospitalWardType;
import de.quarano.sormas.client.model.HospitalizationDto;
import de.quarano.sormas.client.model.InvestigationStatus;
import de.quarano.sormas.client.model.MaternalHistoryDto;
import de.quarano.sormas.client.model.PersonReferenceDto;
import de.quarano.sormas.client.model.PlagueType;
import de.quarano.sormas.client.model.PointOfEntryReferenceDto;
import de.quarano.sormas.client.model.PortHealthInfoDto;
import de.quarano.sormas.client.model.QuarantineReason;
import de.quarano.sormas.client.model.QuarantineType;
import de.quarano.sormas.client.model.RabiesType;
import de.quarano.sormas.client.model.RegionReferenceDto;
import de.quarano.sormas.client.model.ReportingType;
import de.quarano.sormas.client.model.SormasToSormasOriginInfoDto;
import de.quarano.sormas.client.model.SymptomsDto;
import de.quarano.sormas.client.model.TherapyDto;
import de.quarano.sormas.client.model.Trimester;
import de.quarano.sormas.client.model.UserReferenceDto;
import de.quarano.sormas.client.model.Vaccination;
import de.quarano.sormas.client.model.VaccinationInfoSource;
import de.quarano.sormas.client.model.YesNoUnknown;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
/**
 * CaseDataDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-15T22:47:05.366577+01:00[Europe/Berlin]")
public class CaseDataDto {
  @JsonProperty("creationDate")
  private OffsetDateTime creationDate = null;

  @JsonProperty("changeDate")
  private OffsetDateTime changeDate = null;

  @JsonProperty("uuid")
  private String uuid = null;

  @JsonProperty("pseudonymized")
  private Boolean pseudonymized = null;

  @JsonProperty("disease")
  private Disease disease = null;

  @JsonProperty("diseaseDetails")
  private String diseaseDetails = null;

  @JsonProperty("plagueType")
  private PlagueType plagueType = null;

  @JsonProperty("dengueFeverType")
  private DengueFeverType dengueFeverType = null;

  @JsonProperty("rabiesType")
  private RabiesType rabiesType = null;

  @JsonProperty("person")
  private PersonReferenceDto person = null;

  @JsonProperty("epidNumber")
  private String epidNumber = null;

  @JsonProperty("reportDate")
  private OffsetDateTime reportDate = null;

  @JsonProperty("reportingUser")
  private UserReferenceDto reportingUser = null;

  @JsonProperty("regionLevelDate")
  private OffsetDateTime regionLevelDate = null;

  @JsonProperty("nationalLevelDate")
  private OffsetDateTime nationalLevelDate = null;

  @JsonProperty("districtLevelDate")
  private OffsetDateTime districtLevelDate = null;

  @JsonProperty("caseClassification")
  private CaseClassification caseClassification = null;

  @JsonProperty("classificationUser")
  private UserReferenceDto classificationUser = null;

  @JsonProperty("classificationDate")
  private OffsetDateTime classificationDate = null;

  @JsonProperty("classificationComment")
  private String classificationComment = null;

  @JsonProperty("clinicalConfirmation")
  private YesNoUnknown clinicalConfirmation = null;

  @JsonProperty("epidemiologicalConfirmation")
  private YesNoUnknown epidemiologicalConfirmation = null;

  @JsonProperty("laboratoryDiagnosticConfirmation")
  private YesNoUnknown laboratoryDiagnosticConfirmation = null;

  @JsonProperty("investigationStatus")
  private InvestigationStatus investigationStatus = null;

  @JsonProperty("investigatedDate")
  private OffsetDateTime investigatedDate = null;

  @JsonProperty("outcome")
  private CaseOutcome outcome = null;

  @JsonProperty("outcomeDate")
  private OffsetDateTime outcomeDate = null;

  @JsonProperty("sequelae")
  private YesNoUnknown sequelae = null;

  @JsonProperty("sequelaeDetails")
  private String sequelaeDetails = null;

  @JsonProperty("region")
  private RegionReferenceDto region = null;

  @JsonProperty("district")
  private DistrictReferenceDto district = null;

  @JsonProperty("community")
  private CommunityReferenceDto community = null;

  @JsonProperty("facilityType")
  private FacilityType facilityType = null;

  @JsonProperty("healthFacility")
  private FacilityReferenceDto healthFacility = null;

  @JsonProperty("healthFacilityDetails")
  private String healthFacilityDetails = null;

  @JsonProperty("pregnant")
  private YesNoUnknown pregnant = null;

  @JsonProperty("vaccination")
  private Vaccination vaccination = null;

  @JsonProperty("vaccinationDoses")
  private String vaccinationDoses = null;

  @JsonProperty("vaccinationDate")
  private OffsetDateTime vaccinationDate = null;

  @JsonProperty("vaccinationInfoSource")
  private VaccinationInfoSource vaccinationInfoSource = null;

  @JsonProperty("vaccine")
  private String vaccine = null;

  @JsonProperty("smallpoxVaccinationScar")
  private YesNoUnknown smallpoxVaccinationScar = null;

  @JsonProperty("smallpoxVaccinationReceived")
  private YesNoUnknown smallpoxVaccinationReceived = null;

  @JsonProperty("surveillanceOfficer")
  private UserReferenceDto surveillanceOfficer = null;

  @JsonProperty("clinicianName")
  private String clinicianName = null;

  @JsonProperty("clinicianPhone")
  private String clinicianPhone = null;

  @JsonProperty("clinicianEmail")
  private String clinicianEmail = null;

  @JsonProperty("notifyingClinic")
  private HospitalWardType notifyingClinic = null;

  @JsonProperty("notifyingClinicDetails")
  private String notifyingClinicDetails = null;

  @JsonProperty("caseOfficer")
  private UserReferenceDto caseOfficer = null;

  @JsonProperty("reportLat")
  private Double reportLat = null;

  @JsonProperty("reportLon")
  private Double reportLon = null;

  @JsonProperty("reportLatLonAccuracy")
  private Float reportLatLonAccuracy = null;

  @JsonProperty("hospitalization")
  private HospitalizationDto hospitalization = null;

  @JsonProperty("symptoms")
  private SymptomsDto symptoms = null;

  @JsonProperty("epiData")
  private EpiDataDto epiData = null;

  @JsonProperty("therapy")
  private TherapyDto therapy = null;

  @JsonProperty("clinicalCourse")
  private ClinicalCourseDto clinicalCourse = null;

  @JsonProperty("maternalHistory")
  private MaternalHistoryDto maternalHistory = null;

  @JsonProperty("creationVersion")
  private String creationVersion = null;

  @JsonProperty("portHealthInfo")
  private PortHealthInfoDto portHealthInfo = null;

  @JsonProperty("caseOrigin")
  private CaseOrigin caseOrigin = null;

  @JsonProperty("pointOfEntry")
  private PointOfEntryReferenceDto pointOfEntry = null;

  @JsonProperty("pointOfEntryDetails")
  private String pointOfEntryDetails = null;

  @JsonProperty("additionalDetails")
  private String additionalDetails = null;

  @JsonProperty("externalID")
  private String externalID = null;

  @JsonProperty("sharedToCountry")
  private Boolean sharedToCountry = null;

  @JsonProperty("quarantine")
  private QuarantineType quarantine = null;

  @JsonProperty("quarantineTypeDetails")
  private String quarantineTypeDetails = null;

  @JsonProperty("quarantineFrom")
  private OffsetDateTime quarantineFrom = null;

  @JsonProperty("quarantineTo")
  private OffsetDateTime quarantineTo = null;

  @JsonProperty("quarantineHelpNeeded")
  private String quarantineHelpNeeded = null;

  @JsonProperty("quarantineOrderedVerbally")
  private Boolean quarantineOrderedVerbally = null;

  @JsonProperty("quarantineOrderedOfficialDocument")
  private Boolean quarantineOrderedOfficialDocument = null;

  @JsonProperty("quarantineOrderedVerballyDate")
  private OffsetDateTime quarantineOrderedVerballyDate = null;

  @JsonProperty("quarantineOrderedOfficialDocumentDate")
  private OffsetDateTime quarantineOrderedOfficialDocumentDate = null;

  @JsonProperty("quarantineHomePossible")
  private YesNoUnknown quarantineHomePossible = null;

  @JsonProperty("quarantineHomePossibleComment")
  private String quarantineHomePossibleComment = null;

  @JsonProperty("quarantineHomeSupplyEnsured")
  private YesNoUnknown quarantineHomeSupplyEnsured = null;

  @JsonProperty("quarantineHomeSupplyEnsuredComment")
  private String quarantineHomeSupplyEnsuredComment = null;

  @JsonProperty("quarantineExtended")
  private Boolean quarantineExtended = null;

  @JsonProperty("quarantineReduced")
  private Boolean quarantineReduced = null;

  @JsonProperty("quarantineOfficialOrderSent")
  private Boolean quarantineOfficialOrderSent = null;

  @JsonProperty("quarantineOfficialOrderSentDate")
  private OffsetDateTime quarantineOfficialOrderSentDate = null;

  @JsonProperty("reportingType")
  private ReportingType reportingType = null;

  @JsonProperty("postpartum")
  private YesNoUnknown postpartum = null;

  @JsonProperty("trimester")
  private Trimester trimester = null;

  @JsonProperty("followUpStatus")
  private FollowUpStatus followUpStatus = null;

  @JsonProperty("followUpComment")
  private String followUpComment = null;

  @JsonProperty("followUpUntil")
  private OffsetDateTime followUpUntil = null;

  @JsonProperty("overwriteFollowUpUntil")
  private Boolean overwriteFollowUpUntil = null;

  @JsonProperty("sormasToSormasOriginInfo")
  private SormasToSormasOriginInfoDto sormasToSormasOriginInfo = null;

  @JsonProperty("ownershipHandedOver")
  private Boolean ownershipHandedOver = null;

  @JsonProperty("caseIdIsm")
  private Integer caseIdIsm = null;

  @JsonProperty("covidTestReason")
  private CovidTestReason covidTestReason = null;

  @JsonProperty("covidTestReasonDetails")
  private String covidTestReasonDetails = null;

  @JsonProperty("contactTracingFirstContactType")
  private ContactTracingContactType contactTracingFirstContactType = null;

  @JsonProperty("contactTracingFirstContactDate")
  private OffsetDateTime contactTracingFirstContactDate = null;

  @JsonProperty("wasInQuarantineBeforeIsolation")
  private YesNoUnknown wasInQuarantineBeforeIsolation = null;

  @JsonProperty("quarantineReasonBeforeIsolation")
  private QuarantineReason quarantineReasonBeforeIsolation = null;

  @JsonProperty("quarantineReasonBeforeIsolationDetails")
  private String quarantineReasonBeforeIsolationDetails = null;

  @JsonProperty("endOfIsolationReason")
  private EndOfIsolationReason endOfIsolationReason = null;

  @JsonProperty("endOfIsolationReasonDetails")
  private String endOfIsolationReasonDetails = null;

  public CaseDataDto creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @Schema(description = "")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public CaseDataDto changeDate(OffsetDateTime changeDate) {
    this.changeDate = changeDate;
    return this;
  }

   /**
   * Get changeDate
   * @return changeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getChangeDate() {
    return changeDate;
  }

  public void setChangeDate(OffsetDateTime changeDate) {
    this.changeDate = changeDate;
  }

  public CaseDataDto uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @Schema(description = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public CaseDataDto pseudonymized(Boolean pseudonymized) {
    this.pseudonymized = pseudonymized;
    return this;
  }

   /**
   * Get pseudonymized
   * @return pseudonymized
  **/
  @Schema(description = "")
  public Boolean isPseudonymized() {
    return pseudonymized;
  }

  public void setPseudonymized(Boolean pseudonymized) {
    this.pseudonymized = pseudonymized;
  }

  public CaseDataDto disease(Disease disease) {
    this.disease = disease;
    return this;
  }

   /**
   * Get disease
   * @return disease
  **/
  @Schema(required = true, description = "")
  public Disease getDisease() {
    return disease;
  }

  public void setDisease(Disease disease) {
    this.disease = disease;
  }

  public CaseDataDto diseaseDetails(String diseaseDetails) {
    this.diseaseDetails = diseaseDetails;
    return this;
  }

   /**
   * Get diseaseDetails
   * @return diseaseDetails
  **/
  @Schema(description = "")
  public String getDiseaseDetails() {
    return diseaseDetails;
  }

  public void setDiseaseDetails(String diseaseDetails) {
    this.diseaseDetails = diseaseDetails;
  }

  public CaseDataDto plagueType(PlagueType plagueType) {
    this.plagueType = plagueType;
    return this;
  }

   /**
   * Get plagueType
   * @return plagueType
  **/
  @Schema(description = "")
  public PlagueType getPlagueType() {
    return plagueType;
  }

  public void setPlagueType(PlagueType plagueType) {
    this.plagueType = plagueType;
  }

  public CaseDataDto dengueFeverType(DengueFeverType dengueFeverType) {
    this.dengueFeverType = dengueFeverType;
    return this;
  }

   /**
   * Get dengueFeverType
   * @return dengueFeverType
  **/
  @Schema(description = "")
  public DengueFeverType getDengueFeverType() {
    return dengueFeverType;
  }

  public void setDengueFeverType(DengueFeverType dengueFeverType) {
    this.dengueFeverType = dengueFeverType;
  }

  public CaseDataDto rabiesType(RabiesType rabiesType) {
    this.rabiesType = rabiesType;
    return this;
  }

   /**
   * Get rabiesType
   * @return rabiesType
  **/
  @Schema(description = "")
  public RabiesType getRabiesType() {
    return rabiesType;
  }

  public void setRabiesType(RabiesType rabiesType) {
    this.rabiesType = rabiesType;
  }

  public CaseDataDto person(PersonReferenceDto person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  @Schema(required = true, description = "")
  public PersonReferenceDto getPerson() {
    return person;
  }

  public void setPerson(PersonReferenceDto person) {
    this.person = person;
  }

  public CaseDataDto epidNumber(String epidNumber) {
    this.epidNumber = epidNumber;
    return this;
  }

   /**
   * Get epidNumber
   * @return epidNumber
  **/
  @Schema(description = "")
  public String getEpidNumber() {
    return epidNumber;
  }

  public void setEpidNumber(String epidNumber) {
    this.epidNumber = epidNumber;
  }

  public CaseDataDto reportDate(OffsetDateTime reportDate) {
    this.reportDate = reportDate;
    return this;
  }

   /**
   * Get reportDate
   * @return reportDate
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getReportDate() {
    return reportDate;
  }

  public void setReportDate(OffsetDateTime reportDate) {
    this.reportDate = reportDate;
  }

  public CaseDataDto reportingUser(UserReferenceDto reportingUser) {
    this.reportingUser = reportingUser;
    return this;
  }

   /**
   * Get reportingUser
   * @return reportingUser
  **/
  @Schema(required = true, description = "")
  public UserReferenceDto getReportingUser() {
    return reportingUser;
  }

  public void setReportingUser(UserReferenceDto reportingUser) {
    this.reportingUser = reportingUser;
  }

  public CaseDataDto regionLevelDate(OffsetDateTime regionLevelDate) {
    this.regionLevelDate = regionLevelDate;
    return this;
  }

   /**
   * Get regionLevelDate
   * @return regionLevelDate
  **/
  @Schema(description = "")
  public OffsetDateTime getRegionLevelDate() {
    return regionLevelDate;
  }

  public void setRegionLevelDate(OffsetDateTime regionLevelDate) {
    this.regionLevelDate = regionLevelDate;
  }

  public CaseDataDto nationalLevelDate(OffsetDateTime nationalLevelDate) {
    this.nationalLevelDate = nationalLevelDate;
    return this;
  }

   /**
   * Get nationalLevelDate
   * @return nationalLevelDate
  **/
  @Schema(description = "")
  public OffsetDateTime getNationalLevelDate() {
    return nationalLevelDate;
  }

  public void setNationalLevelDate(OffsetDateTime nationalLevelDate) {
    this.nationalLevelDate = nationalLevelDate;
  }

  public CaseDataDto districtLevelDate(OffsetDateTime districtLevelDate) {
    this.districtLevelDate = districtLevelDate;
    return this;
  }

   /**
   * Get districtLevelDate
   * @return districtLevelDate
  **/
  @Schema(description = "")
  public OffsetDateTime getDistrictLevelDate() {
    return districtLevelDate;
  }

  public void setDistrictLevelDate(OffsetDateTime districtLevelDate) {
    this.districtLevelDate = districtLevelDate;
  }

  public CaseDataDto caseClassification(CaseClassification caseClassification) {
    this.caseClassification = caseClassification;
    return this;
  }

   /**
   * Get caseClassification
   * @return caseClassification
  **/
  @Schema(required = true, description = "")
  public CaseClassification getCaseClassification() {
    return caseClassification;
  }

  public void setCaseClassification(CaseClassification caseClassification) {
    this.caseClassification = caseClassification;
  }

  public CaseDataDto classificationUser(UserReferenceDto classificationUser) {
    this.classificationUser = classificationUser;
    return this;
  }

   /**
   * Get classificationUser
   * @return classificationUser
  **/
  @Schema(description = "")
  public UserReferenceDto getClassificationUser() {
    return classificationUser;
  }

  public void setClassificationUser(UserReferenceDto classificationUser) {
    this.classificationUser = classificationUser;
  }

  public CaseDataDto classificationDate(OffsetDateTime classificationDate) {
    this.classificationDate = classificationDate;
    return this;
  }

   /**
   * Get classificationDate
   * @return classificationDate
  **/
  @Schema(description = "")
  public OffsetDateTime getClassificationDate() {
    return classificationDate;
  }

  public void setClassificationDate(OffsetDateTime classificationDate) {
    this.classificationDate = classificationDate;
  }

  public CaseDataDto classificationComment(String classificationComment) {
    this.classificationComment = classificationComment;
    return this;
  }

   /**
   * Get classificationComment
   * @return classificationComment
  **/
  @Schema(description = "")
  public String getClassificationComment() {
    return classificationComment;
  }

  public void setClassificationComment(String classificationComment) {
    this.classificationComment = classificationComment;
  }

  public CaseDataDto clinicalConfirmation(YesNoUnknown clinicalConfirmation) {
    this.clinicalConfirmation = clinicalConfirmation;
    return this;
  }

   /**
   * Get clinicalConfirmation
   * @return clinicalConfirmation
  **/
  @Schema(description = "")
  public YesNoUnknown getClinicalConfirmation() {
    return clinicalConfirmation;
  }

  public void setClinicalConfirmation(YesNoUnknown clinicalConfirmation) {
    this.clinicalConfirmation = clinicalConfirmation;
  }

  public CaseDataDto epidemiologicalConfirmation(YesNoUnknown epidemiologicalConfirmation) {
    this.epidemiologicalConfirmation = epidemiologicalConfirmation;
    return this;
  }

   /**
   * Get epidemiologicalConfirmation
   * @return epidemiologicalConfirmation
  **/
  @Schema(description = "")
  public YesNoUnknown getEpidemiologicalConfirmation() {
    return epidemiologicalConfirmation;
  }

  public void setEpidemiologicalConfirmation(YesNoUnknown epidemiologicalConfirmation) {
    this.epidemiologicalConfirmation = epidemiologicalConfirmation;
  }

  public CaseDataDto laboratoryDiagnosticConfirmation(YesNoUnknown laboratoryDiagnosticConfirmation) {
    this.laboratoryDiagnosticConfirmation = laboratoryDiagnosticConfirmation;
    return this;
  }

   /**
   * Get laboratoryDiagnosticConfirmation
   * @return laboratoryDiagnosticConfirmation
  **/
  @Schema(description = "")
  public YesNoUnknown getLaboratoryDiagnosticConfirmation() {
    return laboratoryDiagnosticConfirmation;
  }

  public void setLaboratoryDiagnosticConfirmation(YesNoUnknown laboratoryDiagnosticConfirmation) {
    this.laboratoryDiagnosticConfirmation = laboratoryDiagnosticConfirmation;
  }

  public CaseDataDto investigationStatus(InvestigationStatus investigationStatus) {
    this.investigationStatus = investigationStatus;
    return this;
  }

   /**
   * Get investigationStatus
   * @return investigationStatus
  **/
  @Schema(required = true, description = "")
  public InvestigationStatus getInvestigationStatus() {
    return investigationStatus;
  }

  public void setInvestigationStatus(InvestigationStatus investigationStatus) {
    this.investigationStatus = investigationStatus;
  }

  public CaseDataDto investigatedDate(OffsetDateTime investigatedDate) {
    this.investigatedDate = investigatedDate;
    return this;
  }

   /**
   * Get investigatedDate
   * @return investigatedDate
  **/
  @Schema(description = "")
  public OffsetDateTime getInvestigatedDate() {
    return investigatedDate;
  }

  public void setInvestigatedDate(OffsetDateTime investigatedDate) {
    this.investigatedDate = investigatedDate;
  }

  public CaseDataDto outcome(CaseOutcome outcome) {
    this.outcome = outcome;
    return this;
  }

   /**
   * Get outcome
   * @return outcome
  **/
  @Schema(description = "")
  public CaseOutcome getOutcome() {
    return outcome;
  }

  public void setOutcome(CaseOutcome outcome) {
    this.outcome = outcome;
  }

  public CaseDataDto outcomeDate(OffsetDateTime outcomeDate) {
    this.outcomeDate = outcomeDate;
    return this;
  }

   /**
   * Get outcomeDate
   * @return outcomeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getOutcomeDate() {
    return outcomeDate;
  }

  public void setOutcomeDate(OffsetDateTime outcomeDate) {
    this.outcomeDate = outcomeDate;
  }

  public CaseDataDto sequelae(YesNoUnknown sequelae) {
    this.sequelae = sequelae;
    return this;
  }

   /**
   * Get sequelae
   * @return sequelae
  **/
  @Schema(description = "")
  public YesNoUnknown getSequelae() {
    return sequelae;
  }

  public void setSequelae(YesNoUnknown sequelae) {
    this.sequelae = sequelae;
  }

  public CaseDataDto sequelaeDetails(String sequelaeDetails) {
    this.sequelaeDetails = sequelaeDetails;
    return this;
  }

   /**
   * Get sequelaeDetails
   * @return sequelaeDetails
  **/
  @Schema(description = "")
  public String getSequelaeDetails() {
    return sequelaeDetails;
  }

  public void setSequelaeDetails(String sequelaeDetails) {
    this.sequelaeDetails = sequelaeDetails;
  }

  public CaseDataDto region(RegionReferenceDto region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @Schema(required = true, description = "")
  public RegionReferenceDto getRegion() {
    return region;
  }

  public void setRegion(RegionReferenceDto region) {
    this.region = region;
  }

  public CaseDataDto district(DistrictReferenceDto district) {
    this.district = district;
    return this;
  }

   /**
   * Get district
   * @return district
  **/
  @Schema(required = true, description = "")
  public DistrictReferenceDto getDistrict() {
    return district;
  }

  public void setDistrict(DistrictReferenceDto district) {
    this.district = district;
  }

  public CaseDataDto community(CommunityReferenceDto community) {
    this.community = community;
    return this;
  }

   /**
   * Get community
   * @return community
  **/
  @Schema(description = "")
  public CommunityReferenceDto getCommunity() {
    return community;
  }

  public void setCommunity(CommunityReferenceDto community) {
    this.community = community;
  }

  public CaseDataDto facilityType(FacilityType facilityType) {
    this.facilityType = facilityType;
    return this;
  }

   /**
   * Get facilityType
   * @return facilityType
  **/
  @Schema(description = "")
  public FacilityType getFacilityType() {
    return facilityType;
  }

  public void setFacilityType(FacilityType facilityType) {
    this.facilityType = facilityType;
  }

  public CaseDataDto healthFacility(FacilityReferenceDto healthFacility) {
    this.healthFacility = healthFacility;
    return this;
  }

   /**
   * Get healthFacility
   * @return healthFacility
  **/
  @Schema(required = true, description = "")
  public FacilityReferenceDto getHealthFacility() {
    return healthFacility;
  }

  public void setHealthFacility(FacilityReferenceDto healthFacility) {
    this.healthFacility = healthFacility;
  }

  public CaseDataDto healthFacilityDetails(String healthFacilityDetails) {
    this.healthFacilityDetails = healthFacilityDetails;
    return this;
  }

   /**
   * Get healthFacilityDetails
   * @return healthFacilityDetails
  **/
  @Schema(description = "")
  public String getHealthFacilityDetails() {
    return healthFacilityDetails;
  }

  public void setHealthFacilityDetails(String healthFacilityDetails) {
    this.healthFacilityDetails = healthFacilityDetails;
  }

  public CaseDataDto pregnant(YesNoUnknown pregnant) {
    this.pregnant = pregnant;
    return this;
  }

   /**
   * Get pregnant
   * @return pregnant
  **/
  @Schema(description = "")
  public YesNoUnknown getPregnant() {
    return pregnant;
  }

  public void setPregnant(YesNoUnknown pregnant) {
    this.pregnant = pregnant;
  }

  public CaseDataDto vaccination(Vaccination vaccination) {
    this.vaccination = vaccination;
    return this;
  }

   /**
   * Get vaccination
   * @return vaccination
  **/
  @Schema(description = "")
  public Vaccination getVaccination() {
    return vaccination;
  }

  public void setVaccination(Vaccination vaccination) {
    this.vaccination = vaccination;
  }

  public CaseDataDto vaccinationDoses(String vaccinationDoses) {
    this.vaccinationDoses = vaccinationDoses;
    return this;
  }

   /**
   * Get vaccinationDoses
   * @return vaccinationDoses
  **/
  @Schema(description = "")
  public String getVaccinationDoses() {
    return vaccinationDoses;
  }

  public void setVaccinationDoses(String vaccinationDoses) {
    this.vaccinationDoses = vaccinationDoses;
  }

  public CaseDataDto vaccinationDate(OffsetDateTime vaccinationDate) {
    this.vaccinationDate = vaccinationDate;
    return this;
  }

   /**
   * Get vaccinationDate
   * @return vaccinationDate
  **/
  @Schema(description = "")
  public OffsetDateTime getVaccinationDate() {
    return vaccinationDate;
  }

  public void setVaccinationDate(OffsetDateTime vaccinationDate) {
    this.vaccinationDate = vaccinationDate;
  }

  public CaseDataDto vaccinationInfoSource(VaccinationInfoSource vaccinationInfoSource) {
    this.vaccinationInfoSource = vaccinationInfoSource;
    return this;
  }

   /**
   * Get vaccinationInfoSource
   * @return vaccinationInfoSource
  **/
  @Schema(description = "")
  public VaccinationInfoSource getVaccinationInfoSource() {
    return vaccinationInfoSource;
  }

  public void setVaccinationInfoSource(VaccinationInfoSource vaccinationInfoSource) {
    this.vaccinationInfoSource = vaccinationInfoSource;
  }

  public CaseDataDto vaccine(String vaccine) {
    this.vaccine = vaccine;
    return this;
  }

   /**
   * Get vaccine
   * @return vaccine
  **/
  @Schema(description = "")
  public String getVaccine() {
    return vaccine;
  }

  public void setVaccine(String vaccine) {
    this.vaccine = vaccine;
  }

  public CaseDataDto smallpoxVaccinationScar(YesNoUnknown smallpoxVaccinationScar) {
    this.smallpoxVaccinationScar = smallpoxVaccinationScar;
    return this;
  }

   /**
   * Get smallpoxVaccinationScar
   * @return smallpoxVaccinationScar
  **/
  @Schema(description = "")
  public YesNoUnknown getSmallpoxVaccinationScar() {
    return smallpoxVaccinationScar;
  }

  public void setSmallpoxVaccinationScar(YesNoUnknown smallpoxVaccinationScar) {
    this.smallpoxVaccinationScar = smallpoxVaccinationScar;
  }

  public CaseDataDto smallpoxVaccinationReceived(YesNoUnknown smallpoxVaccinationReceived) {
    this.smallpoxVaccinationReceived = smallpoxVaccinationReceived;
    return this;
  }

   /**
   * Get smallpoxVaccinationReceived
   * @return smallpoxVaccinationReceived
  **/
  @Schema(description = "")
  public YesNoUnknown getSmallpoxVaccinationReceived() {
    return smallpoxVaccinationReceived;
  }

  public void setSmallpoxVaccinationReceived(YesNoUnknown smallpoxVaccinationReceived) {
    this.smallpoxVaccinationReceived = smallpoxVaccinationReceived;
  }

  public CaseDataDto surveillanceOfficer(UserReferenceDto surveillanceOfficer) {
    this.surveillanceOfficer = surveillanceOfficer;
    return this;
  }

   /**
   * Get surveillanceOfficer
   * @return surveillanceOfficer
  **/
  @Schema(description = "")
  public UserReferenceDto getSurveillanceOfficer() {
    return surveillanceOfficer;
  }

  public void setSurveillanceOfficer(UserReferenceDto surveillanceOfficer) {
    this.surveillanceOfficer = surveillanceOfficer;
  }

  public CaseDataDto clinicianName(String clinicianName) {
    this.clinicianName = clinicianName;
    return this;
  }

   /**
   * Get clinicianName
   * @return clinicianName
  **/
  @Schema(description = "")
  public String getClinicianName() {
    return clinicianName;
  }

  public void setClinicianName(String clinicianName) {
    this.clinicianName = clinicianName;
  }

  public CaseDataDto clinicianPhone(String clinicianPhone) {
    this.clinicianPhone = clinicianPhone;
    return this;
  }

   /**
   * Get clinicianPhone
   * @return clinicianPhone
  **/
  @Schema(description = "")
  public String getClinicianPhone() {
    return clinicianPhone;
  }

  public void setClinicianPhone(String clinicianPhone) {
    this.clinicianPhone = clinicianPhone;
  }

  public CaseDataDto clinicianEmail(String clinicianEmail) {
    this.clinicianEmail = clinicianEmail;
    return this;
  }

   /**
   * Get clinicianEmail
   * @return clinicianEmail
  **/
  @Schema(description = "")
  public String getClinicianEmail() {
    return clinicianEmail;
  }

  public void setClinicianEmail(String clinicianEmail) {
    this.clinicianEmail = clinicianEmail;
  }

  public CaseDataDto notifyingClinic(HospitalWardType notifyingClinic) {
    this.notifyingClinic = notifyingClinic;
    return this;
  }

   /**
   * Get notifyingClinic
   * @return notifyingClinic
  **/
  @Schema(description = "")
  public HospitalWardType getNotifyingClinic() {
    return notifyingClinic;
  }

  public void setNotifyingClinic(HospitalWardType notifyingClinic) {
    this.notifyingClinic = notifyingClinic;
  }

  public CaseDataDto notifyingClinicDetails(String notifyingClinicDetails) {
    this.notifyingClinicDetails = notifyingClinicDetails;
    return this;
  }

   /**
   * Get notifyingClinicDetails
   * @return notifyingClinicDetails
  **/
  @Schema(description = "")
  public String getNotifyingClinicDetails() {
    return notifyingClinicDetails;
  }

  public void setNotifyingClinicDetails(String notifyingClinicDetails) {
    this.notifyingClinicDetails = notifyingClinicDetails;
  }

  public CaseDataDto caseOfficer(UserReferenceDto caseOfficer) {
    this.caseOfficer = caseOfficer;
    return this;
  }

   /**
   * Get caseOfficer
   * @return caseOfficer
  **/
  @Schema(description = "")
  public UserReferenceDto getCaseOfficer() {
    return caseOfficer;
  }

  public void setCaseOfficer(UserReferenceDto caseOfficer) {
    this.caseOfficer = caseOfficer;
  }

  public CaseDataDto reportLat(Double reportLat) {
    this.reportLat = reportLat;
    return this;
  }

   /**
   * Get reportLat
   * @return reportLat
  **/
  @Schema(description = "")
  public Double getReportLat() {
    return reportLat;
  }

  public void setReportLat(Double reportLat) {
    this.reportLat = reportLat;
  }

  public CaseDataDto reportLon(Double reportLon) {
    this.reportLon = reportLon;
    return this;
  }

   /**
   * Get reportLon
   * @return reportLon
  **/
  @Schema(description = "")
  public Double getReportLon() {
    return reportLon;
  }

  public void setReportLon(Double reportLon) {
    this.reportLon = reportLon;
  }

  public CaseDataDto reportLatLonAccuracy(Float reportLatLonAccuracy) {
    this.reportLatLonAccuracy = reportLatLonAccuracy;
    return this;
  }

   /**
   * Get reportLatLonAccuracy
   * @return reportLatLonAccuracy
  **/
  @Schema(description = "")
  public Float getReportLatLonAccuracy() {
    return reportLatLonAccuracy;
  }

  public void setReportLatLonAccuracy(Float reportLatLonAccuracy) {
    this.reportLatLonAccuracy = reportLatLonAccuracy;
  }

  public CaseDataDto hospitalization(HospitalizationDto hospitalization) {
    this.hospitalization = hospitalization;
    return this;
  }

   /**
   * Get hospitalization
   * @return hospitalization
  **/
  @Schema(description = "")
  public HospitalizationDto getHospitalization() {
    return hospitalization;
  }

  public void setHospitalization(HospitalizationDto hospitalization) {
    this.hospitalization = hospitalization;
  }

  public CaseDataDto symptoms(SymptomsDto symptoms) {
    this.symptoms = symptoms;
    return this;
  }

   /**
   * Get symptoms
   * @return symptoms
  **/
  @Schema(description = "")
  public SymptomsDto getSymptoms() {
    return symptoms;
  }

  public void setSymptoms(SymptomsDto symptoms) {
    this.symptoms = symptoms;
  }

  public CaseDataDto epiData(EpiDataDto epiData) {
    this.epiData = epiData;
    return this;
  }

   /**
   * Get epiData
   * @return epiData
  **/
  @Schema(description = "")
  public EpiDataDto getEpiData() {
    return epiData;
  }

  public void setEpiData(EpiDataDto epiData) {
    this.epiData = epiData;
  }

  public CaseDataDto therapy(TherapyDto therapy) {
    this.therapy = therapy;
    return this;
  }

   /**
   * Get therapy
   * @return therapy
  **/
  @Schema(description = "")
  public TherapyDto getTherapy() {
    return therapy;
  }

  public void setTherapy(TherapyDto therapy) {
    this.therapy = therapy;
  }

  public CaseDataDto clinicalCourse(ClinicalCourseDto clinicalCourse) {
    this.clinicalCourse = clinicalCourse;
    return this;
  }

   /**
   * Get clinicalCourse
   * @return clinicalCourse
  **/
  @Schema(description = "")
  public ClinicalCourseDto getClinicalCourse() {
    return clinicalCourse;
  }

  public void setClinicalCourse(ClinicalCourseDto clinicalCourse) {
    this.clinicalCourse = clinicalCourse;
  }

  public CaseDataDto maternalHistory(MaternalHistoryDto maternalHistory) {
    this.maternalHistory = maternalHistory;
    return this;
  }

   /**
   * Get maternalHistory
   * @return maternalHistory
  **/
  @Schema(description = "")
  public MaternalHistoryDto getMaternalHistory() {
    return maternalHistory;
  }

  public void setMaternalHistory(MaternalHistoryDto maternalHistory) {
    this.maternalHistory = maternalHistory;
  }

  public CaseDataDto creationVersion(String creationVersion) {
    this.creationVersion = creationVersion;
    return this;
  }

   /**
   * Get creationVersion
   * @return creationVersion
  **/
  @Schema(description = "")
  public String getCreationVersion() {
    return creationVersion;
  }

  public void setCreationVersion(String creationVersion) {
    this.creationVersion = creationVersion;
  }

  public CaseDataDto portHealthInfo(PortHealthInfoDto portHealthInfo) {
    this.portHealthInfo = portHealthInfo;
    return this;
  }

   /**
   * Get portHealthInfo
   * @return portHealthInfo
  **/
  @Schema(description = "")
  public PortHealthInfoDto getPortHealthInfo() {
    return portHealthInfo;
  }

  public void setPortHealthInfo(PortHealthInfoDto portHealthInfo) {
    this.portHealthInfo = portHealthInfo;
  }

  public CaseDataDto caseOrigin(CaseOrigin caseOrigin) {
    this.caseOrigin = caseOrigin;
    return this;
  }

   /**
   * Get caseOrigin
   * @return caseOrigin
  **/
  @Schema(description = "")
  public CaseOrigin getCaseOrigin() {
    return caseOrigin;
  }

  public void setCaseOrigin(CaseOrigin caseOrigin) {
    this.caseOrigin = caseOrigin;
  }

  public CaseDataDto pointOfEntry(PointOfEntryReferenceDto pointOfEntry) {
    this.pointOfEntry = pointOfEntry;
    return this;
  }

   /**
   * Get pointOfEntry
   * @return pointOfEntry
  **/
  @Schema(description = "")
  public PointOfEntryReferenceDto getPointOfEntry() {
    return pointOfEntry;
  }

  public void setPointOfEntry(PointOfEntryReferenceDto pointOfEntry) {
    this.pointOfEntry = pointOfEntry;
  }

  public CaseDataDto pointOfEntryDetails(String pointOfEntryDetails) {
    this.pointOfEntryDetails = pointOfEntryDetails;
    return this;
  }

   /**
   * Get pointOfEntryDetails
   * @return pointOfEntryDetails
  **/
  @Schema(description = "")
  public String getPointOfEntryDetails() {
    return pointOfEntryDetails;
  }

  public void setPointOfEntryDetails(String pointOfEntryDetails) {
    this.pointOfEntryDetails = pointOfEntryDetails;
  }

  public CaseDataDto additionalDetails(String additionalDetails) {
    this.additionalDetails = additionalDetails;
    return this;
  }

   /**
   * Get additionalDetails
   * @return additionalDetails
  **/
  @Schema(description = "")
  public String getAdditionalDetails() {
    return additionalDetails;
  }

  public void setAdditionalDetails(String additionalDetails) {
    this.additionalDetails = additionalDetails;
  }

  public CaseDataDto externalID(String externalID) {
    this.externalID = externalID;
    return this;
  }

   /**
   * Get externalID
   * @return externalID
  **/
  @Schema(description = "")
  public String getExternalID() {
    return externalID;
  }

  public void setExternalID(String externalID) {
    this.externalID = externalID;
  }

  public CaseDataDto sharedToCountry(Boolean sharedToCountry) {
    this.sharedToCountry = sharedToCountry;
    return this;
  }

   /**
   * Get sharedToCountry
   * @return sharedToCountry
  **/
  @Schema(description = "")
  public Boolean isSharedToCountry() {
    return sharedToCountry;
  }

  public void setSharedToCountry(Boolean sharedToCountry) {
    this.sharedToCountry = sharedToCountry;
  }

  public CaseDataDto quarantine(QuarantineType quarantine) {
    this.quarantine = quarantine;
    return this;
  }

   /**
   * Get quarantine
   * @return quarantine
  **/
  @Schema(description = "")
  public QuarantineType getQuarantine() {
    return quarantine;
  }

  public void setQuarantine(QuarantineType quarantine) {
    this.quarantine = quarantine;
  }

  public CaseDataDto quarantineTypeDetails(String quarantineTypeDetails) {
    this.quarantineTypeDetails = quarantineTypeDetails;
    return this;
  }

   /**
   * Get quarantineTypeDetails
   * @return quarantineTypeDetails
  **/
  @Schema(description = "")
  public String getQuarantineTypeDetails() {
    return quarantineTypeDetails;
  }

  public void setQuarantineTypeDetails(String quarantineTypeDetails) {
    this.quarantineTypeDetails = quarantineTypeDetails;
  }

  public CaseDataDto quarantineFrom(OffsetDateTime quarantineFrom) {
    this.quarantineFrom = quarantineFrom;
    return this;
  }

   /**
   * Get quarantineFrom
   * @return quarantineFrom
  **/
  @Schema(description = "")
  public OffsetDateTime getQuarantineFrom() {
    return quarantineFrom;
  }

  public void setQuarantineFrom(OffsetDateTime quarantineFrom) {
    this.quarantineFrom = quarantineFrom;
  }

  public CaseDataDto quarantineTo(OffsetDateTime quarantineTo) {
    this.quarantineTo = quarantineTo;
    return this;
  }

   /**
   * Get quarantineTo
   * @return quarantineTo
  **/
  @Schema(description = "")
  public OffsetDateTime getQuarantineTo() {
    return quarantineTo;
  }

  public void setQuarantineTo(OffsetDateTime quarantineTo) {
    this.quarantineTo = quarantineTo;
  }

  public CaseDataDto quarantineHelpNeeded(String quarantineHelpNeeded) {
    this.quarantineHelpNeeded = quarantineHelpNeeded;
    return this;
  }

   /**
   * Get quarantineHelpNeeded
   * @return quarantineHelpNeeded
  **/
  @Schema(description = "")
  public String getQuarantineHelpNeeded() {
    return quarantineHelpNeeded;
  }

  public void setQuarantineHelpNeeded(String quarantineHelpNeeded) {
    this.quarantineHelpNeeded = quarantineHelpNeeded;
  }

  public CaseDataDto quarantineOrderedVerbally(Boolean quarantineOrderedVerbally) {
    this.quarantineOrderedVerbally = quarantineOrderedVerbally;
    return this;
  }

   /**
   * Get quarantineOrderedVerbally
   * @return quarantineOrderedVerbally
  **/
  @Schema(description = "")
  public Boolean isQuarantineOrderedVerbally() {
    return quarantineOrderedVerbally;
  }

  public void setQuarantineOrderedVerbally(Boolean quarantineOrderedVerbally) {
    this.quarantineOrderedVerbally = quarantineOrderedVerbally;
  }

  public CaseDataDto quarantineOrderedOfficialDocument(Boolean quarantineOrderedOfficialDocument) {
    this.quarantineOrderedOfficialDocument = quarantineOrderedOfficialDocument;
    return this;
  }

   /**
   * Get quarantineOrderedOfficialDocument
   * @return quarantineOrderedOfficialDocument
  **/
  @Schema(description = "")
  public Boolean isQuarantineOrderedOfficialDocument() {
    return quarantineOrderedOfficialDocument;
  }

  public void setQuarantineOrderedOfficialDocument(Boolean quarantineOrderedOfficialDocument) {
    this.quarantineOrderedOfficialDocument = quarantineOrderedOfficialDocument;
  }

  public CaseDataDto quarantineOrderedVerballyDate(OffsetDateTime quarantineOrderedVerballyDate) {
    this.quarantineOrderedVerballyDate = quarantineOrderedVerballyDate;
    return this;
  }

   /**
   * Get quarantineOrderedVerballyDate
   * @return quarantineOrderedVerballyDate
  **/
  @Schema(description = "")
  public OffsetDateTime getQuarantineOrderedVerballyDate() {
    return quarantineOrderedVerballyDate;
  }

  public void setQuarantineOrderedVerballyDate(OffsetDateTime quarantineOrderedVerballyDate) {
    this.quarantineOrderedVerballyDate = quarantineOrderedVerballyDate;
  }

  public CaseDataDto quarantineOrderedOfficialDocumentDate(OffsetDateTime quarantineOrderedOfficialDocumentDate) {
    this.quarantineOrderedOfficialDocumentDate = quarantineOrderedOfficialDocumentDate;
    return this;
  }

   /**
   * Get quarantineOrderedOfficialDocumentDate
   * @return quarantineOrderedOfficialDocumentDate
  **/
  @Schema(description = "")
  public OffsetDateTime getQuarantineOrderedOfficialDocumentDate() {
    return quarantineOrderedOfficialDocumentDate;
  }

  public void setQuarantineOrderedOfficialDocumentDate(OffsetDateTime quarantineOrderedOfficialDocumentDate) {
    this.quarantineOrderedOfficialDocumentDate = quarantineOrderedOfficialDocumentDate;
  }

  public CaseDataDto quarantineHomePossible(YesNoUnknown quarantineHomePossible) {
    this.quarantineHomePossible = quarantineHomePossible;
    return this;
  }

   /**
   * Get quarantineHomePossible
   * @return quarantineHomePossible
  **/
  @Schema(description = "")
  public YesNoUnknown getQuarantineHomePossible() {
    return quarantineHomePossible;
  }

  public void setQuarantineHomePossible(YesNoUnknown quarantineHomePossible) {
    this.quarantineHomePossible = quarantineHomePossible;
  }

  public CaseDataDto quarantineHomePossibleComment(String quarantineHomePossibleComment) {
    this.quarantineHomePossibleComment = quarantineHomePossibleComment;
    return this;
  }

   /**
   * Get quarantineHomePossibleComment
   * @return quarantineHomePossibleComment
  **/
  @Schema(description = "")
  public String getQuarantineHomePossibleComment() {
    return quarantineHomePossibleComment;
  }

  public void setQuarantineHomePossibleComment(String quarantineHomePossibleComment) {
    this.quarantineHomePossibleComment = quarantineHomePossibleComment;
  }

  public CaseDataDto quarantineHomeSupplyEnsured(YesNoUnknown quarantineHomeSupplyEnsured) {
    this.quarantineHomeSupplyEnsured = quarantineHomeSupplyEnsured;
    return this;
  }

   /**
   * Get quarantineHomeSupplyEnsured
   * @return quarantineHomeSupplyEnsured
  **/
  @Schema(description = "")
  public YesNoUnknown getQuarantineHomeSupplyEnsured() {
    return quarantineHomeSupplyEnsured;
  }

  public void setQuarantineHomeSupplyEnsured(YesNoUnknown quarantineHomeSupplyEnsured) {
    this.quarantineHomeSupplyEnsured = quarantineHomeSupplyEnsured;
  }

  public CaseDataDto quarantineHomeSupplyEnsuredComment(String quarantineHomeSupplyEnsuredComment) {
    this.quarantineHomeSupplyEnsuredComment = quarantineHomeSupplyEnsuredComment;
    return this;
  }

   /**
   * Get quarantineHomeSupplyEnsuredComment
   * @return quarantineHomeSupplyEnsuredComment
  **/
  @Schema(description = "")
  public String getQuarantineHomeSupplyEnsuredComment() {
    return quarantineHomeSupplyEnsuredComment;
  }

  public void setQuarantineHomeSupplyEnsuredComment(String quarantineHomeSupplyEnsuredComment) {
    this.quarantineHomeSupplyEnsuredComment = quarantineHomeSupplyEnsuredComment;
  }

  public CaseDataDto quarantineExtended(Boolean quarantineExtended) {
    this.quarantineExtended = quarantineExtended;
    return this;
  }

   /**
   * Get quarantineExtended
   * @return quarantineExtended
  **/
  @Schema(description = "")
  public Boolean isQuarantineExtended() {
    return quarantineExtended;
  }

  public void setQuarantineExtended(Boolean quarantineExtended) {
    this.quarantineExtended = quarantineExtended;
  }

  public CaseDataDto quarantineReduced(Boolean quarantineReduced) {
    this.quarantineReduced = quarantineReduced;
    return this;
  }

   /**
   * Get quarantineReduced
   * @return quarantineReduced
  **/
  @Schema(description = "")
  public Boolean isQuarantineReduced() {
    return quarantineReduced;
  }

  public void setQuarantineReduced(Boolean quarantineReduced) {
    this.quarantineReduced = quarantineReduced;
  }

  public CaseDataDto quarantineOfficialOrderSent(Boolean quarantineOfficialOrderSent) {
    this.quarantineOfficialOrderSent = quarantineOfficialOrderSent;
    return this;
  }

   /**
   * Get quarantineOfficialOrderSent
   * @return quarantineOfficialOrderSent
  **/
  @Schema(description = "")
  public Boolean isQuarantineOfficialOrderSent() {
    return quarantineOfficialOrderSent;
  }

  public void setQuarantineOfficialOrderSent(Boolean quarantineOfficialOrderSent) {
    this.quarantineOfficialOrderSent = quarantineOfficialOrderSent;
  }

  public CaseDataDto quarantineOfficialOrderSentDate(OffsetDateTime quarantineOfficialOrderSentDate) {
    this.quarantineOfficialOrderSentDate = quarantineOfficialOrderSentDate;
    return this;
  }

   /**
   * Get quarantineOfficialOrderSentDate
   * @return quarantineOfficialOrderSentDate
  **/
  @Schema(description = "")
  public OffsetDateTime getQuarantineOfficialOrderSentDate() {
    return quarantineOfficialOrderSentDate;
  }

  public void setQuarantineOfficialOrderSentDate(OffsetDateTime quarantineOfficialOrderSentDate) {
    this.quarantineOfficialOrderSentDate = quarantineOfficialOrderSentDate;
  }

  public CaseDataDto reportingType(ReportingType reportingType) {
    this.reportingType = reportingType;
    return this;
  }

   /**
   * Get reportingType
   * @return reportingType
  **/
  @Schema(description = "")
  public ReportingType getReportingType() {
    return reportingType;
  }

  public void setReportingType(ReportingType reportingType) {
    this.reportingType = reportingType;
  }

  public CaseDataDto postpartum(YesNoUnknown postpartum) {
    this.postpartum = postpartum;
    return this;
  }

   /**
   * Get postpartum
   * @return postpartum
  **/
  @Schema(description = "")
  public YesNoUnknown getPostpartum() {
    return postpartum;
  }

  public void setPostpartum(YesNoUnknown postpartum) {
    this.postpartum = postpartum;
  }

  public CaseDataDto trimester(Trimester trimester) {
    this.trimester = trimester;
    return this;
  }

   /**
   * Get trimester
   * @return trimester
  **/
  @Schema(description = "")
  public Trimester getTrimester() {
    return trimester;
  }

  public void setTrimester(Trimester trimester) {
    this.trimester = trimester;
  }

  public CaseDataDto followUpStatus(FollowUpStatus followUpStatus) {
    this.followUpStatus = followUpStatus;
    return this;
  }

   /**
   * Get followUpStatus
   * @return followUpStatus
  **/
  @Schema(description = "")
  public FollowUpStatus getFollowUpStatus() {
    return followUpStatus;
  }

  public void setFollowUpStatus(FollowUpStatus followUpStatus) {
    this.followUpStatus = followUpStatus;
  }

  public CaseDataDto followUpComment(String followUpComment) {
    this.followUpComment = followUpComment;
    return this;
  }

   /**
   * Get followUpComment
   * @return followUpComment
  **/
  @Schema(description = "")
  public String getFollowUpComment() {
    return followUpComment;
  }

  public void setFollowUpComment(String followUpComment) {
    this.followUpComment = followUpComment;
  }

  public CaseDataDto followUpUntil(OffsetDateTime followUpUntil) {
    this.followUpUntil = followUpUntil;
    return this;
  }

   /**
   * Get followUpUntil
   * @return followUpUntil
  **/
  @Schema(description = "")
  public OffsetDateTime getFollowUpUntil() {
    return followUpUntil;
  }

  public void setFollowUpUntil(OffsetDateTime followUpUntil) {
    this.followUpUntil = followUpUntil;
  }

  public CaseDataDto overwriteFollowUpUntil(Boolean overwriteFollowUpUntil) {
    this.overwriteFollowUpUntil = overwriteFollowUpUntil;
    return this;
  }

   /**
   * Get overwriteFollowUpUntil
   * @return overwriteFollowUpUntil
  **/
  @Schema(description = "")
  public Boolean isOverwriteFollowUpUntil() {
    return overwriteFollowUpUntil;
  }

  public void setOverwriteFollowUpUntil(Boolean overwriteFollowUpUntil) {
    this.overwriteFollowUpUntil = overwriteFollowUpUntil;
  }

  public CaseDataDto sormasToSormasOriginInfo(SormasToSormasOriginInfoDto sormasToSormasOriginInfo) {
    this.sormasToSormasOriginInfo = sormasToSormasOriginInfo;
    return this;
  }

   /**
   * Get sormasToSormasOriginInfo
   * @return sormasToSormasOriginInfo
  **/
  @Schema(description = "")
  public SormasToSormasOriginInfoDto getSormasToSormasOriginInfo() {
    return sormasToSormasOriginInfo;
  }

  public void setSormasToSormasOriginInfo(SormasToSormasOriginInfoDto sormasToSormasOriginInfo) {
    this.sormasToSormasOriginInfo = sormasToSormasOriginInfo;
  }

  public CaseDataDto ownershipHandedOver(Boolean ownershipHandedOver) {
    this.ownershipHandedOver = ownershipHandedOver;
    return this;
  }

   /**
   * Get ownershipHandedOver
   * @return ownershipHandedOver
  **/
  @Schema(description = "")
  public Boolean isOwnershipHandedOver() {
    return ownershipHandedOver;
  }

  public void setOwnershipHandedOver(Boolean ownershipHandedOver) {
    this.ownershipHandedOver = ownershipHandedOver;
  }

  public CaseDataDto caseIdIsm(Integer caseIdIsm) {
    this.caseIdIsm = caseIdIsm;
    return this;
  }

   /**
   * Get caseIdIsm
   * @return caseIdIsm
  **/
  @Schema(description = "")
  public Integer getCaseIdIsm() {
    return caseIdIsm;
  }

  public void setCaseIdIsm(Integer caseIdIsm) {
    this.caseIdIsm = caseIdIsm;
  }

  public CaseDataDto covidTestReason(CovidTestReason covidTestReason) {
    this.covidTestReason = covidTestReason;
    return this;
  }

   /**
   * Get covidTestReason
   * @return covidTestReason
  **/
  @Schema(description = "")
  public CovidTestReason getCovidTestReason() {
    return covidTestReason;
  }

  public void setCovidTestReason(CovidTestReason covidTestReason) {
    this.covidTestReason = covidTestReason;
  }

  public CaseDataDto covidTestReasonDetails(String covidTestReasonDetails) {
    this.covidTestReasonDetails = covidTestReasonDetails;
    return this;
  }

   /**
   * Get covidTestReasonDetails
   * @return covidTestReasonDetails
  **/
  @Schema(description = "")
  public String getCovidTestReasonDetails() {
    return covidTestReasonDetails;
  }

  public void setCovidTestReasonDetails(String covidTestReasonDetails) {
    this.covidTestReasonDetails = covidTestReasonDetails;
  }

  public CaseDataDto contactTracingFirstContactType(ContactTracingContactType contactTracingFirstContactType) {
    this.contactTracingFirstContactType = contactTracingFirstContactType;
    return this;
  }

   /**
   * Get contactTracingFirstContactType
   * @return contactTracingFirstContactType
  **/
  @Schema(description = "")
  public ContactTracingContactType getContactTracingFirstContactType() {
    return contactTracingFirstContactType;
  }

  public void setContactTracingFirstContactType(ContactTracingContactType contactTracingFirstContactType) {
    this.contactTracingFirstContactType = contactTracingFirstContactType;
  }

  public CaseDataDto contactTracingFirstContactDate(OffsetDateTime contactTracingFirstContactDate) {
    this.contactTracingFirstContactDate = contactTracingFirstContactDate;
    return this;
  }

   /**
   * Get contactTracingFirstContactDate
   * @return contactTracingFirstContactDate
  **/
  @Schema(description = "")
  public OffsetDateTime getContactTracingFirstContactDate() {
    return contactTracingFirstContactDate;
  }

  public void setContactTracingFirstContactDate(OffsetDateTime contactTracingFirstContactDate) {
    this.contactTracingFirstContactDate = contactTracingFirstContactDate;
  }

  public CaseDataDto wasInQuarantineBeforeIsolation(YesNoUnknown wasInQuarantineBeforeIsolation) {
    this.wasInQuarantineBeforeIsolation = wasInQuarantineBeforeIsolation;
    return this;
  }

   /**
   * Get wasInQuarantineBeforeIsolation
   * @return wasInQuarantineBeforeIsolation
  **/
  @Schema(description = "")
  public YesNoUnknown getWasInQuarantineBeforeIsolation() {
    return wasInQuarantineBeforeIsolation;
  }

  public void setWasInQuarantineBeforeIsolation(YesNoUnknown wasInQuarantineBeforeIsolation) {
    this.wasInQuarantineBeforeIsolation = wasInQuarantineBeforeIsolation;
  }

  public CaseDataDto quarantineReasonBeforeIsolation(QuarantineReason quarantineReasonBeforeIsolation) {
    this.quarantineReasonBeforeIsolation = quarantineReasonBeforeIsolation;
    return this;
  }

   /**
   * Get quarantineReasonBeforeIsolation
   * @return quarantineReasonBeforeIsolation
  **/
  @Schema(description = "")
  public QuarantineReason getQuarantineReasonBeforeIsolation() {
    return quarantineReasonBeforeIsolation;
  }

  public void setQuarantineReasonBeforeIsolation(QuarantineReason quarantineReasonBeforeIsolation) {
    this.quarantineReasonBeforeIsolation = quarantineReasonBeforeIsolation;
  }

  public CaseDataDto quarantineReasonBeforeIsolationDetails(String quarantineReasonBeforeIsolationDetails) {
    this.quarantineReasonBeforeIsolationDetails = quarantineReasonBeforeIsolationDetails;
    return this;
  }

   /**
   * Get quarantineReasonBeforeIsolationDetails
   * @return quarantineReasonBeforeIsolationDetails
  **/
  @Schema(description = "")
  public String getQuarantineReasonBeforeIsolationDetails() {
    return quarantineReasonBeforeIsolationDetails;
  }

  public void setQuarantineReasonBeforeIsolationDetails(String quarantineReasonBeforeIsolationDetails) {
    this.quarantineReasonBeforeIsolationDetails = quarantineReasonBeforeIsolationDetails;
  }

  public CaseDataDto endOfIsolationReason(EndOfIsolationReason endOfIsolationReason) {
    this.endOfIsolationReason = endOfIsolationReason;
    return this;
  }

   /**
   * Get endOfIsolationReason
   * @return endOfIsolationReason
  **/
  @Schema(description = "")
  public EndOfIsolationReason getEndOfIsolationReason() {
    return endOfIsolationReason;
  }

  public void setEndOfIsolationReason(EndOfIsolationReason endOfIsolationReason) {
    this.endOfIsolationReason = endOfIsolationReason;
  }

  public CaseDataDto endOfIsolationReasonDetails(String endOfIsolationReasonDetails) {
    this.endOfIsolationReasonDetails = endOfIsolationReasonDetails;
    return this;
  }

   /**
   * Get endOfIsolationReasonDetails
   * @return endOfIsolationReasonDetails
  **/
  @Schema(description = "")
  public String getEndOfIsolationReasonDetails() {
    return endOfIsolationReasonDetails;
  }

  public void setEndOfIsolationReasonDetails(String endOfIsolationReasonDetails) {
    this.endOfIsolationReasonDetails = endOfIsolationReasonDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseDataDto caseDataDto = (CaseDataDto) o;
    return Objects.equals(this.creationDate, caseDataDto.creationDate) &&
        Objects.equals(this.changeDate, caseDataDto.changeDate) &&
        Objects.equals(this.uuid, caseDataDto.uuid) &&
        Objects.equals(this.pseudonymized, caseDataDto.pseudonymized) &&
        Objects.equals(this.disease, caseDataDto.disease) &&
        Objects.equals(this.diseaseDetails, caseDataDto.diseaseDetails) &&
        Objects.equals(this.plagueType, caseDataDto.plagueType) &&
        Objects.equals(this.dengueFeverType, caseDataDto.dengueFeverType) &&
        Objects.equals(this.rabiesType, caseDataDto.rabiesType) &&
        Objects.equals(this.person, caseDataDto.person) &&
        Objects.equals(this.epidNumber, caseDataDto.epidNumber) &&
        Objects.equals(this.reportDate, caseDataDto.reportDate) &&
        Objects.equals(this.reportingUser, caseDataDto.reportingUser) &&
        Objects.equals(this.regionLevelDate, caseDataDto.regionLevelDate) &&
        Objects.equals(this.nationalLevelDate, caseDataDto.nationalLevelDate) &&
        Objects.equals(this.districtLevelDate, caseDataDto.districtLevelDate) &&
        Objects.equals(this.caseClassification, caseDataDto.caseClassification) &&
        Objects.equals(this.classificationUser, caseDataDto.classificationUser) &&
        Objects.equals(this.classificationDate, caseDataDto.classificationDate) &&
        Objects.equals(this.classificationComment, caseDataDto.classificationComment) &&
        Objects.equals(this.clinicalConfirmation, caseDataDto.clinicalConfirmation) &&
        Objects.equals(this.epidemiologicalConfirmation, caseDataDto.epidemiologicalConfirmation) &&
        Objects.equals(this.laboratoryDiagnosticConfirmation, caseDataDto.laboratoryDiagnosticConfirmation) &&
        Objects.equals(this.investigationStatus, caseDataDto.investigationStatus) &&
        Objects.equals(this.investigatedDate, caseDataDto.investigatedDate) &&
        Objects.equals(this.outcome, caseDataDto.outcome) &&
        Objects.equals(this.outcomeDate, caseDataDto.outcomeDate) &&
        Objects.equals(this.sequelae, caseDataDto.sequelae) &&
        Objects.equals(this.sequelaeDetails, caseDataDto.sequelaeDetails) &&
        Objects.equals(this.region, caseDataDto.region) &&
        Objects.equals(this.district, caseDataDto.district) &&
        Objects.equals(this.community, caseDataDto.community) &&
        Objects.equals(this.facilityType, caseDataDto.facilityType) &&
        Objects.equals(this.healthFacility, caseDataDto.healthFacility) &&
        Objects.equals(this.healthFacilityDetails, caseDataDto.healthFacilityDetails) &&
        Objects.equals(this.pregnant, caseDataDto.pregnant) &&
        Objects.equals(this.vaccination, caseDataDto.vaccination) &&
        Objects.equals(this.vaccinationDoses, caseDataDto.vaccinationDoses) &&
        Objects.equals(this.vaccinationDate, caseDataDto.vaccinationDate) &&
        Objects.equals(this.vaccinationInfoSource, caseDataDto.vaccinationInfoSource) &&
        Objects.equals(this.vaccine, caseDataDto.vaccine) &&
        Objects.equals(this.smallpoxVaccinationScar, caseDataDto.smallpoxVaccinationScar) &&
        Objects.equals(this.smallpoxVaccinationReceived, caseDataDto.smallpoxVaccinationReceived) &&
        Objects.equals(this.surveillanceOfficer, caseDataDto.surveillanceOfficer) &&
        Objects.equals(this.clinicianName, caseDataDto.clinicianName) &&
        Objects.equals(this.clinicianPhone, caseDataDto.clinicianPhone) &&
        Objects.equals(this.clinicianEmail, caseDataDto.clinicianEmail) &&
        Objects.equals(this.notifyingClinic, caseDataDto.notifyingClinic) &&
        Objects.equals(this.notifyingClinicDetails, caseDataDto.notifyingClinicDetails) &&
        Objects.equals(this.caseOfficer, caseDataDto.caseOfficer) &&
        Objects.equals(this.reportLat, caseDataDto.reportLat) &&
        Objects.equals(this.reportLon, caseDataDto.reportLon) &&
        Objects.equals(this.reportLatLonAccuracy, caseDataDto.reportLatLonAccuracy) &&
        Objects.equals(this.hospitalization, caseDataDto.hospitalization) &&
        Objects.equals(this.symptoms, caseDataDto.symptoms) &&
        Objects.equals(this.epiData, caseDataDto.epiData) &&
        Objects.equals(this.therapy, caseDataDto.therapy) &&
        Objects.equals(this.clinicalCourse, caseDataDto.clinicalCourse) &&
        Objects.equals(this.maternalHistory, caseDataDto.maternalHistory) &&
        Objects.equals(this.creationVersion, caseDataDto.creationVersion) &&
        Objects.equals(this.portHealthInfo, caseDataDto.portHealthInfo) &&
        Objects.equals(this.caseOrigin, caseDataDto.caseOrigin) &&
        Objects.equals(this.pointOfEntry, caseDataDto.pointOfEntry) &&
        Objects.equals(this.pointOfEntryDetails, caseDataDto.pointOfEntryDetails) &&
        Objects.equals(this.additionalDetails, caseDataDto.additionalDetails) &&
        Objects.equals(this.externalID, caseDataDto.externalID) &&
        Objects.equals(this.sharedToCountry, caseDataDto.sharedToCountry) &&
        Objects.equals(this.quarantine, caseDataDto.quarantine) &&
        Objects.equals(this.quarantineTypeDetails, caseDataDto.quarantineTypeDetails) &&
        Objects.equals(this.quarantineFrom, caseDataDto.quarantineFrom) &&
        Objects.equals(this.quarantineTo, caseDataDto.quarantineTo) &&
        Objects.equals(this.quarantineHelpNeeded, caseDataDto.quarantineHelpNeeded) &&
        Objects.equals(this.quarantineOrderedVerbally, caseDataDto.quarantineOrderedVerbally) &&
        Objects.equals(this.quarantineOrderedOfficialDocument, caseDataDto.quarantineOrderedOfficialDocument) &&
        Objects.equals(this.quarantineOrderedVerballyDate, caseDataDto.quarantineOrderedVerballyDate) &&
        Objects.equals(this.quarantineOrderedOfficialDocumentDate, caseDataDto.quarantineOrderedOfficialDocumentDate) &&
        Objects.equals(this.quarantineHomePossible, caseDataDto.quarantineHomePossible) &&
        Objects.equals(this.quarantineHomePossibleComment, caseDataDto.quarantineHomePossibleComment) &&
        Objects.equals(this.quarantineHomeSupplyEnsured, caseDataDto.quarantineHomeSupplyEnsured) &&
        Objects.equals(this.quarantineHomeSupplyEnsuredComment, caseDataDto.quarantineHomeSupplyEnsuredComment) &&
        Objects.equals(this.quarantineExtended, caseDataDto.quarantineExtended) &&
        Objects.equals(this.quarantineReduced, caseDataDto.quarantineReduced) &&
        Objects.equals(this.quarantineOfficialOrderSent, caseDataDto.quarantineOfficialOrderSent) &&
        Objects.equals(this.quarantineOfficialOrderSentDate, caseDataDto.quarantineOfficialOrderSentDate) &&
        Objects.equals(this.reportingType, caseDataDto.reportingType) &&
        Objects.equals(this.postpartum, caseDataDto.postpartum) &&
        Objects.equals(this.trimester, caseDataDto.trimester) &&
        Objects.equals(this.followUpStatus, caseDataDto.followUpStatus) &&
        Objects.equals(this.followUpComment, caseDataDto.followUpComment) &&
        Objects.equals(this.followUpUntil, caseDataDto.followUpUntil) &&
        Objects.equals(this.overwriteFollowUpUntil, caseDataDto.overwriteFollowUpUntil) &&
        Objects.equals(this.sormasToSormasOriginInfo, caseDataDto.sormasToSormasOriginInfo) &&
        Objects.equals(this.ownershipHandedOver, caseDataDto.ownershipHandedOver) &&
        Objects.equals(this.caseIdIsm, caseDataDto.caseIdIsm) &&
        Objects.equals(this.covidTestReason, caseDataDto.covidTestReason) &&
        Objects.equals(this.covidTestReasonDetails, caseDataDto.covidTestReasonDetails) &&
        Objects.equals(this.contactTracingFirstContactType, caseDataDto.contactTracingFirstContactType) &&
        Objects.equals(this.contactTracingFirstContactDate, caseDataDto.contactTracingFirstContactDate) &&
        Objects.equals(this.wasInQuarantineBeforeIsolation, caseDataDto.wasInQuarantineBeforeIsolation) &&
        Objects.equals(this.quarantineReasonBeforeIsolation, caseDataDto.quarantineReasonBeforeIsolation) &&
        Objects.equals(this.quarantineReasonBeforeIsolationDetails, caseDataDto.quarantineReasonBeforeIsolationDetails) &&
        Objects.equals(this.endOfIsolationReason, caseDataDto.endOfIsolationReason) &&
        Objects.equals(this.endOfIsolationReasonDetails, caseDataDto.endOfIsolationReasonDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDate, changeDate, uuid, pseudonymized, disease, diseaseDetails, plagueType, dengueFeverType, rabiesType, person, epidNumber, reportDate, reportingUser, regionLevelDate, nationalLevelDate, districtLevelDate, caseClassification, classificationUser, classificationDate, classificationComment, clinicalConfirmation, epidemiologicalConfirmation, laboratoryDiagnosticConfirmation, investigationStatus, investigatedDate, outcome, outcomeDate, sequelae, sequelaeDetails, region, district, community, facilityType, healthFacility, healthFacilityDetails, pregnant, vaccination, vaccinationDoses, vaccinationDate, vaccinationInfoSource, vaccine, smallpoxVaccinationScar, smallpoxVaccinationReceived, surveillanceOfficer, clinicianName, clinicianPhone, clinicianEmail, notifyingClinic, notifyingClinicDetails, caseOfficer, reportLat, reportLon, reportLatLonAccuracy, hospitalization, symptoms, epiData, therapy, clinicalCourse, maternalHistory, creationVersion, portHealthInfo, caseOrigin, pointOfEntry, pointOfEntryDetails, additionalDetails, externalID, sharedToCountry, quarantine, quarantineTypeDetails, quarantineFrom, quarantineTo, quarantineHelpNeeded, quarantineOrderedVerbally, quarantineOrderedOfficialDocument, quarantineOrderedVerballyDate, quarantineOrderedOfficialDocumentDate, quarantineHomePossible, quarantineHomePossibleComment, quarantineHomeSupplyEnsured, quarantineHomeSupplyEnsuredComment, quarantineExtended, quarantineReduced, quarantineOfficialOrderSent, quarantineOfficialOrderSentDate, reportingType, postpartum, trimester, followUpStatus, followUpComment, followUpUntil, overwriteFollowUpUntil, sormasToSormasOriginInfo, ownershipHandedOver, caseIdIsm, covidTestReason, covidTestReasonDetails, contactTracingFirstContactType, contactTracingFirstContactDate, wasInQuarantineBeforeIsolation, quarantineReasonBeforeIsolation, quarantineReasonBeforeIsolationDetails, endOfIsolationReason, endOfIsolationReasonDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseDataDto {\n");
    
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    changeDate: ").append(toIndentedString(changeDate)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    pseudonymized: ").append(toIndentedString(pseudonymized)).append("\n");
    sb.append("    disease: ").append(toIndentedString(disease)).append("\n");
    sb.append("    diseaseDetails: ").append(toIndentedString(diseaseDetails)).append("\n");
    sb.append("    plagueType: ").append(toIndentedString(plagueType)).append("\n");
    sb.append("    dengueFeverType: ").append(toIndentedString(dengueFeverType)).append("\n");
    sb.append("    rabiesType: ").append(toIndentedString(rabiesType)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    epidNumber: ").append(toIndentedString(epidNumber)).append("\n");
    sb.append("    reportDate: ").append(toIndentedString(reportDate)).append("\n");
    sb.append("    reportingUser: ").append(toIndentedString(reportingUser)).append("\n");
    sb.append("    regionLevelDate: ").append(toIndentedString(regionLevelDate)).append("\n");
    sb.append("    nationalLevelDate: ").append(toIndentedString(nationalLevelDate)).append("\n");
    sb.append("    districtLevelDate: ").append(toIndentedString(districtLevelDate)).append("\n");
    sb.append("    caseClassification: ").append(toIndentedString(caseClassification)).append("\n");
    sb.append("    classificationUser: ").append(toIndentedString(classificationUser)).append("\n");
    sb.append("    classificationDate: ").append(toIndentedString(classificationDate)).append("\n");
    sb.append("    classificationComment: ").append(toIndentedString(classificationComment)).append("\n");
    sb.append("    clinicalConfirmation: ").append(toIndentedString(clinicalConfirmation)).append("\n");
    sb.append("    epidemiologicalConfirmation: ").append(toIndentedString(epidemiologicalConfirmation)).append("\n");
    sb.append("    laboratoryDiagnosticConfirmation: ").append(toIndentedString(laboratoryDiagnosticConfirmation)).append("\n");
    sb.append("    investigationStatus: ").append(toIndentedString(investigationStatus)).append("\n");
    sb.append("    investigatedDate: ").append(toIndentedString(investigatedDate)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    outcomeDate: ").append(toIndentedString(outcomeDate)).append("\n");
    sb.append("    sequelae: ").append(toIndentedString(sequelae)).append("\n");
    sb.append("    sequelaeDetails: ").append(toIndentedString(sequelaeDetails)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    community: ").append(toIndentedString(community)).append("\n");
    sb.append("    facilityType: ").append(toIndentedString(facilityType)).append("\n");
    sb.append("    healthFacility: ").append(toIndentedString(healthFacility)).append("\n");
    sb.append("    healthFacilityDetails: ").append(toIndentedString(healthFacilityDetails)).append("\n");
    sb.append("    pregnant: ").append(toIndentedString(pregnant)).append("\n");
    sb.append("    vaccination: ").append(toIndentedString(vaccination)).append("\n");
    sb.append("    vaccinationDoses: ").append(toIndentedString(vaccinationDoses)).append("\n");
    sb.append("    vaccinationDate: ").append(toIndentedString(vaccinationDate)).append("\n");
    sb.append("    vaccinationInfoSource: ").append(toIndentedString(vaccinationInfoSource)).append("\n");
    sb.append("    vaccine: ").append(toIndentedString(vaccine)).append("\n");
    sb.append("    smallpoxVaccinationScar: ").append(toIndentedString(smallpoxVaccinationScar)).append("\n");
    sb.append("    smallpoxVaccinationReceived: ").append(toIndentedString(smallpoxVaccinationReceived)).append("\n");
    sb.append("    surveillanceOfficer: ").append(toIndentedString(surveillanceOfficer)).append("\n");
    sb.append("    clinicianName: ").append(toIndentedString(clinicianName)).append("\n");
    sb.append("    clinicianPhone: ").append(toIndentedString(clinicianPhone)).append("\n");
    sb.append("    clinicianEmail: ").append(toIndentedString(clinicianEmail)).append("\n");
    sb.append("    notifyingClinic: ").append(toIndentedString(notifyingClinic)).append("\n");
    sb.append("    notifyingClinicDetails: ").append(toIndentedString(notifyingClinicDetails)).append("\n");
    sb.append("    caseOfficer: ").append(toIndentedString(caseOfficer)).append("\n");
    sb.append("    reportLat: ").append(toIndentedString(reportLat)).append("\n");
    sb.append("    reportLon: ").append(toIndentedString(reportLon)).append("\n");
    sb.append("    reportLatLonAccuracy: ").append(toIndentedString(reportLatLonAccuracy)).append("\n");
    sb.append("    hospitalization: ").append(toIndentedString(hospitalization)).append("\n");
    sb.append("    symptoms: ").append(toIndentedString(symptoms)).append("\n");
    sb.append("    epiData: ").append(toIndentedString(epiData)).append("\n");
    sb.append("    therapy: ").append(toIndentedString(therapy)).append("\n");
    sb.append("    clinicalCourse: ").append(toIndentedString(clinicalCourse)).append("\n");
    sb.append("    maternalHistory: ").append(toIndentedString(maternalHistory)).append("\n");
    sb.append("    creationVersion: ").append(toIndentedString(creationVersion)).append("\n");
    sb.append("    portHealthInfo: ").append(toIndentedString(portHealthInfo)).append("\n");
    sb.append("    caseOrigin: ").append(toIndentedString(caseOrigin)).append("\n");
    sb.append("    pointOfEntry: ").append(toIndentedString(pointOfEntry)).append("\n");
    sb.append("    pointOfEntryDetails: ").append(toIndentedString(pointOfEntryDetails)).append("\n");
    sb.append("    additionalDetails: ").append(toIndentedString(additionalDetails)).append("\n");
    sb.append("    externalID: ").append(toIndentedString(externalID)).append("\n");
    sb.append("    sharedToCountry: ").append(toIndentedString(sharedToCountry)).append("\n");
    sb.append("    quarantine: ").append(toIndentedString(quarantine)).append("\n");
    sb.append("    quarantineTypeDetails: ").append(toIndentedString(quarantineTypeDetails)).append("\n");
    sb.append("    quarantineFrom: ").append(toIndentedString(quarantineFrom)).append("\n");
    sb.append("    quarantineTo: ").append(toIndentedString(quarantineTo)).append("\n");
    sb.append("    quarantineHelpNeeded: ").append(toIndentedString(quarantineHelpNeeded)).append("\n");
    sb.append("    quarantineOrderedVerbally: ").append(toIndentedString(quarantineOrderedVerbally)).append("\n");
    sb.append("    quarantineOrderedOfficialDocument: ").append(toIndentedString(quarantineOrderedOfficialDocument)).append("\n");
    sb.append("    quarantineOrderedVerballyDate: ").append(toIndentedString(quarantineOrderedVerballyDate)).append("\n");
    sb.append("    quarantineOrderedOfficialDocumentDate: ").append(toIndentedString(quarantineOrderedOfficialDocumentDate)).append("\n");
    sb.append("    quarantineHomePossible: ").append(toIndentedString(quarantineHomePossible)).append("\n");
    sb.append("    quarantineHomePossibleComment: ").append(toIndentedString(quarantineHomePossibleComment)).append("\n");
    sb.append("    quarantineHomeSupplyEnsured: ").append(toIndentedString(quarantineHomeSupplyEnsured)).append("\n");
    sb.append("    quarantineHomeSupplyEnsuredComment: ").append(toIndentedString(quarantineHomeSupplyEnsuredComment)).append("\n");
    sb.append("    quarantineExtended: ").append(toIndentedString(quarantineExtended)).append("\n");
    sb.append("    quarantineReduced: ").append(toIndentedString(quarantineReduced)).append("\n");
    sb.append("    quarantineOfficialOrderSent: ").append(toIndentedString(quarantineOfficialOrderSent)).append("\n");
    sb.append("    quarantineOfficialOrderSentDate: ").append(toIndentedString(quarantineOfficialOrderSentDate)).append("\n");
    sb.append("    reportingType: ").append(toIndentedString(reportingType)).append("\n");
    sb.append("    postpartum: ").append(toIndentedString(postpartum)).append("\n");
    sb.append("    trimester: ").append(toIndentedString(trimester)).append("\n");
    sb.append("    followUpStatus: ").append(toIndentedString(followUpStatus)).append("\n");
    sb.append("    followUpComment: ").append(toIndentedString(followUpComment)).append("\n");
    sb.append("    followUpUntil: ").append(toIndentedString(followUpUntil)).append("\n");
    sb.append("    overwriteFollowUpUntil: ").append(toIndentedString(overwriteFollowUpUntil)).append("\n");
    sb.append("    sormasToSormasOriginInfo: ").append(toIndentedString(sormasToSormasOriginInfo)).append("\n");
    sb.append("    ownershipHandedOver: ").append(toIndentedString(ownershipHandedOver)).append("\n");
    sb.append("    caseIdIsm: ").append(toIndentedString(caseIdIsm)).append("\n");
    sb.append("    covidTestReason: ").append(toIndentedString(covidTestReason)).append("\n");
    sb.append("    covidTestReasonDetails: ").append(toIndentedString(covidTestReasonDetails)).append("\n");
    sb.append("    contactTracingFirstContactType: ").append(toIndentedString(contactTracingFirstContactType)).append("\n");
    sb.append("    contactTracingFirstContactDate: ").append(toIndentedString(contactTracingFirstContactDate)).append("\n");
    sb.append("    wasInQuarantineBeforeIsolation: ").append(toIndentedString(wasInQuarantineBeforeIsolation)).append("\n");
    sb.append("    quarantineReasonBeforeIsolation: ").append(toIndentedString(quarantineReasonBeforeIsolation)).append("\n");
    sb.append("    quarantineReasonBeforeIsolationDetails: ").append(toIndentedString(quarantineReasonBeforeIsolationDetails)).append("\n");
    sb.append("    endOfIsolationReason: ").append(toIndentedString(endOfIsolationReason)).append("\n");
    sb.append("    endOfIsolationReasonDetails: ").append(toIndentedString(endOfIsolationReasonDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
