/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.52.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import de.quarano.sormas.client.model.ClassificationCaseCriteriaDto;
import de.quarano.sormas.client.model.PathogenTestType;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ClassificationPathogenTestCriteriaDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-15T22:47:05.366577+01:00[Europe/Berlin]")
public class ClassificationPathogenTestCriteriaDto extends ClassificationCaseCriteriaDto {
  @JsonProperty("testTypes")
  private List<PathogenTestType> testTypes = null;

  public ClassificationPathogenTestCriteriaDto testTypes(List<PathogenTestType> testTypes) {
    this.testTypes = testTypes;
    return this;
  }

  public ClassificationPathogenTestCriteriaDto addTestTypesItem(PathogenTestType testTypesItem) {
    if (this.testTypes == null) {
      this.testTypes = new ArrayList<>();
    }
    this.testTypes.add(testTypesItem);
    return this;
  }

   /**
   * Get testTypes
   * @return testTypes
  **/
  @Schema(description = "")
  public List<PathogenTestType> getTestTypes() {
    return testTypes;
  }

  public void setTestTypes(List<PathogenTestType> testTypes) {
    this.testTypes = testTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClassificationPathogenTestCriteriaDto classificationPathogenTestCriteriaDto = (ClassificationPathogenTestCriteriaDto) o;
    return Objects.equals(this.testTypes, classificationPathogenTestCriteriaDto.testTypes) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(testTypes, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClassificationPathogenTestCriteriaDto {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    testTypes: ").append(toIndentedString(testTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
