/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.44.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import de.quarano.sormas.client.model.ClinicalCourseReferenceDto;
import de.quarano.sormas.client.model.Disease;
import de.quarano.sormas.client.model.SymptomsDto;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
/**
 * ClinicalVisitDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-09T17:56:16.099120+02:00[Europe/Berlin]")
public class ClinicalVisitDto {
  @JsonProperty("creationDate")
  private OffsetDateTime creationDate = null;

  @JsonProperty("changeDate")
  private OffsetDateTime changeDate = null;

  @JsonProperty("uuid")
  private String uuid = null;

  @JsonProperty("clinicalCourse")
  private ClinicalCourseReferenceDto clinicalCourse = null;

  @JsonProperty("symptoms")
  private SymptomsDto symptoms = null;

  @JsonProperty("disease")
  private Disease disease = null;

  @JsonProperty("visitDateTime")
  private OffsetDateTime visitDateTime = null;

  @JsonProperty("visitRemarks")
  private String visitRemarks = null;

  @JsonProperty("visitingPerson")
  private String visitingPerson = null;

  public ClinicalVisitDto creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @Schema(description = "")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public ClinicalVisitDto changeDate(OffsetDateTime changeDate) {
    this.changeDate = changeDate;
    return this;
  }

   /**
   * Get changeDate
   * @return changeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getChangeDate() {
    return changeDate;
  }

  public void setChangeDate(OffsetDateTime changeDate) {
    this.changeDate = changeDate;
  }

  public ClinicalVisitDto uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @Schema(description = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public ClinicalVisitDto clinicalCourse(ClinicalCourseReferenceDto clinicalCourse) {
    this.clinicalCourse = clinicalCourse;
    return this;
  }

   /**
   * Get clinicalCourse
   * @return clinicalCourse
  **/
  @Schema(description = "")
  public ClinicalCourseReferenceDto getClinicalCourse() {
    return clinicalCourse;
  }

  public void setClinicalCourse(ClinicalCourseReferenceDto clinicalCourse) {
    this.clinicalCourse = clinicalCourse;
  }

  public ClinicalVisitDto symptoms(SymptomsDto symptoms) {
    this.symptoms = symptoms;
    return this;
  }

   /**
   * Get symptoms
   * @return symptoms
  **/
  @Schema(description = "")
  public SymptomsDto getSymptoms() {
    return symptoms;
  }

  public void setSymptoms(SymptomsDto symptoms) {
    this.symptoms = symptoms;
  }

  public ClinicalVisitDto disease(Disease disease) {
    this.disease = disease;
    return this;
  }

   /**
   * Get disease
   * @return disease
  **/
  @Schema(description = "")
  public Disease getDisease() {
    return disease;
  }

  public void setDisease(Disease disease) {
    this.disease = disease;
  }

  public ClinicalVisitDto visitDateTime(OffsetDateTime visitDateTime) {
    this.visitDateTime = visitDateTime;
    return this;
  }

   /**
   * Get visitDateTime
   * @return visitDateTime
  **/
  @Schema(description = "")
  public OffsetDateTime getVisitDateTime() {
    return visitDateTime;
  }

  public void setVisitDateTime(OffsetDateTime visitDateTime) {
    this.visitDateTime = visitDateTime;
  }

  public ClinicalVisitDto visitRemarks(String visitRemarks) {
    this.visitRemarks = visitRemarks;
    return this;
  }

   /**
   * Get visitRemarks
   * @return visitRemarks
  **/
  @Schema(description = "")
  public String getVisitRemarks() {
    return visitRemarks;
  }

  public void setVisitRemarks(String visitRemarks) {
    this.visitRemarks = visitRemarks;
  }

  public ClinicalVisitDto visitingPerson(String visitingPerson) {
    this.visitingPerson = visitingPerson;
    return this;
  }

   /**
   * Get visitingPerson
   * @return visitingPerson
  **/
  @Schema(description = "")
  public String getVisitingPerson() {
    return visitingPerson;
  }

  public void setVisitingPerson(String visitingPerson) {
    this.visitingPerson = visitingPerson;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClinicalVisitDto clinicalVisitDto = (ClinicalVisitDto) o;
    return Objects.equals(this.creationDate, clinicalVisitDto.creationDate) &&
        Objects.equals(this.changeDate, clinicalVisitDto.changeDate) &&
        Objects.equals(this.uuid, clinicalVisitDto.uuid) &&
        Objects.equals(this.clinicalCourse, clinicalVisitDto.clinicalCourse) &&
        Objects.equals(this.symptoms, clinicalVisitDto.symptoms) &&
        Objects.equals(this.disease, clinicalVisitDto.disease) &&
        Objects.equals(this.visitDateTime, clinicalVisitDto.visitDateTime) &&
        Objects.equals(this.visitRemarks, clinicalVisitDto.visitRemarks) &&
        Objects.equals(this.visitingPerson, clinicalVisitDto.visitingPerson);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDate, changeDate, uuid, clinicalCourse, symptoms, disease, visitDateTime, visitRemarks, visitingPerson);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClinicalVisitDto {\n");
    
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    changeDate: ").append(toIndentedString(changeDate)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    clinicalCourse: ").append(toIndentedString(clinicalCourse)).append("\n");
    sb.append("    symptoms: ").append(toIndentedString(symptoms)).append("\n");
    sb.append("    disease: ").append(toIndentedString(disease)).append("\n");
    sb.append("    visitDateTime: ").append(toIndentedString(visitDateTime)).append("\n");
    sb.append("    visitRemarks: ").append(toIndentedString(visitRemarks)).append("\n");
    sb.append("    visitingPerson: ").append(toIndentedString(visitingPerson)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
