/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.44.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import de.quarano.sormas.client.model.CaseReferenceDto;
import de.quarano.sormas.client.model.ContactCategory;
import de.quarano.sormas.client.model.ContactClassification;
import de.quarano.sormas.client.model.ContactProximity;
import de.quarano.sormas.client.model.ContactRelation;
import de.quarano.sormas.client.model.ContactStatus;
import de.quarano.sormas.client.model.Disease;
import de.quarano.sormas.client.model.DistrictReferenceDto;
import de.quarano.sormas.client.model.FollowUpStatus;
import de.quarano.sormas.client.model.PersonReferenceDto;
import de.quarano.sormas.client.model.QuarantineType;
import de.quarano.sormas.client.model.RegionReferenceDto;
import de.quarano.sormas.client.model.UserReferenceDto;
import de.quarano.sormas.client.model.YesNoUnknown;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
/**
 * ContactDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-09T17:56:16.099120+02:00[Europe/Berlin]")
public class ContactDto {
  @JsonProperty("creationDate")
  private OffsetDateTime creationDate = null;

  @JsonProperty("changeDate")
  private OffsetDateTime changeDate = null;

  @JsonProperty("uuid")
  private String uuid = null;

  @JsonProperty("caze")
  private CaseReferenceDto caze = null;

  @JsonProperty("caseIdExternalSystem")
  private String caseIdExternalSystem = null;

  @JsonProperty("caseOrEventInformation")
  private String caseOrEventInformation = null;

  @JsonProperty("disease")
  private Disease disease = null;

  @JsonProperty("diseaseDetails")
  private String diseaseDetails = null;

  @JsonProperty("reportDateTime")
  private OffsetDateTime reportDateTime = null;

  @JsonProperty("reportingUser")
  private UserReferenceDto reportingUser = null;

  @JsonProperty("reportLat")
  private Double reportLat = null;

  @JsonProperty("reportLon")
  private Double reportLon = null;

  @JsonProperty("reportLatLonAccuracy")
  private Float reportLatLonAccuracy = null;

  @JsonProperty("region")
  private RegionReferenceDto region = null;

  @JsonProperty("district")
  private DistrictReferenceDto district = null;

  @JsonProperty("lastContactDate")
  private OffsetDateTime lastContactDate = null;

  @JsonProperty("contactProximity")
  private ContactProximity contactProximity = null;

  @JsonProperty("contactProximityDetails")
  private String contactProximityDetails = null;

  @JsonProperty("contactCategory")
  private ContactCategory contactCategory = null;

  @JsonProperty("contactClassification")
  private ContactClassification contactClassification = null;

  @JsonProperty("contactStatus")
  private ContactStatus contactStatus = null;

  @JsonProperty("followUpStatus")
  private FollowUpStatus followUpStatus = null;

  @JsonProperty("followUpComment")
  private String followUpComment = null;

  @JsonProperty("followUpUntil")
  private OffsetDateTime followUpUntil = null;

  @JsonProperty("overwriteFollowUpUntil")
  private Boolean overwriteFollowUpUntil = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("relationToCase")
  private ContactRelation relationToCase = null;

  @JsonProperty("relationDescription")
  private String relationDescription = null;

  @JsonProperty("externalID")
  private String externalID = null;

  @JsonProperty("highPriority")
  private Boolean highPriority = null;

  @JsonProperty("immunosuppressiveTherapyBasicDisease")
  private YesNoUnknown immunosuppressiveTherapyBasicDisease = null;

  @JsonProperty("immunosuppressiveTherapyBasicDiseaseDetails")
  private String immunosuppressiveTherapyBasicDiseaseDetails = null;

  @JsonProperty("careForPeopleOver60")
  private YesNoUnknown careForPeopleOver60 = null;

  @JsonProperty("quarantine")
  private QuarantineType quarantine = null;

  @JsonProperty("quarantineTypeDetails")
  private String quarantineTypeDetails = null;

  @JsonProperty("quarantineFrom")
  private OffsetDateTime quarantineFrom = null;

  @JsonProperty("quarantineTo")
  private OffsetDateTime quarantineTo = null;

  @JsonProperty("person")
  private PersonReferenceDto person = null;

  @JsonProperty("contactOfficer")
  private UserReferenceDto contactOfficer = null;

  @JsonProperty("resultingCase")
  private CaseReferenceDto resultingCase = null;

  @JsonProperty("resultingCaseUser")
  private UserReferenceDto resultingCaseUser = null;

  @JsonProperty("quarantineHelpNeeded")
  private String quarantineHelpNeeded = null;

  @JsonProperty("quarantineOrderedVerbally")
  private Boolean quarantineOrderedVerbally = null;

  @JsonProperty("quarantineOrderedOfficialDocument")
  private Boolean quarantineOrderedOfficialDocument = null;

  @JsonProperty("quarantineOrderedVerballyDate")
  private OffsetDateTime quarantineOrderedVerballyDate = null;

  @JsonProperty("quarantineOrderedOfficialDocumentDate")
  private OffsetDateTime quarantineOrderedOfficialDocumentDate = null;

  @JsonProperty("quarantineHomePossible")
  private YesNoUnknown quarantineHomePossible = null;

  @JsonProperty("quarantineHomePossibleComment")
  private String quarantineHomePossibleComment = null;

  @JsonProperty("quarantineHomeSupplyEnsured")
  private YesNoUnknown quarantineHomeSupplyEnsured = null;

  @JsonProperty("quarantineHomeSupplyEnsuredComment")
  private String quarantineHomeSupplyEnsuredComment = null;

  @JsonProperty("additionalDetails")
  private String additionalDetails = null;

  public ContactDto creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @Schema(description = "")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public ContactDto changeDate(OffsetDateTime changeDate) {
    this.changeDate = changeDate;
    return this;
  }

   /**
   * Get changeDate
   * @return changeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getChangeDate() {
    return changeDate;
  }

  public void setChangeDate(OffsetDateTime changeDate) {
    this.changeDate = changeDate;
  }

  public ContactDto uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @Schema(description = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public ContactDto caze(CaseReferenceDto caze) {
    this.caze = caze;
    return this;
  }

   /**
   * Get caze
   * @return caze
  **/
  @Schema(description = "")
  public CaseReferenceDto getCaze() {
    return caze;
  }

  public void setCaze(CaseReferenceDto caze) {
    this.caze = caze;
  }

  public ContactDto caseIdExternalSystem(String caseIdExternalSystem) {
    this.caseIdExternalSystem = caseIdExternalSystem;
    return this;
  }

   /**
   * Get caseIdExternalSystem
   * @return caseIdExternalSystem
  **/
  @Schema(description = "")
  public String getCaseIdExternalSystem() {
    return caseIdExternalSystem;
  }

  public void setCaseIdExternalSystem(String caseIdExternalSystem) {
    this.caseIdExternalSystem = caseIdExternalSystem;
  }

  public ContactDto caseOrEventInformation(String caseOrEventInformation) {
    this.caseOrEventInformation = caseOrEventInformation;
    return this;
  }

   /**
   * Get caseOrEventInformation
   * @return caseOrEventInformation
  **/
  @Schema(description = "")
  public String getCaseOrEventInformation() {
    return caseOrEventInformation;
  }

  public void setCaseOrEventInformation(String caseOrEventInformation) {
    this.caseOrEventInformation = caseOrEventInformation;
  }

  public ContactDto disease(Disease disease) {
    this.disease = disease;
    return this;
  }

   /**
   * Get disease
   * @return disease
  **/
  @Schema(description = "")
  public Disease getDisease() {
    return disease;
  }

  public void setDisease(Disease disease) {
    this.disease = disease;
  }

  public ContactDto diseaseDetails(String diseaseDetails) {
    this.diseaseDetails = diseaseDetails;
    return this;
  }

   /**
   * Get diseaseDetails
   * @return diseaseDetails
  **/
  @Schema(description = "")
  public String getDiseaseDetails() {
    return diseaseDetails;
  }

  public void setDiseaseDetails(String diseaseDetails) {
    this.diseaseDetails = diseaseDetails;
  }

  public ContactDto reportDateTime(OffsetDateTime reportDateTime) {
    this.reportDateTime = reportDateTime;
    return this;
  }

   /**
   * Get reportDateTime
   * @return reportDateTime
  **/
  @Schema(required = true, description = "")
  public OffsetDateTime getReportDateTime() {
    return reportDateTime;
  }

  public void setReportDateTime(OffsetDateTime reportDateTime) {
    this.reportDateTime = reportDateTime;
  }

  public ContactDto reportingUser(UserReferenceDto reportingUser) {
    this.reportingUser = reportingUser;
    return this;
  }

   /**
   * Get reportingUser
   * @return reportingUser
  **/
  @Schema(required = true, description = "")
  public UserReferenceDto getReportingUser() {
    return reportingUser;
  }

  public void setReportingUser(UserReferenceDto reportingUser) {
    this.reportingUser = reportingUser;
  }

  public ContactDto reportLat(Double reportLat) {
    this.reportLat = reportLat;
    return this;
  }

   /**
   * Get reportLat
   * @return reportLat
  **/
  @Schema(description = "")
  public Double getReportLat() {
    return reportLat;
  }

  public void setReportLat(Double reportLat) {
    this.reportLat = reportLat;
  }

  public ContactDto reportLon(Double reportLon) {
    this.reportLon = reportLon;
    return this;
  }

   /**
   * Get reportLon
   * @return reportLon
  **/
  @Schema(description = "")
  public Double getReportLon() {
    return reportLon;
  }

  public void setReportLon(Double reportLon) {
    this.reportLon = reportLon;
  }

  public ContactDto reportLatLonAccuracy(Float reportLatLonAccuracy) {
    this.reportLatLonAccuracy = reportLatLonAccuracy;
    return this;
  }

   /**
   * Get reportLatLonAccuracy
   * @return reportLatLonAccuracy
  **/
  @Schema(description = "")
  public Float getReportLatLonAccuracy() {
    return reportLatLonAccuracy;
  }

  public void setReportLatLonAccuracy(Float reportLatLonAccuracy) {
    this.reportLatLonAccuracy = reportLatLonAccuracy;
  }

  public ContactDto region(RegionReferenceDto region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @Schema(description = "")
  public RegionReferenceDto getRegion() {
    return region;
  }

  public void setRegion(RegionReferenceDto region) {
    this.region = region;
  }

  public ContactDto district(DistrictReferenceDto district) {
    this.district = district;
    return this;
  }

   /**
   * Get district
   * @return district
  **/
  @Schema(description = "")
  public DistrictReferenceDto getDistrict() {
    return district;
  }

  public void setDistrict(DistrictReferenceDto district) {
    this.district = district;
  }

  public ContactDto lastContactDate(OffsetDateTime lastContactDate) {
    this.lastContactDate = lastContactDate;
    return this;
  }

   /**
   * Get lastContactDate
   * @return lastContactDate
  **/
  @Schema(description = "")
  public OffsetDateTime getLastContactDate() {
    return lastContactDate;
  }

  public void setLastContactDate(OffsetDateTime lastContactDate) {
    this.lastContactDate = lastContactDate;
  }

  public ContactDto contactProximity(ContactProximity contactProximity) {
    this.contactProximity = contactProximity;
    return this;
  }

   /**
   * Get contactProximity
   * @return contactProximity
  **/
  @Schema(description = "")
  public ContactProximity getContactProximity() {
    return contactProximity;
  }

  public void setContactProximity(ContactProximity contactProximity) {
    this.contactProximity = contactProximity;
  }

  public ContactDto contactProximityDetails(String contactProximityDetails) {
    this.contactProximityDetails = contactProximityDetails;
    return this;
  }

   /**
   * Get contactProximityDetails
   * @return contactProximityDetails
  **/
  @Schema(description = "")
  public String getContactProximityDetails() {
    return contactProximityDetails;
  }

  public void setContactProximityDetails(String contactProximityDetails) {
    this.contactProximityDetails = contactProximityDetails;
  }

  public ContactDto contactCategory(ContactCategory contactCategory) {
    this.contactCategory = contactCategory;
    return this;
  }

   /**
   * Get contactCategory
   * @return contactCategory
  **/
  @Schema(description = "")
  public ContactCategory getContactCategory() {
    return contactCategory;
  }

  public void setContactCategory(ContactCategory contactCategory) {
    this.contactCategory = contactCategory;
  }

  public ContactDto contactClassification(ContactClassification contactClassification) {
    this.contactClassification = contactClassification;
    return this;
  }

   /**
   * Get contactClassification
   * @return contactClassification
  **/
  @Schema(description = "")
  public ContactClassification getContactClassification() {
    return contactClassification;
  }

  public void setContactClassification(ContactClassification contactClassification) {
    this.contactClassification = contactClassification;
  }

  public ContactDto contactStatus(ContactStatus contactStatus) {
    this.contactStatus = contactStatus;
    return this;
  }

   /**
   * Get contactStatus
   * @return contactStatus
  **/
  @Schema(description = "")
  public ContactStatus getContactStatus() {
    return contactStatus;
  }

  public void setContactStatus(ContactStatus contactStatus) {
    this.contactStatus = contactStatus;
  }

  public ContactDto followUpStatus(FollowUpStatus followUpStatus) {
    this.followUpStatus = followUpStatus;
    return this;
  }

   /**
   * Get followUpStatus
   * @return followUpStatus
  **/
  @Schema(description = "")
  public FollowUpStatus getFollowUpStatus() {
    return followUpStatus;
  }

  public void setFollowUpStatus(FollowUpStatus followUpStatus) {
    this.followUpStatus = followUpStatus;
  }

  public ContactDto followUpComment(String followUpComment) {
    this.followUpComment = followUpComment;
    return this;
  }

   /**
   * Get followUpComment
   * @return followUpComment
  **/
  @Schema(description = "")
  public String getFollowUpComment() {
    return followUpComment;
  }

  public void setFollowUpComment(String followUpComment) {
    this.followUpComment = followUpComment;
  }

  public ContactDto followUpUntil(OffsetDateTime followUpUntil) {
    this.followUpUntil = followUpUntil;
    return this;
  }

   /**
   * Get followUpUntil
   * @return followUpUntil
  **/
  @Schema(description = "")
  public OffsetDateTime getFollowUpUntil() {
    return followUpUntil;
  }

  public void setFollowUpUntil(OffsetDateTime followUpUntil) {
    this.followUpUntil = followUpUntil;
  }

  public ContactDto overwriteFollowUpUntil(Boolean overwriteFollowUpUntil) {
    this.overwriteFollowUpUntil = overwriteFollowUpUntil;
    return this;
  }

   /**
   * Get overwriteFollowUpUntil
   * @return overwriteFollowUpUntil
  **/
  @Schema(description = "")
  public Boolean isOverwriteFollowUpUntil() {
    return overwriteFollowUpUntil;
  }

  public void setOverwriteFollowUpUntil(Boolean overwriteFollowUpUntil) {
    this.overwriteFollowUpUntil = overwriteFollowUpUntil;
  }

  public ContactDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ContactDto relationToCase(ContactRelation relationToCase) {
    this.relationToCase = relationToCase;
    return this;
  }

   /**
   * Get relationToCase
   * @return relationToCase
  **/
  @Schema(description = "")
  public ContactRelation getRelationToCase() {
    return relationToCase;
  }

  public void setRelationToCase(ContactRelation relationToCase) {
    this.relationToCase = relationToCase;
  }

  public ContactDto relationDescription(String relationDescription) {
    this.relationDescription = relationDescription;
    return this;
  }

   /**
   * Get relationDescription
   * @return relationDescription
  **/
  @Schema(description = "")
  public String getRelationDescription() {
    return relationDescription;
  }

  public void setRelationDescription(String relationDescription) {
    this.relationDescription = relationDescription;
  }

  public ContactDto externalID(String externalID) {
    this.externalID = externalID;
    return this;
  }

   /**
   * Get externalID
   * @return externalID
  **/
  @Schema(description = "")
  public String getExternalID() {
    return externalID;
  }

  public void setExternalID(String externalID) {
    this.externalID = externalID;
  }

  public ContactDto highPriority(Boolean highPriority) {
    this.highPriority = highPriority;
    return this;
  }

   /**
   * Get highPriority
   * @return highPriority
  **/
  @Schema(description = "")
  public Boolean isHighPriority() {
    return highPriority;
  }

  public void setHighPriority(Boolean highPriority) {
    this.highPriority = highPriority;
  }

  public ContactDto immunosuppressiveTherapyBasicDisease(YesNoUnknown immunosuppressiveTherapyBasicDisease) {
    this.immunosuppressiveTherapyBasicDisease = immunosuppressiveTherapyBasicDisease;
    return this;
  }

   /**
   * Get immunosuppressiveTherapyBasicDisease
   * @return immunosuppressiveTherapyBasicDisease
  **/
  @Schema(description = "")
  public YesNoUnknown getImmunosuppressiveTherapyBasicDisease() {
    return immunosuppressiveTherapyBasicDisease;
  }

  public void setImmunosuppressiveTherapyBasicDisease(YesNoUnknown immunosuppressiveTherapyBasicDisease) {
    this.immunosuppressiveTherapyBasicDisease = immunosuppressiveTherapyBasicDisease;
  }

  public ContactDto immunosuppressiveTherapyBasicDiseaseDetails(String immunosuppressiveTherapyBasicDiseaseDetails) {
    this.immunosuppressiveTherapyBasicDiseaseDetails = immunosuppressiveTherapyBasicDiseaseDetails;
    return this;
  }

   /**
   * Get immunosuppressiveTherapyBasicDiseaseDetails
   * @return immunosuppressiveTherapyBasicDiseaseDetails
  **/
  @Schema(description = "")
  public String getImmunosuppressiveTherapyBasicDiseaseDetails() {
    return immunosuppressiveTherapyBasicDiseaseDetails;
  }

  public void setImmunosuppressiveTherapyBasicDiseaseDetails(String immunosuppressiveTherapyBasicDiseaseDetails) {
    this.immunosuppressiveTherapyBasicDiseaseDetails = immunosuppressiveTherapyBasicDiseaseDetails;
  }

  public ContactDto careForPeopleOver60(YesNoUnknown careForPeopleOver60) {
    this.careForPeopleOver60 = careForPeopleOver60;
    return this;
  }

   /**
   * Get careForPeopleOver60
   * @return careForPeopleOver60
  **/
  @Schema(description = "")
  public YesNoUnknown getCareForPeopleOver60() {
    return careForPeopleOver60;
  }

  public void setCareForPeopleOver60(YesNoUnknown careForPeopleOver60) {
    this.careForPeopleOver60 = careForPeopleOver60;
  }

  public ContactDto quarantine(QuarantineType quarantine) {
    this.quarantine = quarantine;
    return this;
  }

   /**
   * Get quarantine
   * @return quarantine
  **/
  @Schema(description = "")
  public QuarantineType getQuarantine() {
    return quarantine;
  }

  public void setQuarantine(QuarantineType quarantine) {
    this.quarantine = quarantine;
  }

  public ContactDto quarantineTypeDetails(String quarantineTypeDetails) {
    this.quarantineTypeDetails = quarantineTypeDetails;
    return this;
  }

   /**
   * Get quarantineTypeDetails
   * @return quarantineTypeDetails
  **/
  @Schema(description = "")
  public String getQuarantineTypeDetails() {
    return quarantineTypeDetails;
  }

  public void setQuarantineTypeDetails(String quarantineTypeDetails) {
    this.quarantineTypeDetails = quarantineTypeDetails;
  }

  public ContactDto quarantineFrom(OffsetDateTime quarantineFrom) {
    this.quarantineFrom = quarantineFrom;
    return this;
  }

   /**
   * Get quarantineFrom
   * @return quarantineFrom
  **/
  @Schema(description = "")
  public OffsetDateTime getQuarantineFrom() {
    return quarantineFrom;
  }

  public void setQuarantineFrom(OffsetDateTime quarantineFrom) {
    this.quarantineFrom = quarantineFrom;
  }

  public ContactDto quarantineTo(OffsetDateTime quarantineTo) {
    this.quarantineTo = quarantineTo;
    return this;
  }

   /**
   * Get quarantineTo
   * @return quarantineTo
  **/
  @Schema(description = "")
  public OffsetDateTime getQuarantineTo() {
    return quarantineTo;
  }

  public void setQuarantineTo(OffsetDateTime quarantineTo) {
    this.quarantineTo = quarantineTo;
  }

  public ContactDto person(PersonReferenceDto person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  @Schema(required = true, description = "")
  public PersonReferenceDto getPerson() {
    return person;
  }

  public void setPerson(PersonReferenceDto person) {
    this.person = person;
  }

  public ContactDto contactOfficer(UserReferenceDto contactOfficer) {
    this.contactOfficer = contactOfficer;
    return this;
  }

   /**
   * Get contactOfficer
   * @return contactOfficer
  **/
  @Schema(description = "")
  public UserReferenceDto getContactOfficer() {
    return contactOfficer;
  }

  public void setContactOfficer(UserReferenceDto contactOfficer) {
    this.contactOfficer = contactOfficer;
  }

  public ContactDto resultingCase(CaseReferenceDto resultingCase) {
    this.resultingCase = resultingCase;
    return this;
  }

   /**
   * Get resultingCase
   * @return resultingCase
  **/
  @Schema(description = "")
  public CaseReferenceDto getResultingCase() {
    return resultingCase;
  }

  public void setResultingCase(CaseReferenceDto resultingCase) {
    this.resultingCase = resultingCase;
  }

  public ContactDto resultingCaseUser(UserReferenceDto resultingCaseUser) {
    this.resultingCaseUser = resultingCaseUser;
    return this;
  }

   /**
   * Get resultingCaseUser
   * @return resultingCaseUser
  **/
  @Schema(description = "")
  public UserReferenceDto getResultingCaseUser() {
    return resultingCaseUser;
  }

  public void setResultingCaseUser(UserReferenceDto resultingCaseUser) {
    this.resultingCaseUser = resultingCaseUser;
  }

  public ContactDto quarantineHelpNeeded(String quarantineHelpNeeded) {
    this.quarantineHelpNeeded = quarantineHelpNeeded;
    return this;
  }

   /**
   * Get quarantineHelpNeeded
   * @return quarantineHelpNeeded
  **/
  @Schema(description = "")
  public String getQuarantineHelpNeeded() {
    return quarantineHelpNeeded;
  }

  public void setQuarantineHelpNeeded(String quarantineHelpNeeded) {
    this.quarantineHelpNeeded = quarantineHelpNeeded;
  }

  public ContactDto quarantineOrderedVerbally(Boolean quarantineOrderedVerbally) {
    this.quarantineOrderedVerbally = quarantineOrderedVerbally;
    return this;
  }

   /**
   * Get quarantineOrderedVerbally
   * @return quarantineOrderedVerbally
  **/
  @Schema(description = "")
  public Boolean isQuarantineOrderedVerbally() {
    return quarantineOrderedVerbally;
  }

  public void setQuarantineOrderedVerbally(Boolean quarantineOrderedVerbally) {
    this.quarantineOrderedVerbally = quarantineOrderedVerbally;
  }

  public ContactDto quarantineOrderedOfficialDocument(Boolean quarantineOrderedOfficialDocument) {
    this.quarantineOrderedOfficialDocument = quarantineOrderedOfficialDocument;
    return this;
  }

   /**
   * Get quarantineOrderedOfficialDocument
   * @return quarantineOrderedOfficialDocument
  **/
  @Schema(description = "")
  public Boolean isQuarantineOrderedOfficialDocument() {
    return quarantineOrderedOfficialDocument;
  }

  public void setQuarantineOrderedOfficialDocument(Boolean quarantineOrderedOfficialDocument) {
    this.quarantineOrderedOfficialDocument = quarantineOrderedOfficialDocument;
  }

  public ContactDto quarantineOrderedVerballyDate(OffsetDateTime quarantineOrderedVerballyDate) {
    this.quarantineOrderedVerballyDate = quarantineOrderedVerballyDate;
    return this;
  }

   /**
   * Get quarantineOrderedVerballyDate
   * @return quarantineOrderedVerballyDate
  **/
  @Schema(description = "")
  public OffsetDateTime getQuarantineOrderedVerballyDate() {
    return quarantineOrderedVerballyDate;
  }

  public void setQuarantineOrderedVerballyDate(OffsetDateTime quarantineOrderedVerballyDate) {
    this.quarantineOrderedVerballyDate = quarantineOrderedVerballyDate;
  }

  public ContactDto quarantineOrderedOfficialDocumentDate(OffsetDateTime quarantineOrderedOfficialDocumentDate) {
    this.quarantineOrderedOfficialDocumentDate = quarantineOrderedOfficialDocumentDate;
    return this;
  }

   /**
   * Get quarantineOrderedOfficialDocumentDate
   * @return quarantineOrderedOfficialDocumentDate
  **/
  @Schema(description = "")
  public OffsetDateTime getQuarantineOrderedOfficialDocumentDate() {
    return quarantineOrderedOfficialDocumentDate;
  }

  public void setQuarantineOrderedOfficialDocumentDate(OffsetDateTime quarantineOrderedOfficialDocumentDate) {
    this.quarantineOrderedOfficialDocumentDate = quarantineOrderedOfficialDocumentDate;
  }

  public ContactDto quarantineHomePossible(YesNoUnknown quarantineHomePossible) {
    this.quarantineHomePossible = quarantineHomePossible;
    return this;
  }

   /**
   * Get quarantineHomePossible
   * @return quarantineHomePossible
  **/
  @Schema(description = "")
  public YesNoUnknown getQuarantineHomePossible() {
    return quarantineHomePossible;
  }

  public void setQuarantineHomePossible(YesNoUnknown quarantineHomePossible) {
    this.quarantineHomePossible = quarantineHomePossible;
  }

  public ContactDto quarantineHomePossibleComment(String quarantineHomePossibleComment) {
    this.quarantineHomePossibleComment = quarantineHomePossibleComment;
    return this;
  }

   /**
   * Get quarantineHomePossibleComment
   * @return quarantineHomePossibleComment
  **/
  @Schema(description = "")
  public String getQuarantineHomePossibleComment() {
    return quarantineHomePossibleComment;
  }

  public void setQuarantineHomePossibleComment(String quarantineHomePossibleComment) {
    this.quarantineHomePossibleComment = quarantineHomePossibleComment;
  }

  public ContactDto quarantineHomeSupplyEnsured(YesNoUnknown quarantineHomeSupplyEnsured) {
    this.quarantineHomeSupplyEnsured = quarantineHomeSupplyEnsured;
    return this;
  }

   /**
   * Get quarantineHomeSupplyEnsured
   * @return quarantineHomeSupplyEnsured
  **/
  @Schema(description = "")
  public YesNoUnknown getQuarantineHomeSupplyEnsured() {
    return quarantineHomeSupplyEnsured;
  }

  public void setQuarantineHomeSupplyEnsured(YesNoUnknown quarantineHomeSupplyEnsured) {
    this.quarantineHomeSupplyEnsured = quarantineHomeSupplyEnsured;
  }

  public ContactDto quarantineHomeSupplyEnsuredComment(String quarantineHomeSupplyEnsuredComment) {
    this.quarantineHomeSupplyEnsuredComment = quarantineHomeSupplyEnsuredComment;
    return this;
  }

   /**
   * Get quarantineHomeSupplyEnsuredComment
   * @return quarantineHomeSupplyEnsuredComment
  **/
  @Schema(description = "")
  public String getQuarantineHomeSupplyEnsuredComment() {
    return quarantineHomeSupplyEnsuredComment;
  }

  public void setQuarantineHomeSupplyEnsuredComment(String quarantineHomeSupplyEnsuredComment) {
    this.quarantineHomeSupplyEnsuredComment = quarantineHomeSupplyEnsuredComment;
  }

  public ContactDto additionalDetails(String additionalDetails) {
    this.additionalDetails = additionalDetails;
    return this;
  }

   /**
   * Get additionalDetails
   * @return additionalDetails
  **/
  @Schema(description = "")
  public String getAdditionalDetails() {
    return additionalDetails;
  }

  public void setAdditionalDetails(String additionalDetails) {
    this.additionalDetails = additionalDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactDto contactDto = (ContactDto) o;
    return Objects.equals(this.creationDate, contactDto.creationDate) &&
        Objects.equals(this.changeDate, contactDto.changeDate) &&
        Objects.equals(this.uuid, contactDto.uuid) &&
        Objects.equals(this.caze, contactDto.caze) &&
        Objects.equals(this.caseIdExternalSystem, contactDto.caseIdExternalSystem) &&
        Objects.equals(this.caseOrEventInformation, contactDto.caseOrEventInformation) &&
        Objects.equals(this.disease, contactDto.disease) &&
        Objects.equals(this.diseaseDetails, contactDto.diseaseDetails) &&
        Objects.equals(this.reportDateTime, contactDto.reportDateTime) &&
        Objects.equals(this.reportingUser, contactDto.reportingUser) &&
        Objects.equals(this.reportLat, contactDto.reportLat) &&
        Objects.equals(this.reportLon, contactDto.reportLon) &&
        Objects.equals(this.reportLatLonAccuracy, contactDto.reportLatLonAccuracy) &&
        Objects.equals(this.region, contactDto.region) &&
        Objects.equals(this.district, contactDto.district) &&
        Objects.equals(this.lastContactDate, contactDto.lastContactDate) &&
        Objects.equals(this.contactProximity, contactDto.contactProximity) &&
        Objects.equals(this.contactProximityDetails, contactDto.contactProximityDetails) &&
        Objects.equals(this.contactCategory, contactDto.contactCategory) &&
        Objects.equals(this.contactClassification, contactDto.contactClassification) &&
        Objects.equals(this.contactStatus, contactDto.contactStatus) &&
        Objects.equals(this.followUpStatus, contactDto.followUpStatus) &&
        Objects.equals(this.followUpComment, contactDto.followUpComment) &&
        Objects.equals(this.followUpUntil, contactDto.followUpUntil) &&
        Objects.equals(this.overwriteFollowUpUntil, contactDto.overwriteFollowUpUntil) &&
        Objects.equals(this.description, contactDto.description) &&
        Objects.equals(this.relationToCase, contactDto.relationToCase) &&
        Objects.equals(this.relationDescription, contactDto.relationDescription) &&
        Objects.equals(this.externalID, contactDto.externalID) &&
        Objects.equals(this.highPriority, contactDto.highPriority) &&
        Objects.equals(this.immunosuppressiveTherapyBasicDisease, contactDto.immunosuppressiveTherapyBasicDisease) &&
        Objects.equals(this.immunosuppressiveTherapyBasicDiseaseDetails, contactDto.immunosuppressiveTherapyBasicDiseaseDetails) &&
        Objects.equals(this.careForPeopleOver60, contactDto.careForPeopleOver60) &&
        Objects.equals(this.quarantine, contactDto.quarantine) &&
        Objects.equals(this.quarantineTypeDetails, contactDto.quarantineTypeDetails) &&
        Objects.equals(this.quarantineFrom, contactDto.quarantineFrom) &&
        Objects.equals(this.quarantineTo, contactDto.quarantineTo) &&
        Objects.equals(this.person, contactDto.person) &&
        Objects.equals(this.contactOfficer, contactDto.contactOfficer) &&
        Objects.equals(this.resultingCase, contactDto.resultingCase) &&
        Objects.equals(this.resultingCaseUser, contactDto.resultingCaseUser) &&
        Objects.equals(this.quarantineHelpNeeded, contactDto.quarantineHelpNeeded) &&
        Objects.equals(this.quarantineOrderedVerbally, contactDto.quarantineOrderedVerbally) &&
        Objects.equals(this.quarantineOrderedOfficialDocument, contactDto.quarantineOrderedOfficialDocument) &&
        Objects.equals(this.quarantineOrderedVerballyDate, contactDto.quarantineOrderedVerballyDate) &&
        Objects.equals(this.quarantineOrderedOfficialDocumentDate, contactDto.quarantineOrderedOfficialDocumentDate) &&
        Objects.equals(this.quarantineHomePossible, contactDto.quarantineHomePossible) &&
        Objects.equals(this.quarantineHomePossibleComment, contactDto.quarantineHomePossibleComment) &&
        Objects.equals(this.quarantineHomeSupplyEnsured, contactDto.quarantineHomeSupplyEnsured) &&
        Objects.equals(this.quarantineHomeSupplyEnsuredComment, contactDto.quarantineHomeSupplyEnsuredComment) &&
        Objects.equals(this.additionalDetails, contactDto.additionalDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDate, changeDate, uuid, caze, caseIdExternalSystem, caseOrEventInformation, disease, diseaseDetails, reportDateTime, reportingUser, reportLat, reportLon, reportLatLonAccuracy, region, district, lastContactDate, contactProximity, contactProximityDetails, contactCategory, contactClassification, contactStatus, followUpStatus, followUpComment, followUpUntil, overwriteFollowUpUntil, description, relationToCase, relationDescription, externalID, highPriority, immunosuppressiveTherapyBasicDisease, immunosuppressiveTherapyBasicDiseaseDetails, careForPeopleOver60, quarantine, quarantineTypeDetails, quarantineFrom, quarantineTo, person, contactOfficer, resultingCase, resultingCaseUser, quarantineHelpNeeded, quarantineOrderedVerbally, quarantineOrderedOfficialDocument, quarantineOrderedVerballyDate, quarantineOrderedOfficialDocumentDate, quarantineHomePossible, quarantineHomePossibleComment, quarantineHomeSupplyEnsured, quarantineHomeSupplyEnsuredComment, additionalDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactDto {\n");
    
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    changeDate: ").append(toIndentedString(changeDate)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    caze: ").append(toIndentedString(caze)).append("\n");
    sb.append("    caseIdExternalSystem: ").append(toIndentedString(caseIdExternalSystem)).append("\n");
    sb.append("    caseOrEventInformation: ").append(toIndentedString(caseOrEventInformation)).append("\n");
    sb.append("    disease: ").append(toIndentedString(disease)).append("\n");
    sb.append("    diseaseDetails: ").append(toIndentedString(diseaseDetails)).append("\n");
    sb.append("    reportDateTime: ").append(toIndentedString(reportDateTime)).append("\n");
    sb.append("    reportingUser: ").append(toIndentedString(reportingUser)).append("\n");
    sb.append("    reportLat: ").append(toIndentedString(reportLat)).append("\n");
    sb.append("    reportLon: ").append(toIndentedString(reportLon)).append("\n");
    sb.append("    reportLatLonAccuracy: ").append(toIndentedString(reportLatLonAccuracy)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    lastContactDate: ").append(toIndentedString(lastContactDate)).append("\n");
    sb.append("    contactProximity: ").append(toIndentedString(contactProximity)).append("\n");
    sb.append("    contactProximityDetails: ").append(toIndentedString(contactProximityDetails)).append("\n");
    sb.append("    contactCategory: ").append(toIndentedString(contactCategory)).append("\n");
    sb.append("    contactClassification: ").append(toIndentedString(contactClassification)).append("\n");
    sb.append("    contactStatus: ").append(toIndentedString(contactStatus)).append("\n");
    sb.append("    followUpStatus: ").append(toIndentedString(followUpStatus)).append("\n");
    sb.append("    followUpComment: ").append(toIndentedString(followUpComment)).append("\n");
    sb.append("    followUpUntil: ").append(toIndentedString(followUpUntil)).append("\n");
    sb.append("    overwriteFollowUpUntil: ").append(toIndentedString(overwriteFollowUpUntil)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    relationToCase: ").append(toIndentedString(relationToCase)).append("\n");
    sb.append("    relationDescription: ").append(toIndentedString(relationDescription)).append("\n");
    sb.append("    externalID: ").append(toIndentedString(externalID)).append("\n");
    sb.append("    highPriority: ").append(toIndentedString(highPriority)).append("\n");
    sb.append("    immunosuppressiveTherapyBasicDisease: ").append(toIndentedString(immunosuppressiveTherapyBasicDisease)).append("\n");
    sb.append("    immunosuppressiveTherapyBasicDiseaseDetails: ").append(toIndentedString(immunosuppressiveTherapyBasicDiseaseDetails)).append("\n");
    sb.append("    careForPeopleOver60: ").append(toIndentedString(careForPeopleOver60)).append("\n");
    sb.append("    quarantine: ").append(toIndentedString(quarantine)).append("\n");
    sb.append("    quarantineTypeDetails: ").append(toIndentedString(quarantineTypeDetails)).append("\n");
    sb.append("    quarantineFrom: ").append(toIndentedString(quarantineFrom)).append("\n");
    sb.append("    quarantineTo: ").append(toIndentedString(quarantineTo)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    contactOfficer: ").append(toIndentedString(contactOfficer)).append("\n");
    sb.append("    resultingCase: ").append(toIndentedString(resultingCase)).append("\n");
    sb.append("    resultingCaseUser: ").append(toIndentedString(resultingCaseUser)).append("\n");
    sb.append("    quarantineHelpNeeded: ").append(toIndentedString(quarantineHelpNeeded)).append("\n");
    sb.append("    quarantineOrderedVerbally: ").append(toIndentedString(quarantineOrderedVerbally)).append("\n");
    sb.append("    quarantineOrderedOfficialDocument: ").append(toIndentedString(quarantineOrderedOfficialDocument)).append("\n");
    sb.append("    quarantineOrderedVerballyDate: ").append(toIndentedString(quarantineOrderedVerballyDate)).append("\n");
    sb.append("    quarantineOrderedOfficialDocumentDate: ").append(toIndentedString(quarantineOrderedOfficialDocumentDate)).append("\n");
    sb.append("    quarantineHomePossible: ").append(toIndentedString(quarantineHomePossible)).append("\n");
    sb.append("    quarantineHomePossibleComment: ").append(toIndentedString(quarantineHomePossibleComment)).append("\n");
    sb.append("    quarantineHomeSupplyEnsured: ").append(toIndentedString(quarantineHomeSupplyEnsured)).append("\n");
    sb.append("    quarantineHomeSupplyEnsuredComment: ").append(toIndentedString(quarantineHomeSupplyEnsuredComment)).append("\n");
    sb.append("    additionalDetails: ").append(toIndentedString(additionalDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
