/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.44.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import de.quarano.sormas.client.model.LocationDto;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
/**
 * EpiDataGatheringDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-09T17:56:16.099120+02:00[Europe/Berlin]")
public class EpiDataGatheringDto {
  @JsonProperty("creationDate")
  private OffsetDateTime creationDate = null;

  @JsonProperty("changeDate")
  private OffsetDateTime changeDate = null;

  @JsonProperty("uuid")
  private String uuid = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("gatheringDate")
  private OffsetDateTime gatheringDate = null;

  @JsonProperty("gatheringAddress")
  private LocationDto gatheringAddress = null;

  public EpiDataGatheringDto creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @Schema(description = "")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public EpiDataGatheringDto changeDate(OffsetDateTime changeDate) {
    this.changeDate = changeDate;
    return this;
  }

   /**
   * Get changeDate
   * @return changeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getChangeDate() {
    return changeDate;
  }

  public void setChangeDate(OffsetDateTime changeDate) {
    this.changeDate = changeDate;
  }

  public EpiDataGatheringDto uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @Schema(description = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public EpiDataGatheringDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EpiDataGatheringDto gatheringDate(OffsetDateTime gatheringDate) {
    this.gatheringDate = gatheringDate;
    return this;
  }

   /**
   * Get gatheringDate
   * @return gatheringDate
  **/
  @Schema(description = "")
  public OffsetDateTime getGatheringDate() {
    return gatheringDate;
  }

  public void setGatheringDate(OffsetDateTime gatheringDate) {
    this.gatheringDate = gatheringDate;
  }

  public EpiDataGatheringDto gatheringAddress(LocationDto gatheringAddress) {
    this.gatheringAddress = gatheringAddress;
    return this;
  }

   /**
   * Get gatheringAddress
   * @return gatheringAddress
  **/
  @Schema(description = "")
  public LocationDto getGatheringAddress() {
    return gatheringAddress;
  }

  public void setGatheringAddress(LocationDto gatheringAddress) {
    this.gatheringAddress = gatheringAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EpiDataGatheringDto epiDataGatheringDto = (EpiDataGatheringDto) o;
    return Objects.equals(this.creationDate, epiDataGatheringDto.creationDate) &&
        Objects.equals(this.changeDate, epiDataGatheringDto.changeDate) &&
        Objects.equals(this.uuid, epiDataGatheringDto.uuid) &&
        Objects.equals(this.description, epiDataGatheringDto.description) &&
        Objects.equals(this.gatheringDate, epiDataGatheringDto.gatheringDate) &&
        Objects.equals(this.gatheringAddress, epiDataGatheringDto.gatheringAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDate, changeDate, uuid, description, gatheringDate, gatheringAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EpiDataGatheringDto {\n");
    
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    changeDate: ").append(toIndentedString(changeDate)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    gatheringDate: ").append(toIndentedString(gatheringDate)).append("\n");
    sb.append("    gatheringAddress: ").append(toIndentedString(gatheringAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
