/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.52.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
/**
 * InfrastructureChangeDatesDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-15T22:47:05.366577+01:00[Europe/Berlin]")
public class InfrastructureChangeDatesDto {
  @JsonProperty("countryChangeDate")
  private OffsetDateTime countryChangeDate = null;

  @JsonProperty("regionChangeDate")
  private OffsetDateTime regionChangeDate = null;

  @JsonProperty("districtChangeDate")
  private OffsetDateTime districtChangeDate = null;

  @JsonProperty("communityChangeDate")
  private OffsetDateTime communityChangeDate = null;

  @JsonProperty("facilityChangeDate")
  private OffsetDateTime facilityChangeDate = null;

  @JsonProperty("pointOfEntryChangeDate")
  private OffsetDateTime pointOfEntryChangeDate = null;

  @JsonProperty("userChangeDate")
  private OffsetDateTime userChangeDate = null;

  @JsonProperty("diseaseClassificationChangeDate")
  private OffsetDateTime diseaseClassificationChangeDate = null;

  @JsonProperty("diseaseConfigurationChangeDate")
  private OffsetDateTime diseaseConfigurationChangeDate = null;

  @JsonProperty("userRoleConfigurationChangeDate")
  private OffsetDateTime userRoleConfigurationChangeDate = null;

  @JsonProperty("featureConfigurationChangeDate")
  private OffsetDateTime featureConfigurationChangeDate = null;

  @JsonProperty("campaignChangeDate")
  private OffsetDateTime campaignChangeDate = null;

  @JsonProperty("campaignFormMetaChangeDate")
  private OffsetDateTime campaignFormMetaChangeDate = null;

  public InfrastructureChangeDatesDto countryChangeDate(OffsetDateTime countryChangeDate) {
    this.countryChangeDate = countryChangeDate;
    return this;
  }

   /**
   * Get countryChangeDate
   * @return countryChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getCountryChangeDate() {
    return countryChangeDate;
  }

  public void setCountryChangeDate(OffsetDateTime countryChangeDate) {
    this.countryChangeDate = countryChangeDate;
  }

  public InfrastructureChangeDatesDto regionChangeDate(OffsetDateTime regionChangeDate) {
    this.regionChangeDate = regionChangeDate;
    return this;
  }

   /**
   * Get regionChangeDate
   * @return regionChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getRegionChangeDate() {
    return regionChangeDate;
  }

  public void setRegionChangeDate(OffsetDateTime regionChangeDate) {
    this.regionChangeDate = regionChangeDate;
  }

  public InfrastructureChangeDatesDto districtChangeDate(OffsetDateTime districtChangeDate) {
    this.districtChangeDate = districtChangeDate;
    return this;
  }

   /**
   * Get districtChangeDate
   * @return districtChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getDistrictChangeDate() {
    return districtChangeDate;
  }

  public void setDistrictChangeDate(OffsetDateTime districtChangeDate) {
    this.districtChangeDate = districtChangeDate;
  }

  public InfrastructureChangeDatesDto communityChangeDate(OffsetDateTime communityChangeDate) {
    this.communityChangeDate = communityChangeDate;
    return this;
  }

   /**
   * Get communityChangeDate
   * @return communityChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getCommunityChangeDate() {
    return communityChangeDate;
  }

  public void setCommunityChangeDate(OffsetDateTime communityChangeDate) {
    this.communityChangeDate = communityChangeDate;
  }

  public InfrastructureChangeDatesDto facilityChangeDate(OffsetDateTime facilityChangeDate) {
    this.facilityChangeDate = facilityChangeDate;
    return this;
  }

   /**
   * Get facilityChangeDate
   * @return facilityChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getFacilityChangeDate() {
    return facilityChangeDate;
  }

  public void setFacilityChangeDate(OffsetDateTime facilityChangeDate) {
    this.facilityChangeDate = facilityChangeDate;
  }

  public InfrastructureChangeDatesDto pointOfEntryChangeDate(OffsetDateTime pointOfEntryChangeDate) {
    this.pointOfEntryChangeDate = pointOfEntryChangeDate;
    return this;
  }

   /**
   * Get pointOfEntryChangeDate
   * @return pointOfEntryChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getPointOfEntryChangeDate() {
    return pointOfEntryChangeDate;
  }

  public void setPointOfEntryChangeDate(OffsetDateTime pointOfEntryChangeDate) {
    this.pointOfEntryChangeDate = pointOfEntryChangeDate;
  }

  public InfrastructureChangeDatesDto userChangeDate(OffsetDateTime userChangeDate) {
    this.userChangeDate = userChangeDate;
    return this;
  }

   /**
   * Get userChangeDate
   * @return userChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getUserChangeDate() {
    return userChangeDate;
  }

  public void setUserChangeDate(OffsetDateTime userChangeDate) {
    this.userChangeDate = userChangeDate;
  }

  public InfrastructureChangeDatesDto diseaseClassificationChangeDate(OffsetDateTime diseaseClassificationChangeDate) {
    this.diseaseClassificationChangeDate = diseaseClassificationChangeDate;
    return this;
  }

   /**
   * Get diseaseClassificationChangeDate
   * @return diseaseClassificationChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getDiseaseClassificationChangeDate() {
    return diseaseClassificationChangeDate;
  }

  public void setDiseaseClassificationChangeDate(OffsetDateTime diseaseClassificationChangeDate) {
    this.diseaseClassificationChangeDate = diseaseClassificationChangeDate;
  }

  public InfrastructureChangeDatesDto diseaseConfigurationChangeDate(OffsetDateTime diseaseConfigurationChangeDate) {
    this.diseaseConfigurationChangeDate = diseaseConfigurationChangeDate;
    return this;
  }

   /**
   * Get diseaseConfigurationChangeDate
   * @return diseaseConfigurationChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getDiseaseConfigurationChangeDate() {
    return diseaseConfigurationChangeDate;
  }

  public void setDiseaseConfigurationChangeDate(OffsetDateTime diseaseConfigurationChangeDate) {
    this.diseaseConfigurationChangeDate = diseaseConfigurationChangeDate;
  }

  public InfrastructureChangeDatesDto userRoleConfigurationChangeDate(OffsetDateTime userRoleConfigurationChangeDate) {
    this.userRoleConfigurationChangeDate = userRoleConfigurationChangeDate;
    return this;
  }

   /**
   * Get userRoleConfigurationChangeDate
   * @return userRoleConfigurationChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getUserRoleConfigurationChangeDate() {
    return userRoleConfigurationChangeDate;
  }

  public void setUserRoleConfigurationChangeDate(OffsetDateTime userRoleConfigurationChangeDate) {
    this.userRoleConfigurationChangeDate = userRoleConfigurationChangeDate;
  }

  public InfrastructureChangeDatesDto featureConfigurationChangeDate(OffsetDateTime featureConfigurationChangeDate) {
    this.featureConfigurationChangeDate = featureConfigurationChangeDate;
    return this;
  }

   /**
   * Get featureConfigurationChangeDate
   * @return featureConfigurationChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getFeatureConfigurationChangeDate() {
    return featureConfigurationChangeDate;
  }

  public void setFeatureConfigurationChangeDate(OffsetDateTime featureConfigurationChangeDate) {
    this.featureConfigurationChangeDate = featureConfigurationChangeDate;
  }

  public InfrastructureChangeDatesDto campaignChangeDate(OffsetDateTime campaignChangeDate) {
    this.campaignChangeDate = campaignChangeDate;
    return this;
  }

   /**
   * Get campaignChangeDate
   * @return campaignChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getCampaignChangeDate() {
    return campaignChangeDate;
  }

  public void setCampaignChangeDate(OffsetDateTime campaignChangeDate) {
    this.campaignChangeDate = campaignChangeDate;
  }

  public InfrastructureChangeDatesDto campaignFormMetaChangeDate(OffsetDateTime campaignFormMetaChangeDate) {
    this.campaignFormMetaChangeDate = campaignFormMetaChangeDate;
    return this;
  }

   /**
   * Get campaignFormMetaChangeDate
   * @return campaignFormMetaChangeDate
  **/
  @Schema(description = "")
  public OffsetDateTime getCampaignFormMetaChangeDate() {
    return campaignFormMetaChangeDate;
  }

  public void setCampaignFormMetaChangeDate(OffsetDateTime campaignFormMetaChangeDate) {
    this.campaignFormMetaChangeDate = campaignFormMetaChangeDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfrastructureChangeDatesDto infrastructureChangeDatesDto = (InfrastructureChangeDatesDto) o;
    return Objects.equals(this.countryChangeDate, infrastructureChangeDatesDto.countryChangeDate) &&
        Objects.equals(this.regionChangeDate, infrastructureChangeDatesDto.regionChangeDate) &&
        Objects.equals(this.districtChangeDate, infrastructureChangeDatesDto.districtChangeDate) &&
        Objects.equals(this.communityChangeDate, infrastructureChangeDatesDto.communityChangeDate) &&
        Objects.equals(this.facilityChangeDate, infrastructureChangeDatesDto.facilityChangeDate) &&
        Objects.equals(this.pointOfEntryChangeDate, infrastructureChangeDatesDto.pointOfEntryChangeDate) &&
        Objects.equals(this.userChangeDate, infrastructureChangeDatesDto.userChangeDate) &&
        Objects.equals(this.diseaseClassificationChangeDate, infrastructureChangeDatesDto.diseaseClassificationChangeDate) &&
        Objects.equals(this.diseaseConfigurationChangeDate, infrastructureChangeDatesDto.diseaseConfigurationChangeDate) &&
        Objects.equals(this.userRoleConfigurationChangeDate, infrastructureChangeDatesDto.userRoleConfigurationChangeDate) &&
        Objects.equals(this.featureConfigurationChangeDate, infrastructureChangeDatesDto.featureConfigurationChangeDate) &&
        Objects.equals(this.campaignChangeDate, infrastructureChangeDatesDto.campaignChangeDate) &&
        Objects.equals(this.campaignFormMetaChangeDate, infrastructureChangeDatesDto.campaignFormMetaChangeDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryChangeDate, regionChangeDate, districtChangeDate, communityChangeDate, facilityChangeDate, pointOfEntryChangeDate, userChangeDate, diseaseClassificationChangeDate, diseaseConfigurationChangeDate, userRoleConfigurationChangeDate, featureConfigurationChangeDate, campaignChangeDate, campaignFormMetaChangeDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfrastructureChangeDatesDto {\n");
    
    sb.append("    countryChangeDate: ").append(toIndentedString(countryChangeDate)).append("\n");
    sb.append("    regionChangeDate: ").append(toIndentedString(regionChangeDate)).append("\n");
    sb.append("    districtChangeDate: ").append(toIndentedString(districtChangeDate)).append("\n");
    sb.append("    communityChangeDate: ").append(toIndentedString(communityChangeDate)).append("\n");
    sb.append("    facilityChangeDate: ").append(toIndentedString(facilityChangeDate)).append("\n");
    sb.append("    pointOfEntryChangeDate: ").append(toIndentedString(pointOfEntryChangeDate)).append("\n");
    sb.append("    userChangeDate: ").append(toIndentedString(userChangeDate)).append("\n");
    sb.append("    diseaseClassificationChangeDate: ").append(toIndentedString(diseaseClassificationChangeDate)).append("\n");
    sb.append("    diseaseConfigurationChangeDate: ").append(toIndentedString(diseaseConfigurationChangeDate)).append("\n");
    sb.append("    userRoleConfigurationChangeDate: ").append(toIndentedString(userRoleConfigurationChangeDate)).append("\n");
    sb.append("    featureConfigurationChangeDate: ").append(toIndentedString(featureConfigurationChangeDate)).append("\n");
    sb.append("    campaignChangeDate: ").append(toIndentedString(campaignChangeDate)).append("\n");
    sb.append("    campaignFormMetaChangeDate: ").append(toIndentedString(campaignFormMetaChangeDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
