/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.44.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import de.quarano.sormas.client.model.CommunityDto;
import de.quarano.sormas.client.model.DiseaseClassificationCriteriaDto;
import de.quarano.sormas.client.model.DiseaseConfigurationDto;
import de.quarano.sormas.client.model.DistrictDto;
import de.quarano.sormas.client.model.FacilityDto;
import de.quarano.sormas.client.model.FeatureConfigurationDto;
import de.quarano.sormas.client.model.PointOfEntryDto;
import de.quarano.sormas.client.model.RegionDto;
import de.quarano.sormas.client.model.UserDto;
import de.quarano.sormas.client.model.UserRoleConfigDto;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * InfrastructureSyncDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-09T17:56:16.099120+02:00[Europe/Berlin]")
public class InfrastructureSyncDto {
  @JsonProperty("initialSyncRequired")
  private Boolean initialSyncRequired = null;

  @JsonProperty("regions")
  private List<RegionDto> regions = null;

  @JsonProperty("districts")
  private List<DistrictDto> districts = null;

  @JsonProperty("communities")
  private List<CommunityDto> communities = null;

  @JsonProperty("facilities")
  private List<FacilityDto> facilities = null;

  @JsonProperty("pointsOfEntry")
  private List<PointOfEntryDto> pointsOfEntry = null;

  @JsonProperty("users")
  private List<UserDto> users = null;

  @JsonProperty("diseaseClassifications")
  private List<DiseaseClassificationCriteriaDto> diseaseClassifications = null;

  @JsonProperty("diseaseConfigurations")
  private List<DiseaseConfigurationDto> diseaseConfigurations = null;

  @JsonProperty("userRoleConfigurations")
  private List<UserRoleConfigDto> userRoleConfigurations = null;

  @JsonProperty("deletedUserRoleConfigurationUuids")
  private List<String> deletedUserRoleConfigurationUuids = null;

  @JsonProperty("featureConfigurations")
  private List<FeatureConfigurationDto> featureConfigurations = null;

  @JsonProperty("deletedFeatureConfigurationUuids")
  private List<String> deletedFeatureConfigurationUuids = null;

  public InfrastructureSyncDto initialSyncRequired(Boolean initialSyncRequired) {
    this.initialSyncRequired = initialSyncRequired;
    return this;
  }

   /**
   * Get initialSyncRequired
   * @return initialSyncRequired
  **/
  @Schema(description = "")
  public Boolean isInitialSyncRequired() {
    return initialSyncRequired;
  }

  public void setInitialSyncRequired(Boolean initialSyncRequired) {
    this.initialSyncRequired = initialSyncRequired;
  }

  public InfrastructureSyncDto regions(List<RegionDto> regions) {
    this.regions = regions;
    return this;
  }

  public InfrastructureSyncDto addRegionsItem(RegionDto regionsItem) {
    if (this.regions == null) {
      this.regions = new ArrayList<>();
    }
    this.regions.add(regionsItem);
    return this;
  }

   /**
   * Get regions
   * @return regions
  **/
  @Schema(description = "")
  public List<RegionDto> getRegions() {
    return regions;
  }

  public void setRegions(List<RegionDto> regions) {
    this.regions = regions;
  }

  public InfrastructureSyncDto districts(List<DistrictDto> districts) {
    this.districts = districts;
    return this;
  }

  public InfrastructureSyncDto addDistrictsItem(DistrictDto districtsItem) {
    if (this.districts == null) {
      this.districts = new ArrayList<>();
    }
    this.districts.add(districtsItem);
    return this;
  }

   /**
   * Get districts
   * @return districts
  **/
  @Schema(description = "")
  public List<DistrictDto> getDistricts() {
    return districts;
  }

  public void setDistricts(List<DistrictDto> districts) {
    this.districts = districts;
  }

  public InfrastructureSyncDto communities(List<CommunityDto> communities) {
    this.communities = communities;
    return this;
  }

  public InfrastructureSyncDto addCommunitiesItem(CommunityDto communitiesItem) {
    if (this.communities == null) {
      this.communities = new ArrayList<>();
    }
    this.communities.add(communitiesItem);
    return this;
  }

   /**
   * Get communities
   * @return communities
  **/
  @Schema(description = "")
  public List<CommunityDto> getCommunities() {
    return communities;
  }

  public void setCommunities(List<CommunityDto> communities) {
    this.communities = communities;
  }

  public InfrastructureSyncDto facilities(List<FacilityDto> facilities) {
    this.facilities = facilities;
    return this;
  }

  public InfrastructureSyncDto addFacilitiesItem(FacilityDto facilitiesItem) {
    if (this.facilities == null) {
      this.facilities = new ArrayList<>();
    }
    this.facilities.add(facilitiesItem);
    return this;
  }

   /**
   * Get facilities
   * @return facilities
  **/
  @Schema(description = "")
  public List<FacilityDto> getFacilities() {
    return facilities;
  }

  public void setFacilities(List<FacilityDto> facilities) {
    this.facilities = facilities;
  }

  public InfrastructureSyncDto pointsOfEntry(List<PointOfEntryDto> pointsOfEntry) {
    this.pointsOfEntry = pointsOfEntry;
    return this;
  }

  public InfrastructureSyncDto addPointsOfEntryItem(PointOfEntryDto pointsOfEntryItem) {
    if (this.pointsOfEntry == null) {
      this.pointsOfEntry = new ArrayList<>();
    }
    this.pointsOfEntry.add(pointsOfEntryItem);
    return this;
  }

   /**
   * Get pointsOfEntry
   * @return pointsOfEntry
  **/
  @Schema(description = "")
  public List<PointOfEntryDto> getPointsOfEntry() {
    return pointsOfEntry;
  }

  public void setPointsOfEntry(List<PointOfEntryDto> pointsOfEntry) {
    this.pointsOfEntry = pointsOfEntry;
  }

  public InfrastructureSyncDto users(List<UserDto> users) {
    this.users = users;
    return this;
  }

  public InfrastructureSyncDto addUsersItem(UserDto usersItem) {
    if (this.users == null) {
      this.users = new ArrayList<>();
    }
    this.users.add(usersItem);
    return this;
  }

   /**
   * Get users
   * @return users
  **/
  @Schema(description = "")
  public List<UserDto> getUsers() {
    return users;
  }

  public void setUsers(List<UserDto> users) {
    this.users = users;
  }

  public InfrastructureSyncDto diseaseClassifications(List<DiseaseClassificationCriteriaDto> diseaseClassifications) {
    this.diseaseClassifications = diseaseClassifications;
    return this;
  }

  public InfrastructureSyncDto addDiseaseClassificationsItem(DiseaseClassificationCriteriaDto diseaseClassificationsItem) {
    if (this.diseaseClassifications == null) {
      this.diseaseClassifications = new ArrayList<>();
    }
    this.diseaseClassifications.add(diseaseClassificationsItem);
    return this;
  }

   /**
   * Get diseaseClassifications
   * @return diseaseClassifications
  **/
  @Schema(description = "")
  public List<DiseaseClassificationCriteriaDto> getDiseaseClassifications() {
    return diseaseClassifications;
  }

  public void setDiseaseClassifications(List<DiseaseClassificationCriteriaDto> diseaseClassifications) {
    this.diseaseClassifications = diseaseClassifications;
  }

  public InfrastructureSyncDto diseaseConfigurations(List<DiseaseConfigurationDto> diseaseConfigurations) {
    this.diseaseConfigurations = diseaseConfigurations;
    return this;
  }

  public InfrastructureSyncDto addDiseaseConfigurationsItem(DiseaseConfigurationDto diseaseConfigurationsItem) {
    if (this.diseaseConfigurations == null) {
      this.diseaseConfigurations = new ArrayList<>();
    }
    this.diseaseConfigurations.add(diseaseConfigurationsItem);
    return this;
  }

   /**
   * Get diseaseConfigurations
   * @return diseaseConfigurations
  **/
  @Schema(description = "")
  public List<DiseaseConfigurationDto> getDiseaseConfigurations() {
    return diseaseConfigurations;
  }

  public void setDiseaseConfigurations(List<DiseaseConfigurationDto> diseaseConfigurations) {
    this.diseaseConfigurations = diseaseConfigurations;
  }

  public InfrastructureSyncDto userRoleConfigurations(List<UserRoleConfigDto> userRoleConfigurations) {
    this.userRoleConfigurations = userRoleConfigurations;
    return this;
  }

  public InfrastructureSyncDto addUserRoleConfigurationsItem(UserRoleConfigDto userRoleConfigurationsItem) {
    if (this.userRoleConfigurations == null) {
      this.userRoleConfigurations = new ArrayList<>();
    }
    this.userRoleConfigurations.add(userRoleConfigurationsItem);
    return this;
  }

   /**
   * Get userRoleConfigurations
   * @return userRoleConfigurations
  **/
  @Schema(description = "")
  public List<UserRoleConfigDto> getUserRoleConfigurations() {
    return userRoleConfigurations;
  }

  public void setUserRoleConfigurations(List<UserRoleConfigDto> userRoleConfigurations) {
    this.userRoleConfigurations = userRoleConfigurations;
  }

  public InfrastructureSyncDto deletedUserRoleConfigurationUuids(List<String> deletedUserRoleConfigurationUuids) {
    this.deletedUserRoleConfigurationUuids = deletedUserRoleConfigurationUuids;
    return this;
  }

  public InfrastructureSyncDto addDeletedUserRoleConfigurationUuidsItem(String deletedUserRoleConfigurationUuidsItem) {
    if (this.deletedUserRoleConfigurationUuids == null) {
      this.deletedUserRoleConfigurationUuids = new ArrayList<>();
    }
    this.deletedUserRoleConfigurationUuids.add(deletedUserRoleConfigurationUuidsItem);
    return this;
  }

   /**
   * Get deletedUserRoleConfigurationUuids
   * @return deletedUserRoleConfigurationUuids
  **/
  @Schema(description = "")
  public List<String> getDeletedUserRoleConfigurationUuids() {
    return deletedUserRoleConfigurationUuids;
  }

  public void setDeletedUserRoleConfigurationUuids(List<String> deletedUserRoleConfigurationUuids) {
    this.deletedUserRoleConfigurationUuids = deletedUserRoleConfigurationUuids;
  }

  public InfrastructureSyncDto featureConfigurations(List<FeatureConfigurationDto> featureConfigurations) {
    this.featureConfigurations = featureConfigurations;
    return this;
  }

  public InfrastructureSyncDto addFeatureConfigurationsItem(FeatureConfigurationDto featureConfigurationsItem) {
    if (this.featureConfigurations == null) {
      this.featureConfigurations = new ArrayList<>();
    }
    this.featureConfigurations.add(featureConfigurationsItem);
    return this;
  }

   /**
   * Get featureConfigurations
   * @return featureConfigurations
  **/
  @Schema(description = "")
  public List<FeatureConfigurationDto> getFeatureConfigurations() {
    return featureConfigurations;
  }

  public void setFeatureConfigurations(List<FeatureConfigurationDto> featureConfigurations) {
    this.featureConfigurations = featureConfigurations;
  }

  public InfrastructureSyncDto deletedFeatureConfigurationUuids(List<String> deletedFeatureConfigurationUuids) {
    this.deletedFeatureConfigurationUuids = deletedFeatureConfigurationUuids;
    return this;
  }

  public InfrastructureSyncDto addDeletedFeatureConfigurationUuidsItem(String deletedFeatureConfigurationUuidsItem) {
    if (this.deletedFeatureConfigurationUuids == null) {
      this.deletedFeatureConfigurationUuids = new ArrayList<>();
    }
    this.deletedFeatureConfigurationUuids.add(deletedFeatureConfigurationUuidsItem);
    return this;
  }

   /**
   * Get deletedFeatureConfigurationUuids
   * @return deletedFeatureConfigurationUuids
  **/
  @Schema(description = "")
  public List<String> getDeletedFeatureConfigurationUuids() {
    return deletedFeatureConfigurationUuids;
  }

  public void setDeletedFeatureConfigurationUuids(List<String> deletedFeatureConfigurationUuids) {
    this.deletedFeatureConfigurationUuids = deletedFeatureConfigurationUuids;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InfrastructureSyncDto infrastructureSyncDto = (InfrastructureSyncDto) o;
    return Objects.equals(this.initialSyncRequired, infrastructureSyncDto.initialSyncRequired) &&
        Objects.equals(this.regions, infrastructureSyncDto.regions) &&
        Objects.equals(this.districts, infrastructureSyncDto.districts) &&
        Objects.equals(this.communities, infrastructureSyncDto.communities) &&
        Objects.equals(this.facilities, infrastructureSyncDto.facilities) &&
        Objects.equals(this.pointsOfEntry, infrastructureSyncDto.pointsOfEntry) &&
        Objects.equals(this.users, infrastructureSyncDto.users) &&
        Objects.equals(this.diseaseClassifications, infrastructureSyncDto.diseaseClassifications) &&
        Objects.equals(this.diseaseConfigurations, infrastructureSyncDto.diseaseConfigurations) &&
        Objects.equals(this.userRoleConfigurations, infrastructureSyncDto.userRoleConfigurations) &&
        Objects.equals(this.deletedUserRoleConfigurationUuids, infrastructureSyncDto.deletedUserRoleConfigurationUuids) &&
        Objects.equals(this.featureConfigurations, infrastructureSyncDto.featureConfigurations) &&
        Objects.equals(this.deletedFeatureConfigurationUuids, infrastructureSyncDto.deletedFeatureConfigurationUuids);
  }

  @Override
  public int hashCode() {
    return Objects.hash(initialSyncRequired, regions, districts, communities, facilities, pointsOfEntry, users, diseaseClassifications, diseaseConfigurations, userRoleConfigurations, deletedUserRoleConfigurationUuids, featureConfigurations, deletedFeatureConfigurationUuids);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InfrastructureSyncDto {\n");
    
    sb.append("    initialSyncRequired: ").append(toIndentedString(initialSyncRequired)).append("\n");
    sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
    sb.append("    districts: ").append(toIndentedString(districts)).append("\n");
    sb.append("    communities: ").append(toIndentedString(communities)).append("\n");
    sb.append("    facilities: ").append(toIndentedString(facilities)).append("\n");
    sb.append("    pointsOfEntry: ").append(toIndentedString(pointsOfEntry)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("    diseaseClassifications: ").append(toIndentedString(diseaseClassifications)).append("\n");
    sb.append("    diseaseConfigurations: ").append(toIndentedString(diseaseConfigurations)).append("\n");
    sb.append("    userRoleConfigurations: ").append(toIndentedString(userRoleConfigurations)).append("\n");
    sb.append("    deletedUserRoleConfigurationUuids: ").append(toIndentedString(deletedUserRoleConfigurationUuids)).append("\n");
    sb.append("    featureConfigurations: ").append(toIndentedString(featureConfigurations)).append("\n");
    sb.append("    deletedFeatureConfigurationUuids: ").append(toIndentedString(deletedFeatureConfigurationUuids)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
