/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.52.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.OffsetDateTime;
/**
 * PersonFollowUpEndDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-15T22:47:05.366577+01:00[Europe/Berlin]")
public class PersonFollowUpEndDto {
  @JsonProperty("personUuid")
  private String personUuid = null;

  @JsonProperty("latestFollowUpEndDate")
  private OffsetDateTime latestFollowUpEndDate = null;

  public PersonFollowUpEndDto personUuid(String personUuid) {
    this.personUuid = personUuid;
    return this;
  }

   /**
   * Get personUuid
   * @return personUuid
  **/
  @Schema(description = "")
  public String getPersonUuid() {
    return personUuid;
  }

  public void setPersonUuid(String personUuid) {
    this.personUuid = personUuid;
  }

  public PersonFollowUpEndDto latestFollowUpEndDate(OffsetDateTime latestFollowUpEndDate) {
    this.latestFollowUpEndDate = latestFollowUpEndDate;
    return this;
  }

   /**
   * Get latestFollowUpEndDate
   * @return latestFollowUpEndDate
  **/
  @Schema(description = "")
  public OffsetDateTime getLatestFollowUpEndDate() {
    return latestFollowUpEndDate;
  }

  public void setLatestFollowUpEndDate(OffsetDateTime latestFollowUpEndDate) {
    this.latestFollowUpEndDate = latestFollowUpEndDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonFollowUpEndDto personFollowUpEndDto = (PersonFollowUpEndDto) o;
    return Objects.equals(this.personUuid, personFollowUpEndDto.personUuid) &&
        Objects.equals(this.latestFollowUpEndDate, personFollowUpEndDto.latestFollowUpEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personUuid, latestFollowUpEndDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonFollowUpEndDto {\n");
    
    sb.append("    personUuid: ").append(toIndentedString(personUuid)).append("\n");
    sb.append("    latestFollowUpEndDate: ").append(toIndentedString(latestFollowUpEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
