/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.44.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets SampleMaterial
 */
public enum SampleMaterial {
  BLOOD("BLOOD"),
  SERA("SERA"),
  STOOL("STOOL"),
  NASAL_SWAB("NASAL_SWAB"),
  THROAT_SWAB("THROAT_SWAB"),
  NP_SWAB("NP_SWAB"),
  RECTAL_SWAB("RECTAL_SWAB"),
  CEREBROSPINAL_FLUID("CEREBROSPINAL_FLUID"),
  CRUST("CRUST"),
  TISSUE("TISSUE"),
  URINE("URINE"),
  CORNEA_PM("CORNEA_PM"),
  SALIVA("SALIVA"),
  URINE_PM("URINE_PM"),
  NUCHAL_SKIN_BIOPSY("NUCHAL_SKIN_BIOPSY"),
  SPUTUM("SPUTUM"),
  ENDOTRACHEAL_ASPIRATE("ENDOTRACHEAL_ASPIRATE"),
  BRONCHOALVEOLAR_LAVAGE("BRONCHOALVEOLAR_LAVAGE"),
  BRAIN_TISSUE("BRAIN_TISSUE"),
  OTHER("OTHER");

  private String value;

  SampleMaterial(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SampleMaterial fromValue(String text) {
    for (SampleMaterial b : SampleMaterial.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
