= Developing the backend

== Code formatting

There's a code formatter for Eclipse available file://../../infrastructure/eclipse-code-formatter.xml[here].
Some additional settings that are not contained in the formatter:

=== Import order

* static imports, wild card used from the first declaration
* `\*` - all unmatched imports
* `java.…`
* `javax.–`
* `org.…`
* `com.…`

=== Blank lines

Use blank lines to group pieces of code logically: variable initializations go together, followed by the method invocations that use those variables.
There's no hard rule here.
It's just nice to be able to identify different steps in the execution order.

For blocks (if clauses, methods) we start with a blank line if the subsequent code is longer than a single line:

[source, java]
----
void someLongMethod() {

  // First statement
  // Second statement
}

VS.

void someOneLineMethod() {
  // Single-line statement
}
----

Symmetric blocks usually also use a blank line on the end to clearly separate the blocks' content from the outer instruction.
Again, the single line rule applies, here, too.

[source, java]
----
if (…) {
  // Single line instruction
} else {
  // Single line instruction
}

but

if (…) {

  // Multi-line instruction
  // Multi-line instruction

} else {

  // Multi-line instruction
  // Multi-line instruction
}
----

The intermediate lines surrounding the `…} else {…` make it easier to see where the block flips.

In general, for if-else-clauses, prefer the ternary expression (`condition ? if-true : if-false`) over an if block.
That creates incentives to rather extract the statements to be executed in either and make the overall expression readable.
If the overall expression gets so long it would line break, it's nice to read if the three parts are each brought onto a single line:

[source, java]
----
Object someMethod(…) {

  return condition
    ? if-true-do-this
    : else-do-that;
}
----

=== Organizing methods

For a consistent discovery experience, a class is organized as follows:

1. `static final` fields in descending visibility (public ones first)
2. `private final` fields
3. `private` fields
4. Constructors in descending visibility
5. Static factory methods
6. Methods to be implemented due to interface declarations
7. Self-declared methods in descending visibility. Methods overridden from super types folded into the visibility group but last. E.g. `equals(…)`/`hashCode()` would follow self-declared `public` methods but precede self-declared package-private and private ones.
8. `private static` methods
9. Nested classes

Methods that do not use any of the class' fields should be declared static to make obvious that they're not related to the state of the class.
That's particularly helpful to potentially identify methods that could live on the parameter types instead or a dedicated value object assembling some of the parameters in case there's an abstraction implicitly hidden in the code.

In unit test classes, there's no need to qualify the fields used to keep the class under test or mocks with visibility modifiers as they don't make a practical difference anyway.
The class under test usually goes first followed by fields for mocks needed etc.

=== Lombok

The project uses Lombok to reduce the cognitive overhead of boilerplate accessor methods, constructors etc.
While this is convenient, make sure you always use the Lombok means that match what you intend to achieve precisely.
It might be tempting to just declare `@Data` on a domain class but just like blindly letting an IDE generate that code one time, that might generate just too much code with unintended side effects.
Also, always double check the visibility of the generated artifacts.
Setters should usually go package protected at best, factory methods should be preferred over public constructors etc.

=== Further IDE settings

The code base generally assumes Eclipse's Save Actions for organized imports and formatting to be applied.
