/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.52.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.api;

import de.quarano.sormas.client.model.CampaignFormMetaDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CampaignFormMetaControllerApi
 */
@Ignore
public class CampaignFormMetaControllerApiTest {

    private final CampaignFormMetaControllerApi api = new CampaignFormMetaControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCampaignFormMetaTest() {
        Long since = null;
        List<CampaignFormMetaDto> response = api.getAllCampaignFormMeta(since);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUuids3Test() {
        List<String> response = api.getAllUuids3();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByUuids4Test() {
        List<String> body = null;
        List<CampaignFormMetaDto> response = api.getByUuids4(body);

        // TODO: test validations
    }
}
