/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.44.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.api;

import de.quarano.sormas.client.model.DiseaseConfigurationDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DiseaseConfigurationControllerApi
 */
@Ignore
public class DiseaseConfigurationControllerApiTest {

    private final DiseaseConfigurationControllerApi api = new DiseaseConfigurationControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllDiseaseConfigurationsTest() {
        Long since = null;
        List<DiseaseConfigurationDto> response = api.getAllDiseaseConfigurations(since);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUuids3Test() {
        List<String> response = api.getAllUuids3();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByUuids6Test() {
        List<String> body = null;
        List<DiseaseConfigurationDto> response = api.getByUuids6(body);

        // TODO: test validations
    }
}
