/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.44.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.api;

import de.quarano.sormas.client.model.FeatureConfigurationDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FeatureConfigurationControllerApi
 */
@Ignore
public class FeatureConfigurationControllerApiTest {

    private final FeatureConfigurationControllerApi api = new FeatureConfigurationControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllFeatureConfigurationsTest() {
        Long since = null;
        List<FeatureConfigurationDto> response = api.getAllFeatureConfigurations(since);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUuids6Test() {
        List<String> response = api.getAllUuids6();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByUuids11Test() {
        List<String> body = null;
        List<FeatureConfigurationDto> response = api.getByUuids11(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDeletedUuidsTest() {
        Long since = null;
        List<String> response = api.getDeletedUuids(since);

        // TODO: test validations
    }
}
