/*
 * SORMAS REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.52.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.quarano.sormas.client.api;

import de.quarano.sormas.client.model.PushResult;
import de.quarano.sormas.client.model.SampleDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SampleControllerApi
 */
@Ignore
public class SampleControllerApiTest {

    private final SampleControllerApi api = new SampleControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllActiveUuids7Test() {
        List<String> response = api.getAllActiveUuids7();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllSamplesTest() {
        Long since = null;
        List<SampleDto> response = api.getAllSamples(since);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByCaseUuidsTest() {
        List<String> body = null;
        List<SampleDto> response = api.getByCaseUuids(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByUuids22Test() {
        List<String> body = null;
        List<SampleDto> response = api.getByUuids22(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDeletedUuidsSince5Test() {
        Long since = null;
        List<String> response = api.getDeletedUuidsSince5(since);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postSamplesTest() {
        List<SampleDto> body = null;
        List<PushResult> response = api.postSamples(body);

        // TODO: test validations
    }
}
