package quarano.reference.web;

import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import quarano.reference.FrontendText;
import quarano.reference.web.FrontendTextRepresentations.FrontendTextDto;

import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.stream.Collectors;

import org.apache.commons.lang3.RandomStringUtils;
import org.springframework.hateoas.RepresentationModel;
import org.springframework.hateoas.mediatype.hal.HalModelBuilder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * @author Jens Kutzsche
 */
@RestController
@RequiredArgsConstructor
public class FrontendTextControler {

	private final @NonNull FrontendTextRepresentations representations;

	@GetMapping(path = "/api/frontendtexts")
	public RepresentationModel<?> getText(@RequestParam("key") Optional<String> key) {

		var text1 = new FrontendText("Key 1", Locale.GERMANY, AGB);

		int length = 10;
		var generatedString = RandomStringUtils.randomAlphanumeric(length);
		var text2 = new FrontendText("Key 2", Locale.GERMANY, generatedString);

		generatedString = RandomStringUtils.randomAlphanumeric(length);
		var text3 = new FrontendText("Key 3", Locale.GERMANY, generatedString);

		var entities = List.of(text1, text2, text3);

		var dtos = entities.stream().map(it -> representations.toDto(it)).collect(Collectors.toList());

		return HalModelBuilder.emptyHalModel()
				.embed(dtos, FrontendTextDto.class)
				.build();
	}

	private static final String AGB = "<mat-card class=\"form__card--animated\">"
			+ "  <mat-card-header>"
			+ "    <mat-card-title><h1>AGB</h1></mat-card-title>"
			+ "  </mat-card-header>"
			+ "  <mat-card-content>"
			+ "    <ol class=\"main-list\">"
			+ "      <li>"
			+ "        <h2>Inhalt und Zustandekommen</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Parteien und Gegenstand: Dieser Vertrag regelt das rechtliche Verhältnis zwischen dem Quarano e. V., c/o"
			+ "            Ferdinand Biere Rheinstraße 24 in 12161 Berlin (\"quarano\") und deren Kunden (\"Kunde\") in Bezug auf die zur"
			+ "            Verfügungstellung von Software zur Nutzung über das Internet (Software as a Service). Für die entsprechende"
			+ "            zur Verfügungstellung einzelner Softwareprodukte gelten ergänzend die jeweiligen ServiceBedingungen. Im"
			+ "            Falle eines Widerspruchs zwischen diesen Allgemeinen Geschäftsbedingungen und den Service-Bedingungen gehen"
			+ "            die Service-Bedingungen vor."
			+ "          </li>"
			+ "          <li>"
			+ "            Pflichten im elektronischen Geschäftsverkehr: § 312g Abs. 1 Nr.1, 2 und 3 sowie § 312g Abs. 1 Satz 2 BGB,"
			+ "            die bei Verträgen im elektronischen Geschäftsverkehr bestimmte Verpflichtungen des Unternehmers vorsehen,"
			+ "            werden abbedungen."
			+ "          </li>"
			+ "          <li>"
			+ "            Pflichten im elektronischen Geschäftsverkehr: § 312g Abs. 1 Nr.1, 2 und 3 sowie § 312g Abs. 1 Satz 2 BGB,"
			+ "            die bei Verträgen im elektronischen Geschäftsverkehr bestimmte Verpflichtungen des Unternehmers vorsehen,"
			+ "            werden abbedungen."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Leistungen von quarano</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Nutzungsrecht: quarano stellt dem Kunden das in den Service-Bedingungen bezeichnete und beschriebene"
			+ "            Softwareprodukt (\"Software\") zur Nutzung über das Internet zur Verfügung (\"Service\"). Die Software wird auf"
			+ "            Computern eines von quarano genutzten Rechenzentrums betrieben, der Kunde erhält für die Laufzeit dieses"
			+ "            Vertrages das nicht ausschließliche und nicht übertragbare Recht, auf die Software mittels eines Browsers"
			+ "            und einer Internetverbindung zuzugreifen und für eigene Geschäftszwecke ausschließlich in Ausübung seiner"
			+ "            gewerblichen oder selbständigen beruflichen Tätigkeit zu nutzen (\"Service\"). Für die Internetverbindung"
			+ "            zwischen dem Kunden und dem Rechenzentrum und die hierfür erforderliche Hard- und Software (z. B. PC,"
			+ "            Netzanschluss, Browser) ist der Kunde verantwortlich. Das Nutzungsrecht ist beschränkt auf die vom Kunden"
			+ "            gebuchte Anzahl von Nutzungseinheiten (z. B. Anzahl der Nutzer oder verwalteten Geräte). Die"
			+ "            Nutzungseinheiten sind in den Service-Bedingungen bezeichnet. Eine Nutzungsüberlassung oder Bereitstellung"
			+ "            des Services an Dritte ist untersagt. quarano erbringt ihre Leistungen nicht für Verbraucher, sondern"
			+ "            ausschließlich für die Zwecke der gewerblichen oder selbständigen beruflichen Tätigkeit des Kunden."
			+ "          </li>"
			+ "          <li>"
			+ "            Einrichtung: Der Kunde nimmt die erstmalige Einrichtung des Services (individuelle Einstellungen oder Import"
			+ "            von Daten) selbst vor. Eine Veränderung des Services, insbesondere eine Umprogrammierung nach Wünschen des"
			+ "            Kunden, ist nicht geschuldet. Entsprechende Serviceleistungen sind besonders zu vereinbaren und zu vergüten."
			+ "          </li>"
			+ "          <li>"
			+ "            Support: quarano stellt einen kostenlosen Online-Support zur Unterstützung bei der Nutzung des Services zur"
			+ "            Verfügung. Der Support beinhaltet nicht: Allgemeinen Knowhow-Transfer, Schulungen, Konfiguration und"
			+ "            Implementierung oder kundenspezifische Dokumentation oder Anpassung der Software. Der Support erfolgt"
			+ "            ausschließlich per E-Mail. Die Supportleistungen werden von quarano werktäglich Montag bis Donnerstag in der"
			+ "            Zeit von 8.00 Uhr - 17.00 Uhr sowie Freitag von 08:00 Uhr – 14:00 Uhr erbracht. Ausgenommen hiervon sind"
			+ "            Feiertage in Berlin sowie der 24. und 31.12. eines jeden Jahres. Anfragen, die außerhalb dieser"
			+ "            Supportzeiten eingehen, gelten als während des nächstfolgenden Werktages eingegangen."
			+ "          </li>"
			+ "          <li>"
			+ "            Leistungsänderungen: quarano kann den Service (einschließlich dessen Systemanforderungen) zur Anpassung an"
			+ "            technische oder wirtschaftliche Marktveränderungen und aus wichtigem Grund ändern. Ein solcher liegt"
			+ "            insbesondere vor, wenn die Änderung erforderlich ist , aufgrund (i) einer notwendigen Anpassung an eine neue"
			+ "            Rechtslage oder Rechtsprechung, (ii) geänderten technischen Rahmenbedingungen (neue Browserversionen oder"
			+ "            technische Standards), (iii) des Schutzes der Systemsicherheit, oder (iv) der Fortentwicklung des Services"
			+ "            (Abschaltung alter Funktionen, die durch neue weitgehend ersetzt wurden). quarano wird den Kunden auf für"
			+ "            ihn nachteilige Änderung rechtzeitig, in der Regel zwei Wochen vor dem Inkrafttreten - per E-Mail hinweisen."
			+ "            Die Zustimmung des Kunden zu einer solchen Änderung gilt als erteilt, wenn der Kunde der Änderung nicht bis"
			+ "            zum Änderungstermin schriftlich oder per E-Mail widerspricht. Bei der Ankündigung der Änderung wird quarano"
			+ "            auf diese Rechtsfolge noch einmal gesondert hinweisen. Würde die Änderung das vertragliche Gleichgewicht"
			+ "            zwischen den Parteien zu Lasten des Kunden erheblich stören, unterbleibt die Änderung."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Vergütung und Zahlungsverzug</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Vergütung: Der Kunde schuldet quarano für die Nutzung des Services während der Vertragslaufzeit die in der"
			+ "            Service-Beschreibung vereinbarte Vergütung. Die Vergütung kann bestehen aus einem einmaligen"
			+ "            Einrichtungsbetrag, einer festen monatlichen Grundbetrag und einem von der Anzahl der gebuchten oder in"
			+ "            Anspruch genommenen Nutzungseinheiten abhängigen monatlichen Nutzungsbetrag."
			+ "          </li>"
			+ "          <li>"
			+ "            Entstehen des Grund- und Nutzungsbetrags: Der Grund- und Nutzungsbetrag wird mit Vertragsbeginn für die"
			+ "            Grundlaufzeit (siehe Ziffer 9(2)) und danach mit Beginn einer jeden Verlängerungslaufzeit (siehe Ziffer"
			+ "            9(2)) für die Verlängerungslaufzeit jeweils im Voraus voll fällig. Eine Erhöhung der gebuchten"
			+ "            Nutzungseinheiten (bzw. Wechsel in ein höheres Leistungspaket) ist jederzeit möglich, eine Reduzierung (bzw."
			+ "            Wechsel in ein niedrigeres Leistungspaket) ist nur mit Wirkung zum Ende der Grund- oder einer"
			+ "            Verlängerungslaufzeit oder davor mit Zustimmung von quarano möglich. Im Falle einer Erhöhung der gebuchten"
			+ "            Nutzungseinheiten innerhalb der Grund- oder einer Verlängerungslaufzeit wird der zusätzliche Betrag anteilig"
			+ "            in Rechnung gestellt. Für die zusätzlichen Nutzungseinheiten gelten die Preise gemäß der bei Bestellung der"
			+ "            zusätzlichen Nutzungseinheiten gültigen Preisliste von quarano."
			+ "          </li>"
			+ "          <li>"
			+ "            Rechnungsstellung: quarano stellt den Betrag zu Vertragsbeginn und sodann zu Beginn jeder"
			+ "            Verlängerungslaufzeit im Voraus in Rechnung. Der Rechnungsbetrag ist innerhalb von 10 Tagen zu zahlen."
			+ "          </li>"
			+ "          <li>"
			+ "            Nettopreise: Alle Preise verstehen sich zuzüglich der jeweils geltenden gesetzlichen Umsatzsteuer."
			+ "          </li>"
			+ "          <li>"
			+ "            Zahlungsverzug: Kommt der Kunde für zwei Kalendermonate mit der Bezahlung der Vergütung oder eines nicht"
			+ "            unerheblichen Teils der Vergütung oder in einem Zeitraum, der sich über mehr als zwei Monate erstreckt, mit"
			+ "            der Bezahlung der Vergütung in Höhe eines Betrages, der das doppelte einer monatlichen Grund- plus"
			+ "            Nutzungsbetrag erreicht, in Verzug, ist quarano berechtigt, nach entsprechender Androhung per E-Mail oder"
			+ "            per Brief den Zugang zum Service zu sperren oder den Vertrag außerordentlich zu kündigen. Während der"
			+ "            Sperrung hat der Kunde keinen Zugriff auf die im Service gespeicherten Daten. Im Falle einer Kündigung"
			+ "            findet Ziffer 9(4) Anwendung."
			+ "          </li>"
			+ "          <li>"
			+ "            Preisänderungen: quarano ist berechtigt, die mit dem Kunden vereinbarten Preise jeweils mit Ablauf von"
			+ "            mindestens 12 Monaten seit dem Wirksamwerden der letzten Preisänderung (erstmals jedoch frühestens 24 Monate"
			+ "            nach Abschluss des Software as a Service Vertrages) mit Wirkung zu Beginn der folgenden"
			+ "            Verlängerungslaufzeit zu erhöhen oder zu reduzieren. Eine solche Preiserhöhung darf pro Vertragsjahr nicht"
			+ "            mehr als 5% betragen, es sei denn, die Arbeitskosten von quarano für die Leistungserbringung sind um mehr"
			+ "            als 5% pro Vertragsjahr gestiegen. Die geänderten Preise werden wirksam, wenn (i ) quarano sie dem Kunden"
			+ "            mindestens sechs Wochen vor Wirksamwerden vorab schriftlich oder per E-Mail ankündigt und (ii) der Kunde"
			+ "            ihnen nicht innerhalb von sechs Wochen nach der Mitteilung schriftlich oder per E-Mail widerspricht. Bei der"
			+ "            Ankündigung der Preisänderung wird quarano auf diese Rechtsfolge noch einmal gesondert hinweisen."
			+ "            Widerspricht der Kunde, so gelten die bisherigen Preise weiter. quarano hat das Recht gemäß Ziffer 9(2) den"
			+ "            Vertrag ordentlich zu kündigen."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Pflichten und Obliegenheiten des Kunden</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Sicherungskopien. Dem Kunden obliegt es, regelmäßig Kopien der von ihm eingegebenen Daten zu exportieren und"
			+ "            Sicherungskopien anzufertigen oder die entsprechenden Informationen auszudrucken und aufzubewahren."
			+ "          </li>"
			+ "          <li>"
			+ "            Systemanforderungen und Mitwirkungspflicht: Anforderungen an Hard- und Software beim Kunden sowie"
			+ "            organisatorische Anforderungen und Mitwirkungspflichten des Kunden sind in den ServiceBedingungen geregelt."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Kundendaten und Datenschutz</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Kundendaten: Die vom Kunden im Rahmen der Nutzung des Services eingegebenen und die dabei erzeugten und dem"
			+ "            Kunden zurechenbaren Daten (\"Kundendaten\") stehen ausschließlich dem Kunden zu. quarano behandelt die"
			+ "            Kundendaten vertraulich."
			+ "          </li>"
			+ "          <li>"
			+ "            Auftragsdatenverarbeitung: Soweit es sich bei den Kundendaten um personenbezogene Daten handelt, gilt"
			+ "            Folgendes: quarano verarbeitet die Kundendaten als Auftragsverarbeiter im Sinne von Artikel 28 DSGVO"
			+ "            ausschließlich im Auftrag und nach den Weisungen des Kunden und ausschließlich zum Zwecke der Bereitstellung"
			+ "            des Services. quarano trifft angemessene technische und organisatorische Maßnahmen zum Schutz der"
			+ "            Kundendaten. Der Kunde bleibt für die Rechtmäßigkeit der Erhebung, Verarbeitung und Nutzung der Kundendaten"
			+ "            gemäß den gesetzlichen Bestimmungen, insbesondere des BDSG und der DSGVO, verantwortlich. quarano ist"
			+ "            berechtigt, als Rechenzentrum einen in der Europäischen Union oder dem Europäischen Wirtschaftsraum"
			+ "            ansässigen Hoster einzusetzen. Einzelheiten regeln die Parteien in einem gesonderten Vertrag zur"
			+ "            Auftragsdatenverarbeitung."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Mängelansprüche</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Mängelbeseitigung: Mängel des Services meldet der Kunde unverzüglich an quarano und erläutert die näheren"
			+ "            Umstände des Zustandekommens. quarano wird den Mangel innerhalb angemessener Frist beseitigen. quarano ist"
			+ "            berechtigt, den Mangel durch eine Workaround-Lösung zu umgehen, wenn die Mangelursache selbst nur mit"
			+ "            unverhältnismäßigem Aufwand zu beseitigen ist und die Nutzbarkeit des Services nicht erheblich leidet."
			+ "          </li>"
			+ "          <li>"
			+ "            Service Levels: Etwaige Service Levels für die Mängelbeseitigung einzelner Services sind in der"
			+ "            Service-Beschreibung geregelt."
			+ "          </li>"
			+ "          <li>"
			+ "            Anfängliche Unmöglichkeit: Die verschuldensunabhängige Haftung für anfängliche Mängel gemäß § 536a Abs. 1,"
			+ "            Alt. 1 des Bürgerlichen Gesetzbuches wird ausgeschlossen."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Freistellungspflichten</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Pflicht zur Freistellung: Machen Dritte (einschließlich öffentliche Stellen) gegenüber quarano Ansprüche"
			+ "            bzw. Rechtsverletzungen geltend, die auf der Behauptung beruhen, dass der Kunde gegen seine vertraglichen"
			+ "            Pflichten verstoßen hat, insbesondere rechtswidrige Daten in den Service eingespielt oder den Service in"
			+ "            wettbewerbswidriger oder sonst rechtswidriger Weise genutzt hat, so gilt Folgendes: Der Kunde wird quarano"
			+ "            von diesen Ansprüchen unverzüglich freistellen, quarano bei der Rechtsverteidigung angemessene Unterstützung"
			+ "            bieten und quarano von den Kosten der Rechtsverteidigung freistellen."
			+ "          </li>"
			+ "          <li>"
			+ "            Voraussetzungen der Freistellungspflicht: Voraussetzung für die Freistellungspflicht nach Ziffer 7(1) ist,"
			+ "            dass quarano den Kunden über geltend gemachte Ansprüche unverzüglich schriftlich informiert, keine"
			+ "            Anerkenntnisse oder gleichkommende Erklärungen abgibt und es dem Kunden ermöglicht, auf Kosten des Kunden -"
			+ "            soweit möglich - alle gerichtlichen und außergerichtlichen Verhandlungen über die Ansprüche zu führen."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Haftung</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            quarano haftet für Schäden, soweit diese vorsätzlich oder grob fahrlässig von quarano verursacht wurden,"
			+ "            oder leicht fahrlässig von quarano verursacht wurden und auf wesentliche Pflichtverletzungen zurückzuführen"
			+ "            sind, die die Erreichung des Zwecks dieses Vertrages gefährden, oder auf die Verletzung von Pflichten, deren"
			+ "            Erfüllung die ordnungsgemäße Durchführung dieses Vertrages erst ermöglicht und auf deren Einhaltung der"
			+ "            Kunde vertrauen darf (z. B. Kundendaten sind vollständig verloren und auch Altbestände sind nicht"
			+ "            rekonstruierbar). Im Übrigen ist die Haftung von quarano unabhängig von deren Rechtsgrund ausgeschlossen,"
			+ "            außer quarano haftet kraft Gesetzes zwingend, insbesondere wegen Verletzung von Leben, Körper oder"
			+ "            Gesundheit einer Person, Übernahme einer ausdrücklichen Garantie, arglistigen Verschweigens eines Mangels"
			+ "            oder nach dem Produkthaftungsgesetz. Garantien durch quarano erfolgen nur schriftlich und sind als solche zu"
			+ "            bezeichnen."
			+ "          </li>"
			+ "          <li>"
			+ "            Begrenzung der Höhe nach: Im Falle von Ziffer 8(1) b) haftet quarano nur begrenzt auf den für einen Vertrag"
			+ "            dieser Art typischerweise vorhersehbaren Schaden."
			+ "          </li>"
			+ "          <li>"
			+ "            Mitarbeiter und Beauftragte von quarano: Die Haftungsbeschränkungen der Ziffern 8(1) und 8(2) gelten auch"
			+ "            bei Ansprüchen gegen Mitarbeiter und Beauftragte von quarano."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Laufzeit und Kündigung</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Kostenlose Testphase: Soweit in den Service-Bedingungen nichts Abweichendes geregelt ist, gilt für die"
			+ "            Laufzeit des Vertrages in Bezug auf einen einzelnen Service Folgendes: Mit Vertragsschluss beginnt zunächst"
			+ "            eine 30-tägige Testphase. In der Testphase fallen keine Einrichtungs-, Grund- oder Nutzungsvergütungen an."
			+ "            Der Vertrag endet automatisch mit Ablauf der Testphase, wenn der Kunde den Service nicht ausdrücklich für"
			+ "            eine sich anschließende weitere Laufzeit bestellt. Hierauf wird der Kunde vor Ablauf der Testphase"
			+ "            hingewiesen. Bestellt der Kunde den Service für eine weitere Laufzeit, so beginnt mit Ablauf der Testphase"
			+ "            die Grundlaufzeit gemäß Ziffer 9(2)."
			+ "          </li>"
			+ "          <li>"
			+ "            Laufzeit: Der Vertrag ist je nach Bestellung des Kunden für eine bestimmte Laufzeit (z. B. sechs, zwölf,"
			+ "            achtzehn oder vierundzwanzig Monate) geschlossen (\"Grundlaufzeit\") und verlängert sich anschließend"
			+ "            automatisch um den selben Zeitraum (\"Verlängerungslaufzeit\"), wenn der Vertrag nicht von einer Partei mit"
			+ "            einer Frist von vier Wochen (\"Kündigungsfrist\") zum Ende der Grund- oder einer Verlängerungslaufzeit"
			+ "            gekündigt wurde. Das Recht zur Kündigung aus wichtigem Grund bleibt unberührt. Für die Reduzierung von"
			+ "            Nutzungseinheiten gilt Ziffer 3(2)."
			+ "          </li>"
			+ "          <li>Form: Die Kündigung muss schriftlich erfolgen.</li>"
			+ "          <li>"
			+ "            Daten bei Vertragsende: Der Kunde kann die Kundendaten über die Export -Funktionen des jeweiligen Services"
			+ "            während der Vertragslaufzeit exportieren. Nach Ende der Vertragslaufzeit hat der Kunde keinen Zugriff mehr"
			+ "            auf die Kundendaten. Mit Ablauf von einem Monat nach Vertragsende – oder vorher auf Verlangen des Kunden -"
			+ "            wird quarano die Kundendaten endgültig und vollständig löschen, sofern dem nicht gesetzliche"
			+ "            Aufbewahrungspflichten von quarano entgegenstehen. Zu einer abweichenden Herausgabe der Kundendaten (z. B."
			+ "            betreffend Zeit, Format oder Migration) ist quarano nur verpflichtet, wenn dies gesondert vereinbart und"
			+ "            vergütet wird."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Schlussbestimmungen</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Service-Bedingungen: Die Service-Bedingungen des jeweils beauftragten Services sind Vertragsbestandteil."
			+ "          </li>"
			+ "          <li>"
			+ "            Aufrechnung: Der Kunde kann mit anderen Ansprüchen als mit seinen vertraglichen Gegenforderungen aus dem"
			+ "            jeweils betroffenen Rechtsgeschäft nur aufrechnen oder ein Zurückbehaltungsrecht geltend machen, wenn dieser"
			+ "            Anspruch von quarano unbestritten oder rechtskräftig festgestellt ist."
			+ "          </li>"
			+ "          <li>"
			+ "            Schriftform: Änderungen dieses Vertrages bedürfen der Schriftform. Dies gilt auch für die Abbedingung des"
			+ "            Schriftformerfordernisses."
			+ "          </li>"
			+ "          <li>"
			+ "            Anwendbares Recht: Auf diesen Vertrag findet ausschließlich deutsches Recht unter Ausschluss des UN"
			+ "            Kaufrechts Anwendung."
			+ "          </li>"
			+ "          <li>"
			+ "            Gerichtsstand: Ist der Kunde Kaufmann, eine juristische Person des öffentlichen Rechts oder ein"
			+ "            öffentlich-rechtliches Sondervermögen, so gilt als Gerichtsstand der für den Firmensitz von quarano"
			+ "            zuständige Gerichtsort. quarano ist auch berechtigt, vor einem Gericht zu klagen, welches für den Sitz oder"
			+ "            eine Niederlassung des Kunden zuständig ist."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "    </ol>"
			+ "  </mat-card-content>"
			+ "</mat-card>";
}
