package quarano.masterdata.web;

import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import quarano.masterdata.FrontendText;
import quarano.masterdata.web.FrontendTextRepresentations.FrontendTextDto;

import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.stream.Collectors;

import org.springframework.hateoas.RepresentationModel;
import org.springframework.hateoas.mediatype.hal.HalModelBuilder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * @author Jens Kutzsche
 */
@RestController
@RequiredArgsConstructor
public class FrontendTextController {

	private final @NonNull FrontendTextRepresentations representations;

	@GetMapping(path = "/api/frontendtexts")
	public RepresentationModel<?> getText(@RequestParam("key") Optional<String> key) {

		var terms = new FrontendText("terms", Locale.GERMAN, AGB);
		var dataProtection = new FrontendText("data-protection", Locale.GERMAN, DATA_PROTECTION);
		var imprint = new FrontendText("imprint", Locale.GERMAN, IMPRINT);
		var welcomeIndex = new FrontendText("welcome-index", Locale.GERMAN, WELCOME_INDEX);
		var welcomeContact = new FrontendText("welcome-contact", Locale.GERMAN, WELCOME_CONTACT);

		var dtos = List.of(terms, dataProtection, imprint, welcomeIndex, welcomeContact).stream()
				.map(it -> representations.toRepresentation(it))
				.collect(Collectors.toList());

		return HalModelBuilder.emptyHalModel()
				.embed(dtos, FrontendTextDto.class)
				.build();
	}

	private static final String AGB = "    <ol class=\"main-list\">"
			+ "      <li>"
			+ "        <h2>Inhalt und Zustandekommen</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Parteien und Gegenstand: Dieser Vertrag regelt das rechtliche Verhältnis zwischen dem Quarano e. V., c/o"
			+ "            Ferdinand Biere Rheinstraße 24 in 12161 Berlin (\"quarano\") und deren Kunden (\"Kunde\") in Bezug auf die zur"
			+ "            Verfügungstellung von Software zur Nutzung über das Internet (Software as a Service). Für die entsprechende"
			+ "            zur Verfügungstellung einzelner Softwareprodukte gelten ergänzend die jeweiligen ServiceBedingungen. Im"
			+ "            Falle eines Widerspruchs zwischen diesen Allgemeinen Geschäftsbedingungen und den Service-Bedingungen gehen"
			+ "            die Service-Bedingungen vor."
			+ "          </li>"
			+ "          <li>"
			+ "            Pflichten im elektronischen Geschäftsverkehr: § 312g Abs. 1 Nr.1, 2 und 3 sowie § 312g Abs. 1 Satz 2 BGB,"
			+ "            die bei Verträgen im elektronischen Geschäftsverkehr bestimmte Verpflichtungen des Unternehmers vorsehen,"
			+ "            werden abbedungen."
			+ "          </li>"
			+ "          <li>"
			+ "            Pflichten im elektronischen Geschäftsverkehr: § 312g Abs. 1 Nr.1, 2 und 3 sowie § 312g Abs. 1 Satz 2 BGB,"
			+ "            die bei Verträgen im elektronischen Geschäftsverkehr bestimmte Verpflichtungen des Unternehmers vorsehen,"
			+ "            werden abbedungen."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Leistungen von quarano</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Nutzungsrecht: quarano stellt dem Kunden das in den Service-Bedingungen bezeichnete und beschriebene"
			+ "            Softwareprodukt (\"Software\") zur Nutzung über das Internet zur Verfügung (\"Service\"). Die Software wird auf"
			+ "            Computern eines von quarano genutzten Rechenzentrums betrieben, der Kunde erhält für die Laufzeit dieses"
			+ "            Vertrages das nicht ausschließliche und nicht übertragbare Recht, auf die Software mittels eines Browsers"
			+ "            und einer Internetverbindung zuzugreifen und für eigene Geschäftszwecke ausschließlich in Ausübung seiner"
			+ "            gewerblichen oder selbständigen beruflichen Tätigkeit zu nutzen (\"Service\"). Für die Internetverbindung"
			+ "            zwischen dem Kunden und dem Rechenzentrum und die hierfür erforderliche Hard- und Software (z. B. PC,"
			+ "            Netzanschluss, Browser) ist der Kunde verantwortlich. Das Nutzungsrecht ist beschränkt auf die vom Kunden"
			+ "            gebuchte Anzahl von Nutzungseinheiten (z. B. Anzahl der Nutzer oder verwalteten Geräte). Die"
			+ "            Nutzungseinheiten sind in den Service-Bedingungen bezeichnet. Eine Nutzungsüberlassung oder Bereitstellung"
			+ "            des Services an Dritte ist untersagt. quarano erbringt ihre Leistungen nicht für Verbraucher, sondern"
			+ "            ausschließlich für die Zwecke der gewerblichen oder selbständigen beruflichen Tätigkeit des Kunden."
			+ "          </li>"
			+ "          <li>"
			+ "            Einrichtung: Der Kunde nimmt die erstmalige Einrichtung des Services (individuelle Einstellungen oder Import"
			+ "            von Daten) selbst vor. Eine Veränderung des Services, insbesondere eine Umprogrammierung nach Wünschen des"
			+ "            Kunden, ist nicht geschuldet. Entsprechende Serviceleistungen sind besonders zu vereinbaren und zu vergüten."
			+ "          </li>"
			+ "          <li>"
			+ "            Support: quarano stellt einen kostenlosen Online-Support zur Unterstützung bei der Nutzung des Services zur"
			+ "            Verfügung. Der Support beinhaltet nicht: Allgemeinen Knowhow-Transfer, Schulungen, Konfiguration und"
			+ "            Implementierung oder kundenspezifische Dokumentation oder Anpassung der Software. Der Support erfolgt"
			+ "            ausschließlich per E-Mail. Die Supportleistungen werden von quarano werktäglich Montag bis Donnerstag in der"
			+ "            Zeit von 8.00 Uhr - 17.00 Uhr sowie Freitag von 08:00 Uhr – 14:00 Uhr erbracht. Ausgenommen hiervon sind"
			+ "            Feiertage in Berlin sowie der 24. und 31.12. eines jeden Jahres. Anfragen, die außerhalb dieser"
			+ "            Supportzeiten eingehen, gelten als während des nächstfolgenden Werktages eingegangen."
			+ "          </li>"
			+ "          <li>"
			+ "            Leistungsänderungen: quarano kann den Service (einschließlich dessen Systemanforderungen) zur Anpassung an"
			+ "            technische oder wirtschaftliche Marktveränderungen und aus wichtigem Grund ändern. Ein solcher liegt"
			+ "            insbesondere vor, wenn die Änderung erforderlich ist , aufgrund (i) einer notwendigen Anpassung an eine neue"
			+ "            Rechtslage oder Rechtsprechung, (ii) geänderten technischen Rahmenbedingungen (neue Browserversionen oder"
			+ "            technische Standards), (iii) des Schutzes der Systemsicherheit, oder (iv) der Fortentwicklung des Services"
			+ "            (Abschaltung alter Funktionen, die durch neue weitgehend ersetzt wurden). quarano wird den Kunden auf für"
			+ "            ihn nachteilige Änderung rechtzeitig, in der Regel zwei Wochen vor dem Inkrafttreten - per E-Mail hinweisen."
			+ "            Die Zustimmung des Kunden zu einer solchen Änderung gilt als erteilt, wenn der Kunde der Änderung nicht bis"
			+ "            zum Änderungstermin schriftlich oder per E-Mail widerspricht. Bei der Ankündigung der Änderung wird quarano"
			+ "            auf diese Rechtsfolge noch einmal gesondert hinweisen. Würde die Änderung das vertragliche Gleichgewicht"
			+ "            zwischen den Parteien zu Lasten des Kunden erheblich stören, unterbleibt die Änderung."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Vergütung und Zahlungsverzug</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Vergütung: Der Kunde schuldet quarano für die Nutzung des Services während der Vertragslaufzeit die in der"
			+ "            Service-Beschreibung vereinbarte Vergütung. Die Vergütung kann bestehen aus einem einmaligen"
			+ "            Einrichtungsbetrag, einer festen monatlichen Grundbetrag und einem von der Anzahl der gebuchten oder in"
			+ "            Anspruch genommenen Nutzungseinheiten abhängigen monatlichen Nutzungsbetrag."
			+ "          </li>"
			+ "          <li>"
			+ "            Entstehen des Grund- und Nutzungsbetrags: Der Grund- und Nutzungsbetrag wird mit Vertragsbeginn für die"
			+ "            Grundlaufzeit (siehe Ziffer 9(2)) und danach mit Beginn einer jeden Verlängerungslaufzeit (siehe Ziffer"
			+ "            9(2)) für die Verlängerungslaufzeit jeweils im Voraus voll fällig. Eine Erhöhung der gebuchten"
			+ "            Nutzungseinheiten (bzw. Wechsel in ein höheres Leistungspaket) ist jederzeit möglich, eine Reduzierung (bzw."
			+ "            Wechsel in ein niedrigeres Leistungspaket) ist nur mit Wirkung zum Ende der Grund- oder einer"
			+ "            Verlängerungslaufzeit oder davor mit Zustimmung von quarano möglich. Im Falle einer Erhöhung der gebuchten"
			+ "            Nutzungseinheiten innerhalb der Grund- oder einer Verlängerungslaufzeit wird der zusätzliche Betrag anteilig"
			+ "            in Rechnung gestellt. Für die zusätzlichen Nutzungseinheiten gelten die Preise gemäß der bei Bestellung der"
			+ "            zusätzlichen Nutzungseinheiten gültigen Preisliste von quarano."
			+ "          </li>"
			+ "          <li>"
			+ "            Rechnungsstellung: quarano stellt den Betrag zu Vertragsbeginn und sodann zu Beginn jeder"
			+ "            Verlängerungslaufzeit im Voraus in Rechnung. Der Rechnungsbetrag ist innerhalb von 10 Tagen zu zahlen."
			+ "          </li>"
			+ "          <li>"
			+ "            Nettopreise: Alle Preise verstehen sich zuzüglich der jeweils geltenden gesetzlichen Umsatzsteuer."
			+ "          </li>"
			+ "          <li>"
			+ "            Zahlungsverzug: Kommt der Kunde für zwei Kalendermonate mit der Bezahlung der Vergütung oder eines nicht"
			+ "            unerheblichen Teils der Vergütung oder in einem Zeitraum, der sich über mehr als zwei Monate erstreckt, mit"
			+ "            der Bezahlung der Vergütung in Höhe eines Betrages, der das doppelte einer monatlichen Grund- plus"
			+ "            Nutzungsbetrag erreicht, in Verzug, ist quarano berechtigt, nach entsprechender Androhung per E-Mail oder"
			+ "            per Brief den Zugang zum Service zu sperren oder den Vertrag außerordentlich zu kündigen. Während der"
			+ "            Sperrung hat der Kunde keinen Zugriff auf die im Service gespeicherten Daten. Im Falle einer Kündigung"
			+ "            findet Ziffer 9(4) Anwendung."
			+ "          </li>"
			+ "          <li>"
			+ "            Preisänderungen: quarano ist berechtigt, die mit dem Kunden vereinbarten Preise jeweils mit Ablauf von"
			+ "            mindestens 12 Monaten seit dem Wirksamwerden der letzten Preisänderung (erstmals jedoch frühestens 24 Monate"
			+ "            nach Abschluss des Software as a Service Vertrages) mit Wirkung zu Beginn der folgenden"
			+ "            Verlängerungslaufzeit zu erhöhen oder zu reduzieren. Eine solche Preiserhöhung darf pro Vertragsjahr nicht"
			+ "            mehr als 5% betragen, es sei denn, die Arbeitskosten von quarano für die Leistungserbringung sind um mehr"
			+ "            als 5% pro Vertragsjahr gestiegen. Die geänderten Preise werden wirksam, wenn (i ) quarano sie dem Kunden"
			+ "            mindestens sechs Wochen vor Wirksamwerden vorab schriftlich oder per E-Mail ankündigt und (ii) der Kunde"
			+ "            ihnen nicht innerhalb von sechs Wochen nach der Mitteilung schriftlich oder per E-Mail widerspricht. Bei der"
			+ "            Ankündigung der Preisänderung wird quarano auf diese Rechtsfolge noch einmal gesondert hinweisen."
			+ "            Widerspricht der Kunde, so gelten die bisherigen Preise weiter. quarano hat das Recht gemäß Ziffer 9(2) den"
			+ "            Vertrag ordentlich zu kündigen."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Pflichten und Obliegenheiten des Kunden</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Sicherungskopien. Dem Kunden obliegt es, regelmäßig Kopien der von ihm eingegebenen Daten zu exportieren und"
			+ "            Sicherungskopien anzufertigen oder die entsprechenden Informationen auszudrucken und aufzubewahren."
			+ "          </li>"
			+ "          <li>"
			+ "            Systemanforderungen und Mitwirkungspflicht: Anforderungen an Hard- und Software beim Kunden sowie"
			+ "            organisatorische Anforderungen und Mitwirkungspflichten des Kunden sind in den ServiceBedingungen geregelt."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Kundendaten und Datenschutz</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Kundendaten: Die vom Kunden im Rahmen der Nutzung des Services eingegebenen und die dabei erzeugten und dem"
			+ "            Kunden zurechenbaren Daten (\"Kundendaten\") stehen ausschließlich dem Kunden zu. quarano behandelt die"
			+ "            Kundendaten vertraulich."
			+ "          </li>"
			+ "          <li>"
			+ "            Auftragsdatenverarbeitung: Soweit es sich bei den Kundendaten um personenbezogene Daten handelt, gilt"
			+ "            Folgendes: quarano verarbeitet die Kundendaten als Auftragsverarbeiter im Sinne von Artikel 28 DSGVO"
			+ "            ausschließlich im Auftrag und nach den Weisungen des Kunden und ausschließlich zum Zwecke der Bereitstellung"
			+ "            des Services. quarano trifft angemessene technische und organisatorische Maßnahmen zum Schutz der"
			+ "            Kundendaten. Der Kunde bleibt für die Rechtmäßigkeit der Erhebung, Verarbeitung und Nutzung der Kundendaten"
			+ "            gemäß den gesetzlichen Bestimmungen, insbesondere des BDSG und der DSGVO, verantwortlich. quarano ist"
			+ "            berechtigt, als Rechenzentrum einen in der Europäischen Union oder dem Europäischen Wirtschaftsraum"
			+ "            ansässigen Hoster einzusetzen. Einzelheiten regeln die Parteien in einem gesonderten Vertrag zur"
			+ "            Auftragsdatenverarbeitung."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Mängelansprüche</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Mängelbeseitigung: Mängel des Services meldet der Kunde unverzüglich an quarano und erläutert die näheren"
			+ "            Umstände des Zustandekommens. quarano wird den Mangel innerhalb angemessener Frist beseitigen. quarano ist"
			+ "            berechtigt, den Mangel durch eine Workaround-Lösung zu umgehen, wenn die Mangelursache selbst nur mit"
			+ "            unverhältnismäßigem Aufwand zu beseitigen ist und die Nutzbarkeit des Services nicht erheblich leidet."
			+ "          </li>"
			+ "          <li>"
			+ "            Service Levels: Etwaige Service Levels für die Mängelbeseitigung einzelner Services sind in der"
			+ "            Service-Beschreibung geregelt."
			+ "          </li>"
			+ "          <li>"
			+ "            Anfängliche Unmöglichkeit: Die verschuldensunabhängige Haftung für anfängliche Mängel gemäß § 536a Abs. 1,"
			+ "            Alt. 1 des Bürgerlichen Gesetzbuches wird ausgeschlossen."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Freistellungspflichten</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Pflicht zur Freistellung: Machen Dritte (einschließlich öffentliche Stellen) gegenüber quarano Ansprüche"
			+ "            bzw. Rechtsverletzungen geltend, die auf der Behauptung beruhen, dass der Kunde gegen seine vertraglichen"
			+ "            Pflichten verstoßen hat, insbesondere rechtswidrige Daten in den Service eingespielt oder den Service in"
			+ "            wettbewerbswidriger oder sonst rechtswidriger Weise genutzt hat, so gilt Folgendes: Der Kunde wird quarano"
			+ "            von diesen Ansprüchen unverzüglich freistellen, quarano bei der Rechtsverteidigung angemessene Unterstützung"
			+ "            bieten und quarano von den Kosten der Rechtsverteidigung freistellen."
			+ "          </li>"
			+ "          <li>"
			+ "            Voraussetzungen der Freistellungspflicht: Voraussetzung für die Freistellungspflicht nach Ziffer 7(1) ist,"
			+ "            dass quarano den Kunden über geltend gemachte Ansprüche unverzüglich schriftlich informiert, keine"
			+ "            Anerkenntnisse oder gleichkommende Erklärungen abgibt und es dem Kunden ermöglicht, auf Kosten des Kunden -"
			+ "            soweit möglich - alle gerichtlichen und außergerichtlichen Verhandlungen über die Ansprüche zu führen."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Haftung</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            quarano haftet für Schäden, soweit diese vorsätzlich oder grob fahrlässig von quarano verursacht wurden,"
			+ "            oder leicht fahrlässig von quarano verursacht wurden und auf wesentliche Pflichtverletzungen zurückzuführen"
			+ "            sind, die die Erreichung des Zwecks dieses Vertrages gefährden, oder auf die Verletzung von Pflichten, deren"
			+ "            Erfüllung die ordnungsgemäße Durchführung dieses Vertrages erst ermöglicht und auf deren Einhaltung der"
			+ "            Kunde vertrauen darf (z. B. Kundendaten sind vollständig verloren und auch Altbestände sind nicht"
			+ "            rekonstruierbar). Im Übrigen ist die Haftung von quarano unabhängig von deren Rechtsgrund ausgeschlossen,"
			+ "            außer quarano haftet kraft Gesetzes zwingend, insbesondere wegen Verletzung von Leben, Körper oder"
			+ "            Gesundheit einer Person, Übernahme einer ausdrücklichen Garantie, arglistigen Verschweigens eines Mangels"
			+ "            oder nach dem Produkthaftungsgesetz. Garantien durch quarano erfolgen nur schriftlich und sind als solche zu"
			+ "            bezeichnen."
			+ "          </li>"
			+ "          <li>"
			+ "            Begrenzung der Höhe nach: Im Falle von Ziffer 8(1) b) haftet quarano nur begrenzt auf den für einen Vertrag"
			+ "            dieser Art typischerweise vorhersehbaren Schaden."
			+ "          </li>"
			+ "          <li>"
			+ "            Mitarbeiter und Beauftragte von quarano: Die Haftungsbeschränkungen der Ziffern 8(1) und 8(2) gelten auch"
			+ "            bei Ansprüchen gegen Mitarbeiter und Beauftragte von quarano."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Laufzeit und Kündigung</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Kostenlose Testphase: Soweit in den Service-Bedingungen nichts Abweichendes geregelt ist, gilt für die"
			+ "            Laufzeit des Vertrages in Bezug auf einen einzelnen Service Folgendes: Mit Vertragsschluss beginnt zunächst"
			+ "            eine 30-tägige Testphase. In der Testphase fallen keine Einrichtungs-, Grund- oder Nutzungsvergütungen an."
			+ "            Der Vertrag endet automatisch mit Ablauf der Testphase, wenn der Kunde den Service nicht ausdrücklich für"
			+ "            eine sich anschließende weitere Laufzeit bestellt. Hierauf wird der Kunde vor Ablauf der Testphase"
			+ "            hingewiesen. Bestellt der Kunde den Service für eine weitere Laufzeit, so beginnt mit Ablauf der Testphase"
			+ "            die Grundlaufzeit gemäß Ziffer 9(2)."
			+ "          </li>"
			+ "          <li>"
			+ "            Laufzeit: Der Vertrag ist je nach Bestellung des Kunden für eine bestimmte Laufzeit (z. B. sechs, zwölf,"
			+ "            achtzehn oder vierundzwanzig Monate) geschlossen (\"Grundlaufzeit\") und verlängert sich anschließend"
			+ "            automatisch um den selben Zeitraum (\"Verlängerungslaufzeit\"), wenn der Vertrag nicht von einer Partei mit"
			+ "            einer Frist von vier Wochen (\"Kündigungsfrist\") zum Ende der Grund- oder einer Verlängerungslaufzeit"
			+ "            gekündigt wurde. Das Recht zur Kündigung aus wichtigem Grund bleibt unberührt. Für die Reduzierung von"
			+ "            Nutzungseinheiten gilt Ziffer 3(2)."
			+ "          </li>"
			+ "          <li>Form: Die Kündigung muss schriftlich erfolgen.</li>"
			+ "          <li>"
			+ "            Daten bei Vertragsende: Der Kunde kann die Kundendaten über die Export -Funktionen des jeweiligen Services"
			+ "            während der Vertragslaufzeit exportieren. Nach Ende der Vertragslaufzeit hat der Kunde keinen Zugriff mehr"
			+ "            auf die Kundendaten. Mit Ablauf von einem Monat nach Vertragsende – oder vorher auf Verlangen des Kunden -"
			+ "            wird quarano die Kundendaten endgültig und vollständig löschen, sofern dem nicht gesetzliche"
			+ "            Aufbewahrungspflichten von quarano entgegenstehen. Zu einer abweichenden Herausgabe der Kundendaten (z. B."
			+ "            betreffend Zeit, Format oder Migration) ist quarano nur verpflichtet, wenn dies gesondert vereinbart und"
			+ "            vergütet wird."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "      <li>"
			+ "        <h2>Schlussbestimmungen</h2>"
			+ "        <ol>"
			+ "          <li>"
			+ "            Service-Bedingungen: Die Service-Bedingungen des jeweils beauftragten Services sind Vertragsbestandteil."
			+ "          </li>"
			+ "          <li>"
			+ "            Aufrechnung: Der Kunde kann mit anderen Ansprüchen als mit seinen vertraglichen Gegenforderungen aus dem"
			+ "            jeweils betroffenen Rechtsgeschäft nur aufrechnen oder ein Zurückbehaltungsrecht geltend machen, wenn dieser"
			+ "            Anspruch von quarano unbestritten oder rechtskräftig festgestellt ist."
			+ "          </li>"
			+ "          <li>"
			+ "            Schriftform: Änderungen dieses Vertrages bedürfen der Schriftform. Dies gilt auch für die Abbedingung des"
			+ "            Schriftformerfordernisses."
			+ "          </li>"
			+ "          <li>"
			+ "            Anwendbares Recht: Auf diesen Vertrag findet ausschließlich deutsches Recht unter Ausschluss des UN"
			+ "            Kaufrechts Anwendung."
			+ "          </li>"
			+ "          <li>"
			+ "            Gerichtsstand: Ist der Kunde Kaufmann, eine juristische Person des öffentlichen Rechts oder ein"
			+ "            öffentlich-rechtliches Sondervermögen, so gilt als Gerichtsstand der für den Firmensitz von quarano"
			+ "            zuständige Gerichtsort. quarano ist auch berechtigt, vor einem Gericht zu klagen, welches für den Sitz oder"
			+ "            eine Niederlassung des Kunden zuständig ist."
			+ "          </li>"
			+ "        </ol>"
			+ "      </li>"
			+ "    </ol>";

	private static final String DATA_PROTECTION = "<h2>Informationen zum Datenschutz</h2>"
			+ "<p>"
			+ "  Die folgenden Informationen zum Datenschutz sind ab dem 25. Mai 2018 gültig und spiegeln die gesteigerten"
			+ "  Transparenzanforderungen der EU-Datenschutz-Grundverordnung wieder."
			+ "</p>"
			+ "<h2>Verantwortliche nach DSGVO</h2>"
			+ "<h2>Verarbeitung personenbezogener Daten</h2>"
			+ "<p>"
			+ "  Die mit dieser Applikation verarbeiteten personenbezogenen Daten werden ausschließlich zum Zweck der Nachverfolgung"
			+ "  von bestätigten Corona-Infizierungen oder -Verdachtsfälle erhoben. Grundlage der Verarbeitung bildet das Gesetz zur"
			+ "  Verhütung und Bekämpfung von Infektionskrankheiten beim Menschen (Infektionsschutzgesetz - IfSG) und dem"
			+ "  CoronaVMeldeV."
			+ "</p>"
			+ "<p>"
			+ "  Folgende Personenbezogene Daten des Infektionsbetroffenen werden erfasst und verarbeitet:"
			+ "</p>"
			+ "<ul>"
			+ "  <li>Identifikationsdaten</li>"
			+ "  <li>Adressdaten</li>"
			+ "  <li>Berufliche Tätigkeiten</li>"
			+ "  <li>Gesundheitliche Betreuung</li>"
			+ "  <li>Befund des Infektionsbetroffenen</li>"
			+ "</ul>"
			+ "<p>"
			+ "  Sowie die folgenden Personenbezogenen Daten von Kontaktpersonen des Infektionsbetroffenen:"
			+ "</p>"
			+ "<ul>"
			+ "  <li>Identifikationsdaten</li>"
			+ "  <li>Adressdaten</li>"
			+ "</ul>"
			+ "<p>"
			+ "  Alle hier aufgeführten Personenbezogenen Daten sind nach dem Infektionsschutzgesetz und nachfolgend zur"
			+ "  Corona-Pandemie erlassenden Verordnungen verpflichtend vom Betroffenen einer bestätigten Corona-Infizierung oder"
			+ "  –Verdachtsfalles anzugeben."
			+ "</p>"
			+ "<p>"
			+ "  Darüber hinaus sind ebenso verpflichtend die Personenbezogenen Daten von Kontaktpersonen anzugeben."
			+ "</p>"
			+ "<h2>Verwendung von Cookies sowie PlugIns von Drittanbietern</h2>"
			+ "<p>"
			+ "  In unserer Applikation werden keine Daten erhoben, die über Cookies oder über PlugIns von Drittanbietern weiteren"
			+ "  Unternehmen oder Organisationen als das für den Infektionsbetroffenen zuständige Gesundheitsamt weitergegeben werden."
			+ "</p>"
			+ "<h2>Rechte des Betroffenen nach DSGVO</h2>"
			+ "<p>"
			+ "  Die über die DSGVO geltenden Rechte zum Betroffenenschutz bleiben bestehen, soweit diese mit den geltenden Gesetzen"
			+ "  und Verordnungen zum Infektionsschutz anwendbar sind:"
			+ "</p>"
			+ "<ul>"
			+ "  <li>Recht auf Auskunft, Art. 15 DSGVO</li>"
			+ "  <li>Recht auf Berichtigung, Art. 16 DSGVO</li>"
			+ "  <li>Recht auf Löschung („Recht auf Vergessenwerden“), Art. 17 DSGVO</li>"
			+ "  <li>Recht auf Einschränkung der Verarbeitung, Art. 18 DSGVO</li>"
			+ "  <li>Recht auf Datenübertragbarkeit, Art. 20 DSGVO</li>"
			+ "  <li>Recht auf Widerspruch, Art. 21 DSGVO</li>"
			+ "</ul>"
			+ "<p>"
			+ "  Informationen zum Recht auf Löschung (Art. 17 DSGVO) und Recht auf Einschränkung der Verarbeitung (Art. 18 DSGVO)"
			+ "</p>"
			+ "<p>"
			+ "  Über die in dem Infektionsschutzgesetz definierten Meldepflichten sind die Rechte zu Löschung und der Einschränkung"
			+ "  der Verarbeitung nur eingeschränkt gültig, da die erhobenen Personenbezogenen Daten verpflichtend erhoben werden"
			+ "  müssen."
			+ "</p>"
			+ "<h2>Recht auf Beschwerde</h2>"
			+ "<p>"
			+ "  Darüber hinaus haben Sie nach Art. 77 DSGVO i.V.m. § 19 BDSG das Recht auf Beschwerde bei einer Aufsichtsbehörde. Die"
			+ "  für den Betroffenen zuständige Aufsichtsbehörde richtet sich nach dem Bundesland des für den Betroffenen zuständigen"
			+ "  Gesundheitsamt."
			+ "</p>";

	private static final String IMPRINT = "    <p>"
			+ "      Unser Impressum gilt für die Seite quarano.de sowie für Quarano auf Youtube und Twitter."
			+ "    </p>"
			+ "    <h2>Angaben gemäß § 5 TMG</h2>"
			+ "    <p>Quarano e. V.<br />Rheinstraße 24<br />c/o Ferdinand Biere<br />12161 Berlin</p>"
			+ "    <p>"
			+ "      <strong>Vertreten durch:</strong><br />Vorsitzender: Ferdinand Biere, Berlin<br />Stellvertretender Vorsitzender:"
			+ "      Bodo Biere, Berlin<br />Schriftführer: Thomas C.V. Schmidt, Berlin"
			+ "    </p>"
			+ "    <h2>Kontakt</h2>"
			+ "    <p>Telefon: 030-555742080<br />Telefax: 030-555742089<br />E-Mail: info@quarano.de</p>"
			+ "    <h2>Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV</h2>"
			+ "    <p>Ferdinand Biere<br />Rheinstraße 24<br />12161 Berlin</p>"
			+ "    <h2>EU-Streitschlichtung</h2>"
			+ "    <p>"
			+ "      Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit:"
			+ "      https://ec.europa.eu/consumers/odr. Unsere E-Mail-Adresse finden Sie oben im Impressum."
			+ "    </p>"
			+ "    <h2>Verbraucher­streit­beilegung/Universal­schlichtungs­stelle</h2>"
			+ "    <p>"
			+ "      Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle"
			+ "      teilzunehmen."
			+ "    </p>"
			+ "    <h2>Haftung für Inhalte</h2>"
			+ "    <p>"
			+ "      Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen"
			+ "      Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte"
			+ "      oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige"
			+ "      Tätigkeit hinweisen."
			+ "    </p>"
			+ "    <p>"
			+ "      Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben"
			+ "      hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten"
			+ "      Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte"
			+ "      umgehend entfernen."
			+ "    </p>"
			+ "    <h2>Haftung für Links</h2>"
			+ "    <p>"
			+ "      Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb"
			+ "      können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets"
			+ "      der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der"
			+ "      Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht"
			+ "      erkennbar."
			+ "    </p>"
			+ "    <p>"
			+ "      Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer"
			+ "      Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend"
			+ "      entfernen."
			+ "    </p>"
			+ "    <h2>Urheberrecht</h2>"
			+ "    <p>"
			+ "      Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen"
			+ "      Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des"
			+ "      Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien"
			+ "      dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet."
			+ "    </p>"
			+ "    <p>"
			+ "      Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter"
			+ "      beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine"
			+ "      Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von"
			+ "      Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen."
			+ "    </p>"
			+ "    <p>Quelle: <a href=\"https://www.e-recht24.de\">eRecht24</a></p>";

	private static final String WELCOME_INDEX = "<section>"
			+ "  <p>"
			+ "    Sie haben vom Gesundheitsamt Mannheim einen personalisierten Registrierungs-Link erhalten. In den folgenden"
			+ "    Seiten melden Sie sich bitte an und nutzen die Anwendung. Mit der Nutzung dieser Anwendung unterstützen Sie das"
			+ "    Gesundheitsamt und tragen dazu bei, dass schneller agiert werden kann."
			+ "  </p>"
			+ "  <p>"
			+ "    Mit der Anwendung können Sie:"
			+ "  </p>"
			+ "  <ul>"
			+ "    <li>Ihre Stammdaten aktualisieren</li>"
			+ "    <li>Kontaktpersonen angeben</li>"
			+ "    <li>Mögliche Krankheitszeichen protokollieren</li>"
			+ "  </ul>"
			+ "  <h3><strong>Infos zur Registrierung</strong></h3>"
			+ "  <p>"
			+ "    Registrieren Sie sich mit einem Benutzernamen und einem frei wählbaren Passwort. Danach melden Sie sich mit"
			+ "    diesen Nutzerdaten an und können quarano nutzen:"
			+ "  </p>"
			+ "  <h3><strong>Infos zur Nutzung</strong></h3>"
			+ "  <p>"
			+ "    Ihre Stammdaten sind nur einmal einzugeben, Kontaktpersonen und mögliche Krankheitszeichen sind zweimal täglich"
			+ "    einzugeben."
			+ "  </p>"
			+ "  <p>"
			+ "    <strong>Wichtig:</strong> Dieser Link ist nur für Sie persönlich gültig. Wenn mehrere betroffene Personen im"
			+ "    selben Haushalt leben, ist es wichtig, dass sich jede Person mit einem eigenen Zugangslink vom Gesundheitsamt"
			+ "    jeweils einen eigenen Benutzer anlegt. So können alle Einträge immer richtig zugeordnet werden."
			+ "  </p>"
			+ "  <p>"
			+ "    Bei Fragen scheuen Sie sich bitte nicht, uns zu kontaktieren. Bei allgemeinen Fragen zum Thema Corona wenden Sie"
			+ "    sich bitte an die Corona-Hotline der Stadt Mannheim unter der Telefonnummer"
			+ "    <a href=\"tel:+496212932253\" class=\"phone-link\">0621-293 2253</a>:"
			+ "  </p>"
			+ "  <ul>"
			+ "    <li>Montag bis Freitag von 9:00 – 17:00 Uhr</li>"
			+ "    <li>Samstags sowie an Sonn- und Feiertagen von 9:00 – 14:00 Uhr</li>"
			+ "  </ul>"
			+ "  <p>Ihr Gesundheitsamt Mannheim</p>"
			+ "  <p class=\"footnote\">"
			+ "    <em"
			+ "      >Wenn Sie akut ärztliche Behandlung benötigen, wenden Sie sich an Ihren Hausarzt/Ihre Hausärztin. Nachts und"
			+ "      am Wochenende stehen der hausärztliche Bereitschaftsdienst (116 117) oder in schwerwiegenden Fällen die"
			+ "      Notaufnahmen der Kliniken als Anlaufstelle zur Verfügung. In akuten Notfällen zögern Sie bitte nicht, den"
			+ "      Rettungsdienst unter der 112 zu rufen. Vor einer persönlichen Vorstellung beim Arzt oder im Krankenhaus muss"
			+ "      die telefonische Ankündigung mit Hinweis auf COVID-19 erfolgen und dass Sie aktuell unter Quarantäne"
			+ "      stehen.</em"
			+ "    >"
			+ "  </p>"
			+ "</section>";

	private static final String WELCOME_CONTACT = "<section>"
			+ "  <p>"
			+ "    Sie haben vom Gesundheitsamt Mannheim einen personalisierten Registrierungs-Link erhalten. In den folgenden"
			+ "    Seiten melden Sie sich bitte an und nutzen die Anwendung. Mit der Nutzung dieser Anwendung unterstützen Sie das"
			+ "    Gesundheitsamt und tragen dazu bei, dass schneller agiert werden kann."
			+ "  </p>"
			+ "  <p>"
			+ "    Mit der Anwendung können Sie:"
			+ "  </p>"
			+ "  <ul>"
			+ "    <li>Ihre Stammdaten aktualisieren</li>"
			+ "    <li>Kontaktpersonen angeben</li>"
			+ "    <li>Mögliche Krankheitszeichen protokollieren</li>"
			+ "  </ul>"
			+ "  <h3><strong>Infos zur Registrierung</strong></h3>"
			+ "  <p>"
			+ "    Registrieren Sie sich mit einem Benutzernamen und einem frei wählbaren Passwort. Danach melden Sie sich mit"
			+ "    diesen Nutzerdaten an und können quarano nutzen:"
			+ "  </p>"
			+ "  <h3><strong>Infos zur Nutzung</strong></h3>"
			+ "  <p>"
			+ "    Ihre Stammdaten sind nur einmal einzugeben, Kontaktpersonen und mögliche Krankheitszeichen sind zweimal täglich"
			+ "    einzugeben."
			+ "  </p>"
			+ "  <p>"
			+ "    <strong>Wichtig:</strong> Dieser Link ist nur für Sie persönlich gültig. Wenn mehrere betroffene Personen im"
			+ "    selben Haushalt leben, ist es wichtig, dass sich jede Person mit einem eigenen Zugangslink vom Gesundheitsamt"
			+ "    jeweils einen eigenen Benutzer anlegt. So können alle Einträge immer richtig zugeordnet werden."
			+ "  </p>"
			+ "  <p>"
			+ "    Bei Fragen scheuen Sie sich bitte nicht, uns zu kontaktieren. Bei allgemeinen Fragen zum Thema Corona wenden Sie"
			+ "    sich bitte an die Corona-Hotline der Stadt Mannheim unter der Telefonnummer"
			+ "    <a href=\"tel:+496212932253\" class=\"phone-link\">0621-293 2253</a>:"
			+ "  </p>"
			+ "  <ul>"
			+ "    <li>Montag bis Freitag von 9:00 – 17:00 Uhr</li>"
			+ "    <li>Samstags sowie an Sonn- und Feiertagen von 9:00 – 14:00 Uhr</li>"
			+ "  </ul>"
			+ "  <p>"
			+ "    Bei Fragen, die Sie als Kontaktperson im Speziellen betreffen, wenden Sie sich bitte an die Hotline für"
			+ "    Kontaktpersonen unter der Telefonnummer <a href=\"tel:+496212932212\" class=\"phone-link\">0621-293 2212</a>:"
			+ "  </p>"
			+ "  <ul>"
			+ "    <li>Montag bis Freitag von 8:30 – 13:30 Uhr</li>"
			+ "    <li>Samstags sowie an Sonn- und Feiertagen von 10:00 – 14:00 Uhr</li>"
			+ "  </ul>"
			+ "  <p>Ihr Gesundheitsamt Mannheim</p>"
			+ "  <p class=\"footnote\">"
			+ "    <em"
			+ "      >Wenn Sie akut ärztliche Behandlung benötigen, wenden Sie sich an Ihren Hausarzt/Ihre Hausärztin. Nachts und"
			+ "      am Wochenende stehen der hausärztliche Bereitschaftsdienst (116 117) oder in schwerwiegenden Fällen die"
			+ "      Notaufnahmen der Kliniken als Anlaufstelle zur Verfügung. In akuten Notfällen zögern Sie bitte nicht, den"
			+ "      Rettungsdienst unter der 112 zu rufen. Vor einer persönlichen Vorstellung beim Arzt oder im Krankenhaus muss"
			+ "      die telefonische Ankündigung mit Hinweis auf COVID-19 erfolgen und dass Sie aktuell unter Quarantäne"
			+ "      stehen.</em"
			+ "    >"
			+ "  </p>"
			+ "</section>";
}
